<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Libraries</li>
</ul>
<h1>Libraries</h1>
Страница в разработке!
<table class="table table-hover">
    <tr>
        <th>Name of library</th>
        <th>Actions</th>
    </tr>
    <tr>
        <td>Regions</td>
        <td>
            <a href="/admin/libraries/regions" class="btn">List</a>
            <a href="/admin/libraries/region/add" class="btn btn-primary">Add</a></td>
    </tr>
    <tr>
        <td>Countries</td>
        <td>
            <a href="/admin/libraries/countries" class="btn">List</a>
            <a href="/admin/libraries/country/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Cities</td>
        <td>
            <a href="/admin/libraries/cities" class="btn">List</a>
            <a href="/admin/libraries/city/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Airports</td>
        <td>
            <a href="/admin/libraries/airports" class="btn">List</a>
            <a href="/admin/libraries/airport/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Types Aircraft</td>
        <td>
            <a href="/admin/libraries/aircraft_types" class="btn">List</a>
            <a href="/admin/libraries/aircraft_type/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Aircrafts</td>
        <td>
            <a href="/admin/libraries/aircrafts" class="btn">List</a>
            <a href="/admin/libraries/aircraft/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Air Operators</td>
        <td>
            <a href="/admin/libraries/air_operators" class="btn">List</a>
            <a href="/admin/libraries/air_operator/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Kontragents</td>
        <td>
            <a href="/admin/libraries/kontragents" class="btn">List</a>
            <a href="/admin/libraries/kontragent/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Units</td>
        <td>
            <a href="/admin/libraries/units" class="btn">List</a>
            <a href="/admin/libraries/unit/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
    <tr>
        <td>Currencies</td>
        <td>
            <a href="/admin/libraries/currencies" class="btn">List</a>
            <a href="/admin/libraries/currency/add" class="btn btn-primary">Add</a>
        </td>
    </tr>
</table>

