<h1>Библиотека</h1>
Страница в разработке!
<table class="table table-hover">
    <tr>
        <th>Библиотека</th>
        <th>Действия</th>
    </tr>
    <tr>
        <td>Регионы</td>
        <td><a href="#" class="btn">Список</a> <a href="#" class="btn btn-primary">Добавить</a></td>
    </tr>
    <tr>
        <td>Страны</td>
        <td><a href="#" class="btn">Список</a> <a href="#" class="btn btn-primary">Добавить</a></td>
    </tr>
    <tr>
        <td>Аэропорты</td>
        <td><a href="#" class="btn">Список</a> <a href="#" class="btn btn-primary">Добавить</a></td>
    </tr>
</table>

