<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Libraries</li>
</ul>
<h1>Libraries</h1>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 leftPanes">
            <?php echo $this->partial('fc-libraries-search/widgets/form/search/default.phtml', array('form' => $searchForm)); ?>
        </div>
        <div class="span10 rightPanes">
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

            <table class="table table-hover table-condensed">
                <tr>
                    <th>Name of library</th>
                    <th class="actions">Actions</th>
                </tr>
                <tr>
                    <td>Aircrafts</td>
                    <td class="actions">
                        <a href="/admin/libraries/aircrafts"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/aircraft/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Types Aircraft</td>
                    <td class="actions">
                        <a href="/admin/libraries/aircraft_types"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/aircraft_type/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td class="actions">Air Operators</td>
                    <td>
                        <a href="/admin/libraries/air_operators"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/air_operator/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Airports</td>
                    <td class="actions">
                        <a href="/admin/libraries/airports"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/airport/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Base of Permit</td>
                    <td class="actions">
                        <a href="/admin/libraries/base_of_permits"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/base_of_permit/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Cities</td>
                    <td class="actions">
                        <a href="/admin/libraries/cities"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/city/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Countries</td>
                    <td class="actions">
                        <a href="/admin/libraries/countries"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/country/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Currencies</td>
                    <td class="actions">
                        <a href="/admin/libraries/currencies"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/currency/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Kontragents</td>
                    <td class="actions">
                        <a href="/admin/libraries/kontragents"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/kontragent/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Regions</td>
                    <td class="actions">
                        <a href="/admin/libraries/regions"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/region/add"><i class="icon-plus"></i></a></td>
                </tr>
                <tr>
                    <td>Units</td>
                    <td class="actions">
                        <a href="/admin/libraries/units"><i class="icon-list"></i></a>
                        <a href="/admin/libraries/unit/add"><i class="icon-plus"></i></a>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>
