<h4>Airport</h4>
<?php
if (is_string($result)) {
    ?>
    <div class="alert alert-error">
        <?= $result; ?>
    </div>
<?php
} else {
    ?>
    <table class="table table-bordered table-hover table-striped table-condensed">
        <tr>
            <th>
                Name
            </th>
            <th>
                Short Name
            </th>
            <th>
                Code ICAO
            </th>
            <th>
                Code IATA
            </th>
            <th>
                City
            </th>
            <th>
                Country
            </th>
            <th>
                Region
            </th>
            <th>Actions</th>
        </tr>
        <?php foreach ($result as $row) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($row->name); ?></td>
                <td><?php echo $this->escapeHtml($row->short_name); ?></td>
                <td><?php echo $this->escapeHtml($row->code_icao); ?></td>
                <td><?php echo $this->escapeHtml($row->code_iata); ?></td>
                <td><?php echo $this->escapeHtml($row->city_name); ?></td>
                <td><?php echo $this->escapeHtml($row->country_name); ?></td>
                <td><?php echo $this->escapeHtml($row->region_name); ?></td>
                <td>
                    <a title="Edit" href="<?php echo $this->url('zfcadmin/airport',
                        array('action' => 'edit', 'id' => $row->id));?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?php echo $this->url('zfcadmin/airport',
                        array('action' => 'delete', 'id' => $row->id));?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php
}
?>
