<h4>Kontragent</h4>
<?php
if (is_string($result)) {
    ?>
    <div class="alert alert-error">
        <?= $result; ?>
    </div>
<?php
} else {
    ?>
    <table class="table table-bordered table-hover table-striped table-condensed">
        <tr>
            <th>ID number</th>
            <th>
                Name of Kontragent
            </th>
            <th>
                Short name of Kontragent
            </th>
            <th>
                Address
            </th>
            <th>
                Phones
            </th>
            <th>
                Fax
            </th>
            <th>
                E-mail
            </th>
            <th>
                Agreement
            </th>
            <th class="actions">Actions</th>
        </tr>
        <?php foreach ($result as $row) : ?>
            <tr>
                <td>
                    <?php
                    $showId = 0;
                    if ($row->id <= 9) {
                        $showId = '00' . $row->id;
                    } elseif (10 <= $row->id or $row->id <= 99) {
                        $showId = '0' . $row->id;
                    }
                    echo $this->escapeHtml($showId);
                    ?>
                </td>
                <td><?php echo $this->escapeHtml($row->name); ?></td>
                <td><?php echo $this->escapeHtml($row->short_name); ?></td>
                <td><?php echo $this->escapeHtml($row->address); ?></td>
                <td>
                    <?php
                    $showPnones = $row->phone1;
                    if (!empty($row->phone1)) {
                        $showPnones .= ', ' . $row->phone1;
                    }
                    if (!empty($row->phone2)) {
                        $showPnones .= ', ' . $row->phone2;
                    }
                    echo $this->escapeHtml($showPnones);
                    ?>
                </td>
                <td><?php echo $this->escapeHtml($row->fax); ?></td>
                <td><?php echo $this->escapeHtml($row->mail); ?></td>
                <td><?php echo $this->escapeHtml($row->agreement); ?></td>
                <td class="actions">
                    <a title="Edit" href="<?php echo $this->url('zfcadmin/kontragent',
                        array('action' => 'edit', 'id' => $row->id));?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?php echo $this->url('zfcadmin/kontragent',
                        array('action' => 'delete', 'id' => $row->id));?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php
}
?>
