<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?=$this->url('zfcadmin/libraries', array('action' => 'index'));?>">Libraries</a> <span class="divider">/</span></li>
    <li><a href="<?=$this->url('zfcadmin/base_of_permits', array('action' => 'index'));?>">Base of Permits</a> <span class="divider">/</span></li>
    <li class="active">Remove form</li>
</ul>
<?php
$title = 'Add Base of Permit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure you want to delete
    <strong>'<?php echo $this->escapeHtml($data->airportName); ?>'</strong>?
</p>
<?php
$url = $this->url('zfcadmin/base_of_permit', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int)$data->id; ?>" />
    <input type="hidden" name="name" value="<?php echo $this->escapeHtml($data->airportName); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" />
    <input type="submit" name="del" value="No" class="btn btn-link" />
</div>
</form>
