<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?= $this->url('zfcadmin/libraries', array('action' => 'index')); ?>">Libraries</a> <span
            class="divider">/</span></li>
    <li class="active">Base of Permits</li>
</ul>
<?php
$title = 'Base of Permits';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 leftPanes">
            <?php echo $this->partial('fc-libraries-search/widgets/form/search/default.phtml', array('form' => $searchForm)); ?>
        </div>
        <div class="span10 rightPanes">

            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

            <p>
                <a href="<?php echo $this->url('zfcadmin/base_of_permit', array('action' => 'add')); ?>"
                   class="btn btn-primary">Add Base of Permits</a>
            </p>

            <table class="table table-bordered table-hover table-condensed">
                <tr>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'airportName', 'order' => $url_order)); ?>">
                            Airport
                            <?php if ($order_by == 'airportName'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'cityName', 'order' => $url_order)); ?>">
                            City
                            <?php if ($order_by == 'cityName'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'countryName', 'order' => $url_order)); ?>">
                            Country
                            <?php if ($order_by == 'countryName'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'termValidity', 'order' => $url_order)); ?>">
                            Term validity
                            <?php if ($order_by == 'termValidity'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'termToTake', 'order' => $url_order)); ?>">
                            Term to take
                            <?php if ($order_by == 'termToTake'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        Info to take
                    </th>
                    <th class="actions">Actions</th>
                </tr>
                <?php foreach ($pagination as $row) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($row->airportName); ?></td>
                        <td><?php echo $this->escapeHtml($row->cityName); ?></td>
                        <td><?php echo $this->escapeHtml($row->countryName); ?></td>
                        <td><?php echo $this->escapeHtml($row->termValidity); ?></td>
                        <td><?php echo $this->escapeHtml($row->termToTake); ?></td>
                        <td><?php echo $this->escapeHtml($row->infoToTake); ?></td>
                        <td class="actions">
                            <a title="Edit" href="<?php echo $this->url('zfcadmin/base_of_permit',
                                array('action' => 'edit', 'id' => $row->id));?>"><i class="icon-edit"></i></a>
                            <a title="Remove" href="<?php echo $this->url('zfcadmin/base_of_permit',
                                array('action' => 'delete', 'id' => $row->id));?>"><i class="icon-remove"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?php
            echo $this->paginationControl(
                $pagination, 'Sliding', 'libraries-pagination-slide', array(
                'order_by' => $order_by,
                'order' => $order,
                'route' => $route,
            ));
            ?>
        </div>
    </div>
</div>
