<?php
$title = 'Countries';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'region_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('zfcadmin/country', array('action' => 'add'));?>"
       class="btn btn-primary">Add country</a>
</p>

<table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'name', 'order' => $url_order)); ?>">
                Name
                <?php if ($order_by == 'name'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'region_name', 'order' => $url_order)); ?>">
                Region
                <?php if ($order_by == 'region_name'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'code', 'order' => $url_order)); ?>">
                Code
                <?php if ($order_by == 'code'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>Actions</th>
    </tr>
    <?php foreach ($pagination as $row) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($row->id);?></td>
        <td><?php echo $this->escapeHtml($row->name);?></td>
        <td><?php echo $this->escapeHtml($row->region_name);?></td>
        <td><?php echo $this->escapeHtml($row->code);?></td>
        <td>
            <a href="<?php echo $this->url('zfcadmin/country',
                array('action' => 'edit', 'id' => $row->id));?>" class="btn btn-success">Edit</a>
            <a href="<?php echo $this->url('zfcadmin/country',
                array('action' => 'delete', 'id' => $row->id));?>" class="btn btn-warning">Remove</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
    $pagination, 'Sliding', 'libraries-pagination-slide', array(
        'order_by' => $order_by,
        'order' => $order,
        'route' => $route,
    )
);
?>
