<div id="leg">
    <table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead class="header">
        <tr>
            <th rowspan="2">
                Flight #
            </th>
            <th colspan="3">
                Ap Dep
            </th>
            <th colspan="3">
                Ap Arr
            </th>
            <th rowspan="2" class="actions">Actions</th>
        </tr>
        <tr>
            <th>
                ICAO
            </th>
            <th>
                IATA
            </th>
            <th>
                Date, UTC
            </th>
            <th>
                ICAO
            </th>
            <th>
                IATA
            </th>
            <th>
                Date, UTC
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        $lastLeg = end($this->legs);
        $lastLeg = $lastLeg['id'];
        ?>

        <?php foreach ($this->legs as $row) : ?>
<!--            --><?// \Zend\Debug\Debug::dump($row) ?>
            <tr data-legId="<?= $row['id'] ?>" class="<? if ($row['id'] == $this->currentId): ?><?= 'info' ?><? endif ?>">
                <td><?= $this->escapeHtml($row['flightNumber']) ?></td>
                <td><strong><?= $this->escapeHtml($row['apDepIcao']) ?></strong></td>
                <td><?= $this->escapeHtml($row['apDepIata']) ?></td>
                <td class="apDepTime"><?= $this->escapeHtml($row['apDepTime']) ?></td>
                <td><strong><?= $this->escapeHtml($row['apArrIcao']) ?></strong</td>
                <td><?= $this->escapeHtml($row['apArrIata']) ?></td>
                <td class="apArrTime"><?= $this->escapeHtml($row['apArrTime']) ?></td>
                <td class="actions">
                    <a title="Edit" href="<?= $this->url('leg',
                        array('action' => 'edit', 'id' => $row['id'])) ?>"
                       class="<?= ($this->header->status) ? '' : 'disabled' ?>"><i class="icon-edit"></i></a>
                    <? if ($row['id'] == $lastLeg): ?>
                        <a title="Remove" href="<?= $this->url('leg',
                            array('action' => 'delete', 'id' => $row['id'])) ?>"
                           class="<?= ($this->header->status) ? '' : 'disabled' ?>"><i class="icon-remove"></i></a>
                    <? endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>