<div id="permission">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead class="header">
        <tr>
            <th></th>
            <th>
                Agent
            </th>
            <th>
                Country
            </th>
            <th>
                Type of permission
            </th>
            <th>Time of request</th>
            <th>
                Permission
            </th>
            <th>
                Comment
            </th>
            <th class="actions">Actions</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->permissions as $legId => $legData): ?>
            <tr class="success">
                <td colspan="8">
                    <strong data-leg="<?= $legId ?>"><?= $this->escapeHtml($legData['legName']) ?></strong>
                </td>
            </tr>
            <? foreach ($legData['permission'] as $permissionId => $permissionData): ?>
                <tr class="<? if ($permissionId == $this->currentId): ?><?= 'info' ?><? endif ?>">
                    <td class="status"><? if ($permissionData['status']): ?><i class="icon-ok"></i><? endif ?></td>
                    <td><?= $this->escapeHtml($permissionData['agentName']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['countryName']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['typeOfPermission']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['requestTime']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['permission']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['comment']) ?></td>
                    <td class="actions">
                        <a title="Edit"
                           href="<?= $this->url('permission', array('action' => 'edit', 'id' => $permissionId)) ?>"
                           class="<? if (!$this->status): ?>disabled<? endif ?>"><i class="icon-edit"></i></a>
                        <a title="Remove"
                           href="<?= $this->url('permission', array('action' => 'delete', 'id' => $permissionId)) ?>"
                           class="<? if (!$this->status): ?>disabled<? endif ?>"><i class="icon-remove"></i></a>
                    </td>
                </tr>
            <? endforeach ?>
        <? endforeach ?>
        </tbody>
    </table>
</div>
