<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FcAdmin\Module'                     => __DIR__ . '/Module.php',
    'FcAdmin\Controller\IndexController' => __DIR__ . '/src/FcAdmin/Controller/IndexController.php',
    'FcAdmin\Controller\UserController'  => __DIR__ . '/src/FcAdmin/Controller/UserController.php',
    'FcAdmin\Form\UserForm'              => __DIR__ . '/src/FcAdmin/Form/UserForm.php',
    'FcAdmin\Model\Role'                 => __DIR__ . '/src/FcAdmin/Model/Role.php',
    'FcAdmin\Model\RoleTable'            => __DIR__ . '/src/FcAdmin/Model/RoleTable.php',
    'FcAdmin\Model\User'                 => __DIR__ . '/src/FcAdmin/Model/User.php',
    'FcAdmin\Model\UserTable'            => __DIR__ . '/src/FcAdmin/Model/UserTable.php',
);
