<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Permission form</li>
</ul>
<!--<div class="alert alert-info">-->
<!--    <strong>Warning!</strong> Page in development.-->
<!--</div>-->
<?php
$title = 'Add Permission';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<div id="permission">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('permission', array('action' => 'add', 'id' => $this->headerId)));
    $formLabel = $this->plugin('formLabel');
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('agentId')) . PHP_EOL;
    echo $this->formHidden($form->get('legId')) . PHP_EOL;
    echo $this->formHidden($form->get('countryId')) . PHP_EOL;
    echo $this->formHidden($form->get('typeOfPermission')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>
    <table class="table table-bordered table-hover table-condensed">
        <tr>
            <th>
                Agent
            </th>
            <th>
                Country
            </th>
            <th>
                Type of permission
            </th>
            <th>
                Permission
            </th>
            <th class="actions">Actions</th>
        </tr>
        <? foreach ($permissions as $legId => $legData): ?>
            <tr class="success">
                <td colspan="5">
                    <strong data-leg="<?= $legId ?>"><?= $this->escapeHtml($legData['legName']) ?></strong>
                </td>
            </tr>
            <? foreach ($legData['permission'] as $permissionId => $permissionData): ?>
                <tr>
                    <td><?= $this->escapeHtml($permissionData['agentName']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['countryName']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['typeOfPermission']) ?></td>
                    <td><?= $this->escapeHtml($permissionData['permission']) ?></td>
                    <td class="actions">
                        <a title="Edit"
                           href="<?= $this->url('permission', array('action' => 'edit', 'id' => $permissionId)) ?>"
                           class="<? if (!$headerStatus): ?>disabled<? endif ?>"><i class="icon-edit"></i></a>
                        <a title="Remove"
                           href="<?= $this->url('permission', array('action' => 'delete', 'id' => $permissionId)) ?>"
                           class="<? if (!$headerStatus): ?>disabled<? endif ?>"><i class="icon-remove"></i></a>
                    </td>
                </tr>
            <? endforeach ?>
        <? endforeach ?>
    </table>
    <table class="table ">
        <tr>
            <td>
                <?php
                $field = $form->get('agentsList');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('legsList');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('countriesList');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('typeOfPermissionsList');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('permission');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
