<?php
$title = 'Add Permission';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Type of service: Permission</li>
</ul>

<?=
$this->partial('widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
    )
)
?>

<h1><?= $title ?></h1>

<?php if ($this->form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?= $this->flashMessenger()->render('success', array('alert', 'alert-success')) ?>
<?php endif ?>

<div id="permission">
    <?=
    $this->partial('widgets/tables/permission.phtml',
        array(
            'permissions' => $this->permissions,
            'status' => $this->header->status,
            'fixedHeader' => true,
        )) ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('permission', array('action' => 'add', 'id' => $this->header->id)));
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>

    <table class="table ">
        <thead>
        <tr>
            <th>LEG</th>
            <th>Country</th>
            <th>Type of permission</th>
            <th>Time of request</th>
            <th>Agent</th>
            <th>Permission</th>
            <th>Comment</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                $field = $form->get('legId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('countryId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('typeOfPermission');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('requestTime');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('agentId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('permission');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('comment');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
