<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Permission form</li>
</ul>
<?php
$title = 'Add Permission';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<div id="permission">
    <?php echo $this->partial('widgets/tables/permission.phtml', array('permissions' => $permissions, 'status' => $headerStatus)); ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('permission', array('action' => 'add', 'id' => $this->headerId)));
    $formLabel = $this->plugin('formLabel');
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>

    <table class="table ">
        <tr>
            <td>
                <?php
                $field = $form->get('agentId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('legId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('countryId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('typeOfPermission');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('permission');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
