<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Permission form</li>
</ul>
<?php
$title = 'Edit Permission';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'airportId' => array(
            'required' => true,
        ),
        'isNeed' => array(
            'required' => false,
        ),
        'typeOfPermit' => array(
            'required' => true,
        ),
        'baseOfPermitId' => array(
            'required' => true,
        ),
        'check' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$form->setAttribute('action', $this->url('permission', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>

<?php echo $this->partial('widgets/tables/permission.phtml', array('permissions' => $permissions)); ?>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>

