<div id="apService">
    <table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead class="header">
        <tr>
            <th>
                Airport
            </th>
            <th>
                Type of AP service
            </th>
            <th>
                Agent
            </th>
            <th>
                Price USD
            </th>
            <th class="actions">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($apServices as $row) : ?>
            <tr class="<? if ($row['id'] == $currentId): ?><?= 'info' ?><? endif ?>">
                <td>
                    <a rel="tooltip" href="#" data-toggle="tooltip" data-placement="top"
                       title="" data-original-title="<?= $this->escapeHtml($row['airportName']) ?>">
                        <?= $this->escapeHtml($row['icao']) ?> |
                        <?= $this->escapeHtml($row['iata']) ?>
                    </a>
                </td>
                <td><?= $this->escapeHtml($row['typeOfApServiceName']) ?></td>
                <td><?= $this->escapeHtml($row['kontragentShortName']) ?></td>
                <td><?= $this->escapeHtml($row['priceUSD']) ?></td>
                <td class="actions">
                    <a title="Edit" href="<?= $this->url('apService',
                        array('action' => 'edit', 'id' => $row['id'])) ?>" class="<?= ($status) ? '': 'disabled' ?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?= $this->url('apService',
                        array('action' => 'delete', 'id' => $row['id'])) ?>" class="<?= ($status) ? '': 'disabled' ?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>