<div id="handing">
    <table class="table table-bordered table-hover table-condensed">
        <tr>
            <th>
                Airport
            </th>
            <th>
                Need?
            </th>
            <th>
                Agent
            </th>
            <th class="actions">Actions</th>
        </tr>
        <?php foreach ($handing as $row) : ?>
            <tr>
                <td>
                    <a rel="tooltip" href="#" data-toggle="tooltip" data-placement="top"
                       title="" data-original-title="<?php echo $this->escapeHtml($row['airportName']); ?>">
                        <?php echo $this->escapeHtml($row['icao']); ?> |
                        <?php echo $this->escapeHtml($row['iata']); ?>
                    </a>
                </td>
                <td><?=($row['isNeed']) ? 'YES' : 'NO'; ?></td>
                <td><?php echo $this->escapeHtml($row['kontragentShortName']); ?></td>
                <td class="actions">
                    <a title="Edit" href="<?php echo $this->url('handing',
                        array('action' => 'edit', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?php echo $this->url('handing',
                        array('action' => 'delete', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>