<table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead class="header">
    <tr>
        <th>
            Ref Number
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'dateOrder', 'order' => $url_order)); ?>">
                Date Order
                <?php if ($order_by == 'dateOrder'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'kontragentShortName', 'order' => $url_order)); ?>">
                Customer
                <?php if ($order_by == 'kontragentShortName'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'airOperatorShortName', 'order' => $url_order)); ?>">
                Air Operator
                <?php if ($order_by == 'airOperatorShortName'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'aircraftType', 'order' => $url_order)); ?>">
                Aircraft
                <?php if ($order_by == 'aircraftType'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>Refuel</th>
        <th>Permit</th>
        <th class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data as $row) : ?>
        <tr class="<?= ($row['status']) ? 'warning' : 'success'; ?>">
            <td>
                <a href="<?php
                echo $this->url('browse',
                    array('refNumberOrder' => urlencode($row['refNumberOrder'])));?>">
                    <strong><?php echo $this->escapeHtml($row['refNumberOrder']); ?></strong>
                </a>
            </td>
            <td><strong><?php echo date('d-m-Y', $row['dateOrder']); ?></strong></td>
            <td><?php echo $this->escapeHtml($row['kontragentShortName']); ?></td>
            <td><?php echo $this->escapeHtml($row['airOperatorShortName']); ?></td>
            <td>
                <?php echo $this->escapeHtml($row['aircraftTypeName']); ?>
                <br/>
                <small><?php echo $this->escapeHtml($row['aircraft']); ?></small>
            </td>
            <td>
                <?php
                $class = '';
                switch ($row['refuelStatus']) {
                    case 'YES':
                        $class = 'statusYes';
                        break;
                    case 'NO':
                        $class = 'statusNo';
                        break;
                    case 'CNFMD':
                        $class = 'statusCNFMD';
                        break;
                    default:
                        $class = '';
                        break;
                }
                ?>
                <span class="<?= $class; ?>"><?= $row['refuelStatus']; ?></span>
            </td>
            <td>
                <?php
                $class = '';
                switch ($row['permitStatus']) {
                    case 'YES':
                        $class = 'statusYes';
                        break;
                    case 'NO':
                        $class = 'statusNo';
                        break;
                    case 'CNFMD':
                        $class = 'statusCNFMD';
                        break;
                    default:
                        $class = '';
                        break;
                }
                ?>
                <span class="<?= $class; ?>"><?= $row['permitStatus']; ?></span>
            </td>
            <td class="actions">
                <a title="Edit" href="<?php echo $this->url('flight',
                    array('action' => 'edit-header', 'id' => $row['id']));?>"><i class="icon-edit"></i></a>
                <a title="Remove" href="<?php echo $this->url('flight',
                    array('action' => 'delete-header', 'id' => $row['id']));?>"><i class="icon-remove"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
