<div id="leg">
    <table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead class="header">
        <tr>
            <th rowspan="2">
                Date of Flight
            </th>
            <th colspan="3">
                Flight Number
            </th>
            <th colspan="3">
                Ap Dep
            </th>
            <th colspan="3">
                Ap Arr
            </th>
            <th rowspan="2" class="actions">Actions</th>
        </tr>
        <tr>
            <th>
                ICAO
            </th>
            <th>
                IATA
            </th>
            <th></th>
            <th>
                ICAO
            </th>
            <th>
                IATA
            </th>
            <th>
                Time, UTC
            </th>
            <th>
                ICAO
            </th>
            <th>
                IATA
            </th>
            <th>
                Time, UTC
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        $lastLeg = end($legs);
        $lastLeg = $lastLeg['id'];
        ?>

        <?php foreach ($legs as $row) : ?>
            <tr class="<? if ($row['id'] == $currentId): ?><?= 'info' ?><? endif ?>">
                <td><strong><?php echo $this->escapeHtml($row['dateOfFlight']); ?></strong></td>
                <td><?php echo $this->escapeHtml($row['flightNumberIcao']); ?></td>
                <td><?php echo $this->escapeHtml($row['flightNumberIata']); ?></td>
                <td><?php echo $this->escapeHtml($row['flightNumberText']); ?></td>
                <td><?php echo $this->escapeHtml($row['apDepIcao']); ?></td>
                <td><?php echo $this->escapeHtml($row['apDepIata']); ?></td>
                <td><strong><?php echo $this->escapeHtml($row['apDepTime']); ?></strong></td>
                <td><?php echo $this->escapeHtml($row['apArrIcao']); ?></td>
                <td><?php echo $this->escapeHtml($row['apArrIata']); ?></td>
                <td><strong><?php echo $this->escapeHtml($row['apArrTime']); ?></strong></td>
                <td class="actions">
                    <? if ($row['id'] == $lastLeg): ?>
                        <a title="Edit" href="<?php echo $this->url('leg',
                            array('action' => 'edit', 'id' => $row['id']));?>"
                           class="<?= ($status) ? '' : 'disabled'; ?>"><i class="icon-edit"></i></a>
                        <a title="Remove" href="<?php echo $this->url('leg',
                            array('action' => 'delete', 'id' => $row['id']));?>"
                           class="<?= ($status) ? '' : 'disabled'; ?>"><i class="icon-remove"></i></a>
                    <? endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>