<legend>Type of Service: Permission</legend>
<div id="permission">
    <table class="table table-bordered table-hover table-condensed">
        <tr>
            <th colspan="3">

            </th>
            <th colspan="4">
                Info
            </th>
            <th colspan="2">

            </th>
        </tr>
        <tr>
            <th>
                Airport
            </th>
            <th>
                Need?
            </th>
            <th>
                Type
            </th>
            <th>
                City
            </th>
            <th>
                Country
            </th>
            <th>
                Term validity
            </th>
            <th>
                Term to take
            </th>
            <th>
                Check
            </th>
            <th class="actions">Actions</th>
        </tr>
        <?php foreach ($permissions as $row) : ?>
            <tr>
                <td>
                    <a rel="tooltip" href="#" data-toggle="tooltip" data-placement="top"
                       title="" data-original-title="<?php echo $this->escapeHtml($row['airportName']); ?>">
                        <?php echo $this->escapeHtml($row['icao']); ?> |
                        <?php echo $this->escapeHtml($row['iata']); ?>
                    </a>
                </td>
                <td><strong><?=($row['isNeed']) ? 'YES' : 'NO'; ?></strong></td>
                <td><?php echo $this->escapeHtml($row['typeOfPermit']); ?></td>
                <td><?php echo $this->escapeHtml($row['cityName']); ?></td>
                <td><?php echo $this->escapeHtml($row['countryName']); ?></td>
                <td><?php echo $this->escapeHtml($row['termValidity']); ?></td>
                <td><?php echo $this->escapeHtml($row['termToTake']); ?></td>
                <td><?php echo $this->escapeHtml($row['check']); ?></td>
                <td class="actions">
                    <a title="Edit" href="<?php echo $this->url('permission',
                        array('action' => 'edit', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?php echo $this->url('permission',
                        array('action' => 'delete', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>