<legend>Permission</legend>
<div id="permission">
    <table class="table table-bordered table-hover table-condensed">
        <tr>
            <th>
                Agent
            </th>
            <th>
                LEG
            </th>
            <th>
                Country
            </th>
            <th>
                Type of permission
            </th>
            <th>
                Permission
            </th>
            <th class="actions">Actions</th>
        </tr>
        <? foreach ($permissions as $row): ?>
            <tr>
                <td><?= $this->escapeHtml($row['agentName']) ?></td>
                <td>
                    <a rel="tooltip" href="#" data-toggle="tooltip" data-placement="top"
                       title="" data-original-title="<?= $this->escapeHtml($row['legDescription']) ?>">
                        <?= $this->escapeHtml($row['leg']) ?>
                    </a>
                </td>
                <td><?= $this->escapeHtml($row['countryName']) ?></td>
                <td><?= $this->escapeHtml($row['typeOfPermission']) ?></td>
                <td><?= $this->escapeHtml($row['permission']) ?></td>
                <td class="actions">
                    <a title="Edit"
                       href="<?= $this->url('permission', array('action' => 'edit', 'id' => $row['id'])) ?>"
                       class="<? if (!$status): ?>disabled<? endif ?>"><i class="icon-edit"></i></a>
                    <a title="Remove"
                       href="<?= $this->url('permission', array('action' => 'delete', 'id' => $row['id'])) ?>"
                       class="<? if (!$status): ?>disabled<? endif ?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <? endforeach ?>
    </table>
</div>