<div id="refuel">
    <table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?> refuelData">
        <thead class="header">
        <tr>
            <th>
                Date
            </th>
            <th>
                Agent
            </th>
            <th>
                Quantity LTR
            </th>
            <th>
                Quantity in Selected Units
            </th>
            <th>
                Unit
            </th>
            <th>
                Price USD
            </th>
            <th>
                Total USD
            </th>
            <th class="actions">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $refuelsTotal = 0;
        ?>
        <? foreach ($this->refuels as $legId => $legData): ?>
            <tr class="success">
                <td colspan="8">
                    <strong data-leg="<?= $legId ?>"><?= $this->escapeHtml($legData['legName']) ?></strong>
                </td>
            </tr>
            <? foreach ($legData['refuel'] as $refuelId => $refuelData): ?>
                <?php
                $refuelsTotal += (float)$refuelData['totalPriceUsd'];
                ?>
                <tr class="<? if ($refuelId == $this->currentId): ?><?= 'info' ?><? endif ?>">
                    <td><?= $this->escapeHtml($refuelData['date']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['agentName']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['quantityLtr']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['quantityOtherUnits']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['unitName']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['priceUsd']) ?></td>
                    <td><?= $this->escapeHtml($refuelData['totalPriceUsd']) ?></td>
                    <td class="actions">
                        <a title="Edit"
                        <a title="Edit" href="<?= $this->url('refuel',
                            array('action' => 'edit', 'id' => $refuelId)) ?>"
                           class="<? if (!$this->status): ?>disabled<? endif ?>"><i class="icon-edit"></i></a>
                        <a title="Remove"
                           href="<?= $this->url('refuel', array('action' => 'delete', 'id' => $refuelId)) ?>"
                           class="<? if (!$this->status): ?>disabled<? endif ?>"><i class="icon-remove"></i></a>
                    </td>
                </tr>
            <? endforeach ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="row-fluid">
        <div class="span6">
            <a class="btn disabled" href="#">Make INVOICE</a>
        </div>
        <div class="span6">
            <table style="width: 200px; float: right" class="table table-bordered .pull-right">
                <tr>
                    <td>
                        Subtotal
                    </td>
                    <td>USD</td>
                    <td><?= $refuelsTotal ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>