<div id="typeOfPermission">
    <table class="table table-bordered table-hover table-condensed">
        <tr>
            <th>
                Airport
            </th>
            <th>
                Slot Ap Dep
            </th>
            <th>
                Slot Ap Arr
            </th>
            <th>
                FPL
            </th>
            <th>
                PPL
            </th>
            <th class="actions">Actions</th>
        </tr>
        <?php foreach ($typeOfPermissions as $row) : ?>
            <tr>
                <td>
                    <a rel="tooltip" href="#" data-toggle="tooltip" data-placement="top"
                       title="" data-original-title="<?php echo $this->escapeHtml($row['airportName']); ?>">
                        <?php echo $this->escapeHtml($row['icao']); ?> |
                        <?php echo $this->escapeHtml($row['iata']); ?>
                    </a>
                </td>
                <td><?=($row['slotApDep']) ? 'YES' : 'NO'; ?></td>
                <td><?=($row['slotApArr']) ? 'YES' : 'NO'; ?></td>
                <td><?=($row['fpl']) ? 'YES' : 'NO'; ?></td>
                <td><?=($row['ppl']) ? 'YES' : 'NO'; ?></td>
                <td class="actions">
                    <a title="Edit" href="<?php echo $this->url('typeOfPermission',
                        array('action' => 'edit', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-edit"></i></a>
                    <a title="Remove" href="<?php echo $this->url('typeOfPermission',
                        array('action' => 'delete', 'id' => $row['id']));?>" class="<?=($status) ? '': 'disabled' ;?>"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>