<?php
$title = 'Kontragents';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

<p>
    <a href="<?php echo $this->url('zfcadmin/kontragent', array('action' => 'add'));?>"
       class="btn btn-primary">Add Kontragent</a>
</p>

<table class="table table-bordered table-hover">
    <tr>
        <th>ID number</th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'name', 'order' => $url_order)); ?>">
                Name of Kontragent
                <?php if ($order_by == 'name'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'short_name', 'order' => $url_order)); ?>">
                Short name of Kontragent
                <?php if ($order_by == 'short_name'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            Address
        </th>
        <th>
            Phones
        </th>
        <th>
            Fax
        </th>
        <th>
            E-mail
        </th>
        <th>Actions</th>
    </tr>
    <?php foreach ($pagination as $row) : ?>
    <tr>
        <td>
            <?php
            $showId = 0;
            if ($row->id <= 9) {
                $showId = '00' . $row->id;
            } elseif (10 <= $row->id or $row->id <= 99) {
                $showId = '0' . $row->id;
            }
            echo $this->escapeHtml($showId);
            ?>
        </td>
        <td><?php echo $this->escapeHtml($row->name);?></td>
        <td><?php echo $this->escapeHtml($row->short_name);?></td>
        <td><?php echo $this->escapeHtml($row->address);?></td>
        <td>
            <?php
            $showPnones = $row->phone1;
            if (!empty($row->phone1)) {
                $showPnones .= ', ' . $row->phone1;
            }
            if (!empty($row->phone2)) {
                $showPnones .= ', ' . $row->phone2;
            }
            echo $this->escapeHtml($showPnones);
            ?>
        </td>
        <td><?php echo $this->escapeHtml($row->fax);?></td>
        <td><?php echo $this->escapeHtml($row->mail);?></td>
        <td><?php echo $this->escapeHtml($row->sita);?></td>
        <td>
            <a href="<?php echo $this->url('zfcadmin/kontragent',
                array('action' => 'edit', 'id' => $row->id));?>" class="btn btn-success">Edit</a>
            <a href="<?php echo $this->url('zfcadmin/kontragent',
                array('action' => 'delete', 'id' => $row->id));?>" class="btn btn-warning">Remove</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
    $pagination, 'Sliding', 'libraries-pagination-slide', array(
        'order_by' => $order_by,
        'order' => $order,
        'route' => $route,
    )
);
?>
