<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?= $this->url('zfcadmin/libraries', array('action' => 'index')); ?>">Libraries</a> <span
            class="divider">/</span></li>
    <li class="active">Aircrafts</li>
</ul>
<?php
$title = 'Aircrafts';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

<p>
    <a href="<?php echo $this->url('zfcadmin/aircraft', array('action' => 'add')); ?>"
       class="btn btn-primary">Add Aircraft</a>
</p>

<table class="table table-bordered table-hover table-condensed">
    <tr>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'aircraft_type_name', 'order' => $url_order)); ?>">
                Type Aircraft
                <?php if ($order_by == 'aircraft_type_name'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'reg_number', 'order' => $url_order)); ?>">
                Reg Number
                <?php if ($order_by == 'reg_number'): ?>
                    <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>Actions</th>
    </tr>
    <?php foreach ($pagination as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->aircraft_type_name); ?></td>
            <td><?php echo $this->escapeHtml($row->reg_number); ?></td>
            <td>
                <a title="Edit" href="<?php echo $this->url('zfcadmin/aircraft',
                    array('action' => 'edit', 'id' => $row->id));?>"><i class="icon-edit"></i></a>
                <a title="Remove" href="<?php echo $this->url('zfcadmin/aircraft',
                    array('action' => 'delete', 'id' => $row->id));?>"><i class="icon-remove"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
    $pagination, 'Sliding', 'libraries-pagination-slide', array(
        'order_by' => $order_by,
        'order' => $order,
        'route' => $route,
    )
);
?>
