<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FcLogEvents\Controller\IndexController'  => __DIR__ . '/src/FcLogEvents/Controller/IndexController.php',
  'FcLogEvents\Controller\SearchController' => __DIR__ . '/src/FcLogEvents/Controller/SearchController.php',
  'FcLogEvents\Filter\FcLogEventsFilter'    => __DIR__ . '/src/FcLogEvents/Filter/FcLogEventsFilter.php',
  'FcLogEvents\Filter\SearchFilter'         => __DIR__ . '/src/FcLogEvents/Filter/SearchFilter.php',
  'FcLogEvents\Form\SearchForm'             => __DIR__ . '/src/FcLogEvents/Form/SearchForm.php',
  'FcLogEvents\Model\FcLogEventsModel'      => __DIR__ . '/src/FcLogEvents/Model/FcLogEventsModel.php',
  'FcLogEvents\Model\SearchModel'           => __DIR__ . '/src/FcLogEvents/Model/SearchModel.php',
  'FcLogEvents\Module'                      => __DIR__ . '/Module.php',
);
