<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Hotel form</li>
</ul>
<?php
$title = 'Edit Hotel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'airport' => array(
            'required' => true,
        ),
        'agent' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$form->setAttribute('action', $this->url('hotel', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>

<?php echo $this->partial('widgets/tables/hotel.phtml', array('hotels' => $hotels)); ?>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>

