<table class="table table-bordered table-hover table-condensed">
    <tr>
        <th>
            User
        </th>
        <th>
            IP
        </th>
        <th>
            Priority
        </th>
        <th>
            Time
        </th>
        <th>
            Message
        </th>
    </tr>
    <?php foreach ($data as $row) : ?>
        <?php
        switch ($row->priority) {
            case 4:
                $trClass = 'error';
                break;
            case 5:
                $trClass = 'warning';
                break;
            case 6:
                $trClass = 'info';
                break;
            default:
                $trClass = 'default';
        }
        $row->timestamp = \DateTime::createFromFormat('Y-m-d H:i:s', $row->timestamp)->getTimestamp();
        $row->timestamp = date('d-m-Y H:i:s', $row->timestamp);
        ?>
        <tr class="<?= $trClass; ?>">
            <td><?php echo $this->escapeHtml($row->username); ?></td>
            <td><?php echo $this->escapeHtml($row->ipaddress); ?></td>
            <td><?php echo $this->escapeHtml($row->priorityName); ?></td>
            <td><?php echo $this->escapeHtml($row->timestamp); ?></td>
            <td><?php echo $this->escapeHtml($row->message); ?></td>
        </tr>
    <?php endforeach; ?>
</table>