<table class="table table-bordered table-striped table-hover table-condensed">
    <tr>
        <th>
            User
        </th>
        <th>
            IP
        </th>
        <th>
            Priority
        </th>
        <th>
            Time
        </th>
        <th>
            Component
        </th>
    </tr>
    <?php foreach ($data as $row) : ?>
        <?php
        $row->timestamp = \DateTime::createFromFormat('Y-m-d H:i:s', $row->timestamp)->getTimestamp();
        $row->timestamp = date('d-m-Y H:i:s', $row->timestamp);
        ?>
        <tr>
            <td colspan="5">
                <p class="muted text-right">
                    <strong><?php echo $this->escapeHtml($row->username); ?></strong> |
                    <?php echo $this->escapeHtml($row->ipaddress); ?> |
                    <?php echo $this->escapeHtml($row->timestamp); ?> |
                    <strong><?php echo $this->escapeHtml($row->component); ?></strong> |
                    <span class="label"><?php echo $this->escapeHtml($row->priorityName); ?></span>
                </p>
                <?php echo $this->partial('fc-log-events/widgets/tables/logs/logData.phtml',
                    array('data' => $row->message, 'priority' => $row->priority)); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>