<? // \Zend\Debug\Debug::dump($this->typeOfServices) ?>
<? // \Zend\Debug\Debug::dump($this->data) ?>
<form name="apServiceOutcomeInvoiceStep3" id="apServiceOutcomeInvoiceStep3" method="post"
      action="/management/ap-service/outcome-invoice-step3">
<table id="invoiceMain" class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ORD #</th>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
        <th>Agent</th>
        <th>Type of service</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            <input type="hidden" name="incomeInvoiceId" value="<?= $this->data->incomeInvoiceMainId ?>"/>
            <input type="text" id="flightRefNumberOrder" name="flightRefNumberOrder" class="input-small"
                   placeholder="ORD #" readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->flightRefNumberOrder ?>"/>
        </td>
        <td rowspan="2">
            <input type="text" id="number" name="number" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value="<?= $this->newInvoiceNumber ?>"/>
        </td>
        <td rowspan="2">
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', $this->data->incomeInvoiceMainDate) ?>"/>
        </td>
        <td>
            <select id="currency" name="currency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == $this->data->incomeInvoiceMainCurrency): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required"
                   value="<?= $this->data->incomeInvoiceMainExchangeRate ?>"/>
        </td>
        <td rowspan="2">
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-info" value="Apply">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="agentName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->preInvoiceAgentShortName ?>">
        </td>
        <td>
            <select id="typeOfServiceId" name="typeOfServiceId" class="chosen input-small"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <? if ($this->data->incomeInvoiceMainTypeOfServiceId == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
    </tr>
    <tr class="info">
        <td>
            <?= $this->data->incomeInvoiceMainCurrency ?>
        </td>
        <td>
            <?= $this->data->incomeInvoiceMainExchangeRate ?>
        </td>
        <td>
            <?= $this->data->incomeInvoiceMainTypeOfServiceName ?>
        </td>
    </tr>
    </tbody>
    <thead>
    <tr>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Arr</th>
        <th>Airport Dep</th>
        <th>Date Arr</th>
        <th>Date Dep</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            <input type="text" class="input-small" name="customerName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->flightCustomerShortName ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airOperatorName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->flightAirOperatorShortName ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="flightNumber" maxlength="40" required="required"
                   value="<?= $this->data->incomeInvoiceFlightNumber ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="aircraftName" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->flightAircraftTypeName . ' (' . $this->data->flightAircraftName . ')' ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airportArr" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->legDepToNextAirportICAO . ' (' . $this->data->legDepToNextAirportIATA . ')' ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airportDep" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->preInvoiceAirportICAO . ' (' . $this->data->preInvoiceAirportIATA . ')' ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateArr" maxlength="40" required="required"
                   placeholder="Date"
                   value="<?= date('d-m-Y', $this->data->incomeInvoiceMainDateArr) ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateDep" maxlength="40" required="required"
                   placeholder="Date"
                   value="<?= date('d-m-Y', $this->data->incomeInvoiceMainDateDep) ?>">
        </td>
    </tr>
    <tr class="info">
        <td>
            <?= date('d-m-Y', $this->data->incomeInvoiceMainDateArr) ?>
        </td>
        <td>
            <?= date('d-m-Y', $this->data->incomeInvoiceMainDateDep) ?>
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
<thead>
<tr>
    <th colspan="7" class="text-center">Income invoice data</th>
</tr>
<tr>
    <th></th>
    <th>Description</th>
    <th>Price, <?= $this->data->incomeInvoiceMainCurrency ?></th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Total, <?= $this->data->incomeInvoiceMainCurrency ?></th>
    <th>Exchange Total, USD</th>
</tr>
</thead>
<tbody>
<? foreach ($this->incomeInvoiceData as $item): ?>
    <!--        --><? // \Zend\Debug\Debug::dump($item); ?>
    <tr class="info">
        <td>
        </td>
        <td>
            <?= $item->incomeInvoiceDataTypeOfServiceName ?>
        </td>
        <td>
            <?= $item->incomeInvoiceDataItemPrice ?>
        </td>
        <td>
            <?= $item->incomeInvoiceDataQuantity ?>
        </td>
        <td>
            <?= $item->incomeInvoiceDataUnitId ?>
        </td>
        <td>
            <?php
            $incomeInvoiceDataPriceSubTotal += $item->incomeInvoiceDataPriceTotal;
            ?>
            <?= number_format($item->incomeInvoiceDataPriceTotal, 4, '.', '') ?>
        </td>
        <td>
            <?php
            $incomeInvoiceDataSubPriceTotalExchangedToUsd += $item->incomeInvoiceDataPriceTotalExchangedToUsd;
            ?>
            <?= number_format($item->incomeInvoiceDataPriceTotalExchangedToUsd, 2, '.', '') ?>
        </td>
    </tr>
<? endforeach; ?>
<tr class="info">
    <td colspan="7">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td>
                            <?= $this->data->incomeInvoiceMainCurrency ?>
                            <?= number_format($incomeInvoiceDataPriceSubTotal, 4, '.', '') ?>
                        </td>
                        <td>
                            USD
                            <?= number_format($incomeInvoiceDataSubPriceTotalExchangedToUsd, 2, '.', '') ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>
</tbody>
<thead>
<tr>
    <th colspan="7" class="text-center">Outcome invoice data</th>
</tr>
<tr>
    <th></th>
    <th>Description</th>
    <th>
        Price, <span class="currency"><?= $this->data->incomeInvoiceMainCurrency ?></span>
    </th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>
        Total, <span class="currency"><?= $this->data->incomeInvoiceMainCurrency ?></span>
    </th>
    <th>Exchange Total, USD</th>
</tr>
</thead>
<tbody>

<? for ($i = 1; $i <= 15; $i++): ?>
    <tr class="dataRow <? if ($i > 1): ?><?= 'hidden' ?><? endif; ?>" data-rowid="<?= $i ?>">
        <td>
            <? if ($i > 1): ?>
                <a href="#" class="removeRow"><i class="icon-remove"></i></a>
            <? endif; ?>
        </td>
        <td>
            <select name="data[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <option value="<?= $key ?>"><?= $value ?></option>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small itemPrice" name="data[<?= $i ?>][itemPrice]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <input type="text" class="input-small quantity" name="data[<?= $i ?>][quantity]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <select name="data[<?= $i ?>][unitId]" class="chosen input-large unitId"
                    data-placeholder="Unit"
                    required="required">
                <option value=""></option>
                <? foreach ($this->units as $key => $value): ?>
                    <option value="<?= $key ?>"><?= $value ?></option>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small priceTotal" name="data[<?= $i ?>][priceTotal]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <input type="text" class="input-small priceTotalExchangedToUsd"
                   name="data[<?= $i ?>][priceTotalExchangedToUsd]"
                   maxlength="40"
                   required="required"
                   value="">
        </td>
    </tr>
<? endfor; ?>
<tr>
    <td colspan="7">
        <input name="addRow" type="submit" class="btn btn-info addRow" value="Add row">
    </td>
</tr>
<tr>
    <td colspan="7">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td>
                            <span class="currency"><?= $this->data->incomeInvoiceMainCurrency ?></span>
                            <span class="priceSubTotal"></span>
                        </td>
                        <td>
                            USD <span class="priceSubTotalExchangedToUsd"></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>
<tr>
    <td>
    </td>
    <td>
    </td>
    <td>
        <strong>Disbursement</strong><br/>
        <input type="text" class="input-small disbursement" name="subData[<?= $i ?>][disbursement]" maxlength="40"
               required="required"
               value=""> %
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
        <input type="text" class="input-small disbursementTotal" name="subData[<?= $i ?>][disbursementTotal]" maxlength="40"
               required="required"
               value="">
    </td>
    <td>
        <input type="text" class="input-small disbursementTotalExchangedToUsd"
               name="subData[<?= $i ?>][disbursementTotalExchangedToUsd]"
               maxlength="40"
               required="required"
               value="">
    </td>
</tr>
<? for ($i = 1; $i <= 15; $i++): ?>
    <tr class="subDataRow <? if ($i > 1): ?><?= 'hidden' ?><? endif; ?>" data-subrowid="<?= $i ?>">
        <td>
            <? if ($i > 1): ?>
                <a href="#" class="removeRow"><i class="icon-remove"></i></a>
            <? endif; ?>
        </td>
        <td>
            <select name="subData[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <option value="<?= $key ?>"><?= $value ?></option>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small itemPrice" name="subData[<?= $i ?>][itemPrice]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <input type="text" class="input-small quantity" name="subData[<?= $i ?>][quantity]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <select name="subData[<?= $i ?>][unitId]" class="chosen input-large unitId"
                    data-placeholder="Unit"
                    required="required">
                <option value=""></option>
                <? foreach ($this->units as $key => $value): ?>
                    <option value="<?= $key ?>"><?= $value ?></option>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small priceTotal" name="subData[<?= $i ?>][priceTotal]" maxlength="40"
                   required="required"
                   value="">
        </td>
        <td>
            <input type="text" class="input-small priceTotalExchangedToUsd"
                   name="subData[<?= $i ?>][priceTotalExchangedToUsd]"
                   maxlength="40"
                   required="required"
                   value="">
        </td>
    </tr>
<? endfor; ?>
<tr>
    <td colspan="7">
        <input name="addSubRow" type="submit" class="btn btn-info addSubRow" value="Add row">
    </td>
</tr>
<tr>
    <td colspan="7">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td>
                            <span class="currency"><?= $this->data->incomeInvoiceMainCurrency ?></span>
                            <span class="subPriceSubTotal"></span>
                        </td>
                        <td>
                            USD <span class="subPriceSubTotalExchangedToUsd"></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>


<tr>
    <td colspan="18">
        <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
    </td>
</tr>
</tbody>
</table>
</form>