<form name="apServiceIncomeInvoiceStep4" id="apServiceIncomeInvoiceStep4" method="post"
      action="/management/ap-service/income-invoice-add">
<table id="invoiceMain" class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ORD #</th>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Agent</th>
        <th colspan="2">Type of service</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="hidden" name="preInvoiceId" value="<?= $this->data->preInvoiceId ?>"/>
            <input type="text" id="flightRefNumberOrder" name="flightRefNumberOrder" class="input-small"
                   placeholder="ORD #" readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->flightRefNumberOrder ?>"/>
        </td>
        <td>
            <input type="text" id="number" name="number" class="input-small"
                   placeholder="Invoice #" readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->number ?>"/>
        </td>
        <td>
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date" readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->date ?>"/>
        </td>
        <td>
            <input type="text" id="currency" name="currency" class="input-small" placeholder="Currency"
                   readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->currency ?>"/>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small" readonly="readonly"
                   placeholder="Exchange Rate" maxlength="40" required="required"
                   value="<?= $this->data->exchangeRate ?>"/>
        </td>
        <td>
            <input type="text" class="input-small" name="agentName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->agentName ?>">
        </td>
        <td colspan="2">
            <select id="typeOfServiceId" name="typeOfServiceId" class="chosen input-large"
                    data-placeholder="Type of Service"
                    required="required">
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <? if ($this->data->typeOfServiceId == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option disabled value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
    </tr>
    </tbody>
    <thead>
    <tr>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Arr</th>
        <th>Airport Dep</th>
        <th>Date Arr</th>
        <th>Date Dep</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" class="input-small" name="customerName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->customerName ?>">
        </td>
        <td>
            <input type="text" class="input-small" name="airOperatorName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->airOperatorName ?>">
        </td>
        <td>
            <input type="text" class="input-small" name="flightNumber" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->flightNumber ?>">
        </td>
        <td>
            <select id="aircraftId" name="aircraftId" class="chosen input-medium"
                    data-placeholder="Aircraft"
                    required="required">
                <? foreach ($this->aircrafts as $key => $value): ?>
                    <? if ($key == $this->data->aircraftId): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small" name="airportArr" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->airportArr ?>">
        </td>
        <td>
            <input type="text" class="input-small" name="airportDep" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->airportDep ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateArr" maxlength="40" required="required"
                   readonly="readonly"
                   placeholder="Date"
                   value="<?= $this->data->dateArr ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateDep" maxlength="40" required="required"
                   readonly="readonly"
                   placeholder="Date"
                   value="<?= $this->data->dateDep ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>Description</th>
        <th>Price, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data->data as $i => $row): ?>
        <!--        --><? // \Zend\Debug\Debug::dump($row) ?>
        <tr class="dataRow">
            <td>
                <select name="data[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                        data-placeholder="Type of Service"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->typeOfServices as $key => $value): ?>
                        <? if ($row['typeOfServiceId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="input-small itemPrice" name="data[<?= $i ?>][itemPrice]" maxlength="40"
                       required="required"
                       value="<?= $row['itemPrice'] ?>">
            </td>
            <td>
                <input type="text" class="input-small quantity" name="data[<?= $i ?>][quantity]" maxlength="40"
                       required="required"
                       value="<?= $row['quantity'] ?>">
            </td>
            <td>
                <select name="data[<?= $i ?>][unitId]" class="chosen input-large unitId"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row['unitId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <?php
                $priceTotal += $row['priceTotal'];
                ?>
                <input type="text" class="input-small priceTotal" name="data[<?= $i ?>][priceTotal]" maxlength="40"
                       required="required"
                       value="<?= $row['priceTotal'] ?>">
            </td>
            <td>
                <?php
                $priceTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
                ?>
                <input type="text" class="input-small priceTotalExchangedToUsd"
                       name="data[<?= $i ?>][priceTotalExchangedToUsd]"
                       maxlength="40"
                       required="required"
                       value="<?= $row['priceTotalExchangedToUsd'] ?>">
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="6">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="currency"><?= $this->data->currency ?></span> <span
                                    class="priceSubTotal"><?= number_format($priceTotal, 2, '.', '') ?></span></td>
                            <td>USD <span
                                    class="priceSubTotalExchangedToUsd"><?= number_format($priceTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>