<form name="refuelOutcomeInvoiceStep4" id="refuelOutcomeInvoiceStep4" method="post"
      action="/management/refuel/outcome-invoice-add">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Customer</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="invoiceNumber" name="invoiceNumber" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data['invoiceNumber'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceDate" name="invoiceDate" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data['invoiceDate'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceCurrency" name="invoiceCurrency" class="input-small"
                   placeholder="Currency" maxlength="40" required="required" readonly="readonly"
                   value="<?= $this->data['invoiceCurrency'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceExchangeRate" name="invoiceExchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" readonly="readonly"
                   value="<?= $this->data['invoiceExchangeRate'] ?>"/>
        </td>
        <td>
            <input type="hidden" name="invoiceCustomerId" value="<?= $this->data['invoiceCustomerId'] ?>">
            <input type="text" class="input-small" name="invoiceCustomerName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data['invoiceCustomerName'] ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Fuel supplier</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date</th>
        <th>Quantity, LTR</th>
        <th>Quantity, Unit</th>
        <th>Unit</th>
        <th>Price</th>
        <th>TAX</th>
        <th>MOT</th>
        <th>VAT, %</th>
        <th>Deliver</th>
        <th>Total price</th>
        <th>Total</th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data['data'] as $row): ?>
        <!--        --><? // \Zend\Debug\Debug::dump($row) ?>
        <tr id="outcomeInvoiceRefuelId_<?= $row['incomeInvoiceRefuelId'] ?>">
            <td class="noWrap">
                <input type="hidden" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][incomeInvoiceRefuelId]"
                       value="<?= $row['incomeInvoiceRefuelId'] ?>"/>
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][preInvoiceFlightRefNumberOrder]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['preInvoiceFlightRefNumberOrder'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][supplierId]"
                       value="<?= $row['supplierId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][incomeInvoiceSupplierShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['incomeInvoiceSupplierShortName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][airOperatorId]"
                       value="<?= $row['airOperatorId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][incomeInvoiceAirOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['incomeInvoiceAirOperatorShortName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][airOperatorNumber]"
                       class="input-small"
                       maxlength="40" required="required"
                       value="<?= $row['airOperatorNumber'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][aircraftId]"
                       value="<?= $row['aircraftId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][incomeInvoiceAircraftName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['incomeInvoiceAircraftName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][airportDepId]"
                       value="<?= $row['airportDepId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][incomeInvoiceAirportDepName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['incomeInvoiceAirportDepName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][date]"
                       class="input-small date readonly"
                       placeholder="Date of refuel"
                       maxlength="40" required="required" value="<?= $row['date'] ?>">
            </td>
            <td>
                <input type="text" class="quantityLtr input-mini readonly"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][quantityLtr]"
                       placeholder="QTY LTR"
                       maxlength="40" required="required" value="<?= $row['quantityLtr'] ?>">
            </td>
            <td>
                <input type="text" class="quantityOtherUnits input-mini"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][quantityOtherUnits]"
                       placeholder="Quantity est"
                       maxlength="40" required="required" value="<?= $row['quantityOtherUnits'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['incomeInvoiceRefuelId'] ?>][unitId]"
                        class="unitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row['unitId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td class="noWrap">
                <input type="text" class="itemPrice input-mini text-right"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][itemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="<?= number_format($row['itemPrice'], 4, '.', '') ?>">
                <small>, <span class="refuelCurrency"><?= $this->data->invoiceCurrency ?></span></small>
            </td>
            <td>
                <input type="text" class="tax input-mini" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][tax]"
                       placeholder="TAX"
                       maxlength="40" required="required" value="<?= $row['tax'] ?>">
            </td>
            <td>
                <input type="text" class="mot input-mini" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][mot]"
                       placeholder="MOT"
                       maxlength="40" required="required" value="<?= $row['mot'] ?>">
            </td>
            <td>
                <input type="text" class="vat input-mini" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][vat]"
                       placeholder="VAT"
                       maxlength="40" required="required" value="<?= $row['vat'] ?>">
            </td>
            <td>
                <input type="text" class="deliver input-mini" name="data[<?= $row['incomeInvoiceRefuelId'] ?>][deliver]"
                       placeholder="Deliver"
                       maxlength="40" required="required" value="<?= $row['deliver'] ?>">
            </td>
            <td class="noWrap">
                <input type="text" class="price input-mini text-right"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][price]"
                       placeholder="Total price"
                       maxlength="40" required="required"
                       value="<?= $row['price'] ?>">
                <small>, <span class="refuelCurrency"><?= $this->data->invoiceCurrency ?></span></small>
            </td>
            <td class="noWrap">
                <?php
                $priceSubTotal += $row['priceTotal'];
                ?>
                <input type="text" class="priceTotal input-mini text-right"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][priceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="<?= $row['priceTotal'] ?>">
                <small>, <span class="refuelCurrency"><?= $this->data->invoiceCurrency ?></span></small>
            </td>
            <td>
                <?php
                $priceSubTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
                ?>
                <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                       name="data[<?= $row['incomeInvoiceRefuelId'] ?>][priceTotalExchangedToUsd]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="<?= $row['priceTotalExchangedToUsd'] ?>">
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="18">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="refuelCurrency"><?= $this->data->invoiceCurrency ?></span> <span
                                    class="priceSubTotal"><?= number_format($priceSubTotal, 2, '.', '') ?></span></td>
                            <td>USD <span
                                    class="priceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>