<?// \Zend\Debug\Debug::dump($this->incomeInvoiceData) ?>
<?// \Zend\Debug\Debug::dump($this->outcomeInvoiceData) ?>
<form name="apServiceOutcomeInvoiceStep2" id="apServiceOutcomeInvoiceStep2" method="post"
      action="/management/ap-service/outcome-invoice-step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport</th>
            <th>Date Arr</th>
            <th>Date Dep</th>
            <th>Agent</th>
            <th>Type of service</th>
            <th>Total</th>
            <th>Exchange Rate</th>
            <th>Exchange Total, USD</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
<!--            --><?// \Zend\Debug\Debug::dump($row) ?>
            <tr data-row="<?= $row->incomeInvoiceMainId ?>"
                class="<? if ($row->outcomeInvoiceMainId): ?>success<? endif ?>">
                <td rowspan="2">
                    <input type="checkbox" class="rowsSelected" name="rowsSelected[]"
                           value="<?= $row->incomeInvoiceMainId ?>">
                </td>
                <td rowspan="2" class="noWrap">
                    <a href="<?=
                    $this->url('browse',
                        array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                       target="_blank">
                        <?= $row->flightRefNumberOrder ?>
                    </a>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/ap-service/outcome-invoice-show',
                            array('id' => $row->outcomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->outcomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2" class="flightCustomer">
                    <?= $row->flightCustomerShortName ?>
                </td>
                <td rowspan="2">
                    <?= $row->flightAirOperatorShortName ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceFlightNumber): ?>
                        <?= $row->outcomeInvoiceFlightNumber ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2" class="noWrap">
                    <?= $row->flightAircraftTypeName . '<br /><small>(' . $row->flightAircraftName . ')</small>' ?>
                </td>
                <td rowspan="2">
                    <?= $row->preInvoiceAirportICAO . ' (' . $row->preInvoiceAirportIATA . ')' ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainDateArr): ?>
                        <?= date('d-m-Y', $row->outcomeInvoiceMainDateArr) ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainDateDep): ?>
                        <?= date('d-m-Y', $row->outcomeInvoiceMainDateDep) ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">
                    <?= $row->preInvoiceAgentShortName ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainTypeOfServiceName): ?>
                        <?= $row->outcomeInvoiceMainTypeOfServiceName ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($this->outcomeInvoiceData[$row->outcomeInvoiceMainId]['outcomeInvoiceDataPriceTotal']): ?>
                        <?= number_format($this->outcomeInvoiceData[$row->outcomeInvoiceMainId]['outcomeInvoiceDataPriceTotal'], 4, '.', '') ?><small>, <?= $row->outcomeInvoiceMainCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainExchangeRate): ?>
                        <?= $row->outcomeInvoiceMainExchangeRate ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($this->outcomeInvoiceData[$row->outcomeInvoiceMainId]['outcomeInvoiceDataPriceTotalExchangedToUsd']): ?>
                        <?= number_format($this->outcomeInvoiceData[$row->outcomeInvoiceMainId]['outcomeInvoiceDataPriceTotalExchangedToUsd'], 2, '.', '') ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
            </tr>
            <tr data-incomeInvoiceRefuelRow="<?= $row->incomeInvoiceRefuelId ?>" class="info">
                <td>
                    <? if ($row->incomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/ap-service/income-invoice-show',
                            array('id' => $row->incomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->incomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceFlightNumber ?>
                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceMainDateArr) ?>
                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceMainDateDep) ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceMainTypeOfServiceName ?>
                </td>
                <td class="text-right">
                    <?= number_format($this->incomeInvoiceData[$row->incomeInvoiceMainId]['incomeInvoiceDataPriceTotal'], 4, '.', '') ?><small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                </td>
                <td>
                    <?= $row->incomeInvoiceMainExchangeRate ?>
                </td>
                <td class="text-right">
                    <?= number_format($this->incomeInvoiceData[$row->incomeInvoiceMainId]['incomeInvoiceDataPriceTotalExchangedToUsd'], 2, '.', '') ?>
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="15">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>