<form name="apServiceIncomeInvoiceStep3" id="apServiceIncomeInvoiceStep3" method="post"
      action="/management/ap-service/income-invoice-step3">
<table id="invoiceMain" class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ORD #</th>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
        <th>Agent</th>
        <th>Type of service</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            <input type="hidden" name="preInvoiceId" value="<?= $this->data->preInvoiceId ?>"/>
            <input type="text" id="flightRefNumberOrder" name="flightRefNumberOrder" class="input-small"
                   placeholder="ORD #" readonly="readonly"
                   maxlength="40" required="required" value="<?= $this->data->flightRefNumberOrder ?>"/>
        </td>
        <td rowspan="2">
            <input type="text" id="number" name="number" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value=""/>
        </td>
        <td rowspan="2">
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', time()) ?>"/>
        </td>
        <td>
            <select id="currency" name="currency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == 'USD'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" value="1"/>
        </td>
        <td rowspan="2">
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-info" value="Apply">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="agentName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->preInvoiceAgentShortName ?>">
        </td>
        <td>
            <select id="typeOfServiceId" name="typeOfServiceId" class="chosen input-small"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <? if ($this->data->preInvoiceTypeOfApServiceId == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
    </tr>
    <tr class="info">
        <td>
            <?= $this->data->preInvoiceCurrency ?>
        </td>
        <td>
            <?= $this->data->preInvoiceExchangeRate ?>
        </td>
        <td>
            <?= $this->data->preInvoiceTypeOfServiceName ?>
        </td>
    </tr>
    </tbody>
    <thead>
    <tr>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Arr</th>
        <th>Airport Dep</th>
        <th>Date Arr</th>
        <th>Date Dep</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            <input type="text" class="input-small" name="customerName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->flightCustomerShortName ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airOperatorName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->flightAirOperatorShortName ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="flightNumber" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->legFlightNumberText ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="aircraftName" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->flightAircraftTypeName . ' (' . $this->data->flightAircraftName . ')' ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airportArr" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->legDepToNextAirportICAO . ' (' . $this->data->legDepToNextAirportIATA . ')' ?>">
        </td>
        <td rowspan="2">
            <input type="text" class="input-small" name="airportDep" maxlength="40" required="required"
                   readonly="readonly"
                   value="<?= $this->data->preInvoiceAirportICAO . ' (' . $this->data->preInvoiceAirportIATA . ')' ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateArr" maxlength="40" required="required"
                   placeholder="Date"
                   value="<?= date('d-m-Y', $this->data->legArrTime) ?>">
        </td>
        <td>
            <input type="text" class="input-small date" name="dateDep" maxlength="40" required="required"
                   placeholder="Date"
                   value="<?= date('d-m-Y', $this->data->legDepToNextAirportTime) ?>">
        </td>
    </tr>
    <tr class="info">
        <td>
            <?= date('d-m-Y', $this->data->legArrTime) ?>
        </td>
        <td>
            <?= date('d-m-Y', $this->data->legDepToNextAirportTime) ?>
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th></th>
        <th>Description</th>
        <th>Price, <span class="currency">USD</span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency">USD</span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <!--    --><? // \Zend\Debug\Debug::dump($this->data); ?>
    <tr class="info">
        <td>

        </td>
        <td>
        </td>
        <td>
            <?= $this->data->preInvoicePrice ?>
        </td>
        <td>
        </td>
        <td>
        </td>
        <td>
        </td>
        <td>
            <?= $this->data->preInvoicePriceTotalExchangedToUsd ?>
        </td>
    </tr>
    <? for ($i = 1; $i <= 15; $i++): ?>
        <tr class="dataRow <? if ($i > 1): ?><?= 'hidden' ?><? endif; ?>" data-rowid="<?= $i ?>">
            <td>
                <? if ($i > 1): ?>
                    <a href="#" class="removeRow"><i class="icon-remove"></i></a>
                <? endif; ?>
            </td>
            <td>
                <select name="data[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                        data-placeholder="Type of Service"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->typeOfServices as $key => $value): ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="input-small itemPrice" name="data[<?= $i ?>][itemPrice]" maxlength="40"
                       required="required"
                       value="">
            </td>
            <td>
                <input type="text" class="input-small quantity" name="data[<?= $i ?>][quantity]" maxlength="40"
                       required="required"
                       value="">
            </td>
            <td>
                <select name="data[<?= $i ?>][unitId]" class="chosen input-large unitId"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="input-small priceTotal" name="data[<?= $i ?>][priceTotal]" maxlength="40"
                       required="required"
                       value="">
            </td>
            <td>
                <input type="text" class="input-small priceTotalExchangedToUsd"
                       name="data[<?= $i ?>][priceTotalExchangedToUsd]"
                       maxlength="40"
                       required="required"
                       value="">
            </td>
        </tr>
    <? endfor; ?>
    <tr>
        <td colspan="7">
            <input name="addRow" type="submit" class="btn btn-info addRow" value="Add row">
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="currency">USD</span> <span class="priceSubTotal"></span></td>
                            <td>USD <span class="priceSubTotalExchangedToUsd"></span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>