<?php
//\Zend\Debug\Debug::dump($this->data);
// Проверяем, одинаков ли agent
//todo
//$fuelSupplierOld = '';
foreach ($this->data as $row) {
    $preInvoiceAgentId = $row->preInvoiceAgentId;
    $preInvoiceAgentShortName = $row->preInvoiceAgentShortName;
}
//
?>
<form name="permissionIncomeInvoiceStep3" id="permissionIncomeInvoiceStep3" method="post"
      action="/management/permission/income-invoice-step3">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
        <th>Agent</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="number" name="number" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value=""/>
        </td>
        <td>
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value=""/>
        </td>
        <td>
            <select id="currency" name="currency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == 'USD'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" value="1"/>
        </td>
        <td>
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-info" value="Apply">
        </td>
        <td>
            <input type="hidden" name="agentId" value="<?= $preInvoiceAgentId ?>">
            <input type="text" class="input-small" name="agentShortName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $preInvoiceAgentShortName ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency">USD</span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency">USD</span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data as $row): ?>
<!--        --><?// \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row->preInvoiceId ?>">
            <td class="noWrap" rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][preInvoiceId]" value="<?= $row->preInvoiceId ?>"/>
                <input type="text" name="data[<?= $row->preInvoiceId ?>][flightRefNumberOrder]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->flightRefNumberOrder ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][customerId]"
                       value="<?= $row->flightAgentId ?>">
                <input type="text" name="data[<?= $row->preInvoiceId ?>][customerShortName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->flightCustomerShortName ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][airOperatorId]"
                       value="<?= $row->flightAirOperatorId ?>">
                <input type="text" name="data[<?= $row->preInvoiceId ?>][airOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->flightAirOperatorShortName ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row->preInvoiceId ?>][flightNumber]"
                       class="input-small readonly"
                       maxlength="40" required="required"
                       value="<?= $row->legFlightNumberText ?>">
            </td>
            <td>
                <select id="aircraftId" name="aircraftId" class="chosen input-medium"
                        data-placeholder="Aircraft"
                        required="required">
                    <? foreach ($this->aircrafts as $key => $value): ?>
                        <? if ($key == $row->flightAircraftId): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][airportDepId]"
                       value="<?= $row->legAirportDepId ?>">
                <input type="text" name="data[<?= $row->preInvoiceId ?>][airportDepName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->preInvoiceAirportDepICAO . ' (' . $row->preInvoiceAirportDepIATA . ')' ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row->preInvoiceId ?>][dateDep]"
                       class="input-small date"
                       placeholder="Date"
                       maxlength="40" required="required" value="<?= date('d-m-Y', $row->legDepTime) ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][airportArrId]"
                       value="<?= $row->legAirportArrId ?>">
                <input type="text" name="data[<?= $row->preInvoiceId ?>][airportArrName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->preInvoiceAirportArrICAO . ' (' . $row->preInvoiceAirportArrIATA . ')' ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row->preInvoiceId ?>][dateArr]"
                       class="input-small date"
                       placeholder="Date"
                       maxlength="40" required="required" value="<?= date('d-m-Y', $row->legArrTime) ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->preInvoiceId ?>][countryId]"
                       value="<?= $row->preInvoiceCountryId ?>">
                <input type="text" name="data[<?= $row->preInvoiceId ?>][countryName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->preInvoiceCountryName ?>">
            </td>
            <td>
                <select name="data[<?= $row->preInvoiceId ?>][typeOfPermission]"
                        class="typeOfPermission chosen input-small"
                        data-placeholder="Type of permission"
                        required="required">
                    <? foreach ($this->typesOfPermission as $key => $value): ?>
                        <? if ($row->preInvoiceTypeOfPermission == $value): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td rowspan="2">
                <input type="text" class="itemPrice input-mini text-right"
                       name="data[<?= $row->preInvoiceId ?>][itemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td rowspan="2">
                <input type="text" class="quantity input-mini"
                       name="data[<?= $row->preInvoiceId ?>][quantity]"
                       placeholder="Quantity"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td rowspan="2">
                <select name="data[<?= $row->preInvoiceId ?>][unitId]"
                        class="unitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row->permissionUnitName == $value): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td rowspan="2">
                <input type="text" class="priceTotal input-mini text-right"
                       name="data[<?= $row->preInvoiceId ?>][priceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td rowspan="2">
                <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                       name="data[<?= $row->preInvoiceId ?>][priceTotalExchangedToUsd]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="">
            </td>
        </tr>
        <tr id="preInvoiceId_<?= $row->preInvoiceId ?>" class="info">
            <td>
                <?= $row->legFlightNumberText ?>
            </td>
            <td>
                <?= $row->flightAircraftTypeName . ' (' . $row->flightAircraftName . ')' ?>
            </td>
            <td>
                <?= date('d-m-Y', $row->legDepTime) ?>
            </td>
            <td>
                <?= date('d-m-Y', $row->legArrTime) ?>
            </td>
            <td>
                <?= $row->preInvoiceTypeOfPermission ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="16">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="currency">USD</span> <span class="priceSubTotal"></span></td>
                            <td>USD <span class="priceSubTotalExchangedToUsd"></span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="16">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>