<?php
//\Zend\Debug\Debug::dump($this->data);
?>
<form name="permissionOutcomeInvoiceStep4" id="permissionOutcomeInvoiceStep4" method="post"
      action="/management/permission/outcome-invoice-add">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Customer</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="number" name="number" class="input-small" placeholder="Invoice #" maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->number ?>"/>
        </td>
        <td>
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date" maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->date ?>"/>
        </td>
        <td>
            <input type="text" id="currency" name="currency" class="input-small" placeholder="Currency"
                   maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->currency ?>"/>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small" placeholder="Exchange Rate"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data->exchangeRate ?>"/>
        </td>
        <td>
            <input type="hidden" name="customerId" value="<?= $this->data->customerId ?>">
            <input type="text" class="input-small" name="customerShortName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->customerShortName ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Agent</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data->data as $row): ?>
        <!--    --><? // \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row['incomeInvoiceId'] ?>">
            <td class="noWrap">
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][incomeInvoiceId]"
                       value="<?= $row['incomeInvoiceId'] ?>"/>
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][flightRefNumberOrder]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightRefNumberOrder'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][agentId]"
                       value="<?= $row['agentId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][agentShortName]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['agentShortName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][airOperatorId]"
                       value="<?= $row['airOperatorId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][airOperatorShortName]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airOperatorShortName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][flightNumber]"
                       class="input-small readonly" maxlength="40" required="required"
                       value="<?= $row['flightNumber'] ?>">
            </td>
            <td>
                <select id="aircraftId" name="data[<?= $row['incomeInvoiceId'] ?>][aircraftId]"
                        class="chosen input-medium" data-placeholder="Aircraft" required="required">
                    <? foreach ($this->aircrafts as $key => $value): ?>
                        <? if ($key == $row['aircraftId']): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][airportDepId]"
                       value="<?= $row['airportDepId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][airportDepName]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airportDepName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][dateDep]" class="input-small date"
                       placeholder="Date" maxlength="40" required="required" value="<?= $row['dateDep'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][airportArrId]"
                       value="<?= $row['airportArrId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][airportArrName]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airportArrName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][dateArr]" class="input-small date"
                       placeholder="Date" maxlength="40" required="required" value="<?= $row['dateArr'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['incomeInvoiceId'] ?>][countryId]"
                       value="<?= $row['countryId'] ?>">
                <input type="text" name="data[<?= $row['incomeInvoiceId'] ?>][countryName]"
                       class="input-small readonly" maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['countryName'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['incomeInvoiceId'] ?>][typeOfPermission]"
                        class="typeOfPermission chosen input-small" data-placeholder="Type of permission"
                        required="required">
                    <? foreach ($this->typesOfPermission as $key => $value): ?>
                        <? if ($row['typeOfPermission'] == $value): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="itemPrice input-mini text-right"
                       name="data[<?= $row['incomeInvoiceId'] ?>][itemPrice]" placeholder="Price est" maxlength="40"
                       required="required" value="<?= $row['itemPrice'] ?>">
            </td>
            <td>
                <input type="text" class="quantity input-mini" name="data[<?= $row['incomeInvoiceId'] ?>][quantity]"
                       placeholder="Quantity" maxlength="40" required="required" value="<?= $row['quantity'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['incomeInvoiceId'] ?>][unitId]" class="unitId chosen input-small"
                        data-placeholder="Unit" required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row['unitId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <?php
                $priceSubTotal += $row['priceTotal'];
                ?>
                <input type="text" class="priceTotal input-mini text-right"
                       name="data[<?= $row['incomeInvoiceId'] ?>][priceTotal]" placeholder="Total" maxlength="40"
                       required="required" value="<?= $row['priceTotal'] ?>">
            </td>
            <td>
                <?php
                $priceSubTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
                ?>
                <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                       name="data[<?= $row['incomeInvoiceId'] ?>][priceTotalExchangedToUsd]"
                       placeholder="Exchange Total" maxlength="40" required="required"
                       value="<?= $row['priceTotalExchangedToUsd'] ?>">
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="16">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->data->currency ?></span>
                                <span class="priceSubTotal"><?= number_format($priceSubTotal, 2, '.', '') ?></span>
                            </td>
                            <td>USD
                            <span
                                class="priceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="16">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>