<?php
//\Zend\Debug\Debug::dump($this->data);
?>
<form name="permissionIncomeInvoiceStep4" id="permissionIncomeInvoiceStep4" method="post"
      action="/management/permission/income-invoice-add">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Agent</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="number" name="number" class="input-small" placeholder="Invoice #" maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->number ?>"/>
        </td>
        <td>
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date" maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->date ?>"/>
        </td>
        <td>
            <input type="text" id="currency" name="currency" class="input-small" placeholder="Currency" maxlength="40"
                   required="required" readonly="readonly" value="<?= $this->data->currency ?>"/>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small" placeholder="Exchange Rate"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data->exchangeRate ?>"/>
        </td>
        <td>
            <input type="hidden" name="agentId" value="<?= $this->data->agentId ?>">
            <input type="text" class="input-small" name="agentShortName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data->agentShortName ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->data->currency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data->data as $row): ?>
        <!--                --><? // \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row['preInvoiceId'] ?>">
            <td class="noWrap">
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][preInvoiceId]"
                       value="<?= $row['preInvoiceId'] ?>"/>
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][flightRefNumberOrder]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightRefNumberOrder'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][customerId]"
                       value="<?= $row['customerId'] ?>">
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][customerShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['customerShortName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][airOperatorId]"
                       value="<?= $row['airOperatorId'] ?>">
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][airOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airOperatorShortName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][flightNumber]"
                       class="input-small readonly"
                       maxlength="40" required="required"
                       value="<?= $row['flightNumber'] ?>">
            </td>
            <td>
                <select id="aircraftId" name="data[<?= $row['preInvoiceId'] ?>][aircraftId]" class="chosen input-medium"
                        data-placeholder="Aircraft"
                        required="required">
                    <? foreach ($this->aircrafts as $key => $value): ?>
                        <? if ($key == $row['aircraftId']): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][airportDepId]"
                       value="<?= $row['airportDepId'] ?>">
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][airportDepName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airportDepName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][dateDep]"
                       class="input-small date"
                       placeholder="Date"
                       maxlength="40" required="required" value="<?= $row['dateDep'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][airportArrId]"
                       value="<?= $row['airportArrId'] ?>">
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][airportArrName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['airportArrName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][dateArr]"
                       class="input-small date"
                       placeholder="Date"
                       maxlength="40" required="required" value="<?= $row['dateArr'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['preInvoiceId'] ?>][countryId]"
                       value="<?= $row['countryId'] ?>">
                <input type="text" name="data[<?= $row['preInvoiceId'] ?>][countryName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['countryName'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['preInvoiceId'] ?>][typeOfPermission]"
                        class="typeOfPermission chosen input-small"
                        data-placeholder="Type of permission"
                        required="required">
                    <? foreach ($this->typesOfPermission as $key => $value): ?>
                        <? if ($row['typeOfPermission'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="itemPrice input-mini text-right"
                       name="data[<?= $row['preInvoiceId'] ?>][itemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="<?= $row['itemPrice'] ?>">
            </td>
            <td>
                <input type="text" class="quantity input-mini"
                       name="data[<?= $row['preInvoiceId'] ?>][quantity]"
                       placeholder="Quantity"
                       maxlength="40" required="required"
                       value="<?= $row['quantity'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['preInvoiceId'] ?>][unitId]"
                        class="unitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row['unitId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <?php
                $priceTotal += $row['priceTotal'];
                ?>
                <input type="text" class="priceTotal input-mini text-right"
                       name="data[<?= $row['preInvoiceId'] ?>][priceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="<?= $row['priceTotal'] ?>">
            </td>
            <td>
                <?php
                $priceTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
                ?>
                <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                       name="data[<?= $row['preInvoiceId'] ?>][priceTotalExchangedToUsd]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="<?= $row['priceTotalExchangedToUsd'] ?>">
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="16">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->data->currency ?></span>
                                <span class="priceSubTotal"><?= $priceTotal ?></span>
                            </td>
                            <td>
                                USD <span class="priceSubTotalExchangedToUsd"><?= $priceTotalExchangedToUsd ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="16">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>