<?php
// Проверяем, одинаков ли fuel supplier
//todo
//$fuelSupplierOld = '';
foreach ($this->data as $row) {
    $permissionAgentId = $row->permissionAgentId;
    $permissionAgentName = $row->permissionAgentShortName;
}
//
?>
<form name="permissionIncomeInvoiceStep3" id="permissionIncomeInvoiceStep3" method="post"
      action="/management/permission/income-invoice-step3">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>ORD #</th>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
        <th>Agent</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="invoiceNumber" name="invoiceNumber" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value=""/>
        </td>
        <td>
            <input type="text" id="invoiceDate" name="invoiceDate" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value=""/>
        </td>
        <td>
            <select id="invoiceCurrency" name="invoiceCurrency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == 'USD'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="invoiceExchangeRate" name="invoiceExchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" value="1"/>
        </td>
        <td>
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-info" value="Apply">
        </td>
        <td>
            <input type="hidden" name="invoiceRefuelSupplierId" value="<?= $permissionSupplierId ?>">
            <input type="text" class="input-small" name="invoiceRefuelSupplierName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $permissionSupplierName ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date</th>
        <th>Quantity, LTR</th>
        <th>Quantity, Unit</th>
        <th>Unit</th>
        <th>Price, <span class="permissionCurrency">USD</span></th>
        <th>TAX</th>
        <th>MOT</th>
        <th>VAT, %</th>
        <th>Deliver</th>
        <th>Total price, <span class="permissionCurrency">USD</span></th>
        <th>Total, <span class="permissionCurrency">USD</span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data as $row): ?>
<!--        --><?// \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceRefuelId_<?= $row->permissionId ?>">
            <td class="noWrap" rowspan="2">
                <input type="hidden" name="data[<?= $row->permissionId ?>][permissionId]" value="<?= $row->permissionId ?>"/>
                <input type="text" name="data[<?= $row->permissionId ?>][flightRefNumberOrder]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->flightRefNumberOrder ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->permissionId ?>][flightAgentId]"
                       value="<?= $row->flightAgentId ?>">
                <input type="text" name="data[<?= $row->permissionId ?>][flightAgentShortName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->flightAgentShortName ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->permissionId ?>][flightAirOperatorId]"
                       value="<?= $row->flightAirOperator ?>">
                <input type="text" name="data[<?= $row->permissionId ?>][flightAirOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->flightAirOperatorShortName ?>">
            </td>
            <td rowspan="2">
                <input type="text" name="data[<?= $row->permissionId ?>][flightAirOperatorNumber]"
                       class="input-small readonly"
                       maxlength="40" required="required"
                       value="<?= $row->flightAirOperatorNumber ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->permissionId ?>][flightAircraftId]"
                       value="<?= $row->flightAircraftId ?>">
                <input type="text" name="data[<?= $row->permissionId ?>][flightAircraftName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->flightAircraftTypeName . ' (' . $row->flightAircraftName . ')' ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->permissionId ?>][permissionAirportId]"
                       value="<?= $row->permissionAirportId ?>">
                <input type="text" name="data[<?= $row->permissionId ?>][permissionAirportName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->permissionAirportICAO . ' (' . $row->permissionAirportIATA . ')' ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row->permissionId ?>][permissionDate]"
                       class="input-small date"
                       placeholder="Date of permission"
                       maxlength="40" required="required" value="<?= date('d-m-Y', $row->permissionDate) ?>">
            </td>
            <td>
                <input type="text" class="permissionQuantityLtr input-mini"
                       name="data[<?= $row->permissionId ?>][permissionQuantityLtr]"
                       placeholder="QTY LTR"
                       maxlength="40" required="required" value="<?= $row->permissionQuantityLtr ?>">
            </td>
            <td>
                <input type="text" class="permissionQuantityOtherUnits input-mini"
                       name="data[<?= $row->permissionId ?>][permissionQuantityOtherUnits]"
                       placeholder="Quantity est"
                       maxlength="40" required="required" value="<?= $row->permissionQuantityOtherUnits ?>">
            </td>
            <td>
                <select name="data[<?= $row->permissionId ?>][permissionUnitId]"
                        class="permissionUnitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row->permissionUnitName == $value): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="permissionItemPrice input-mini text-right"
                       name="data[<?= $row->permissionId ?>][permissionItemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="<?= number_format($row->permissionPriceUsd, 4, '.', '') ?>">
            </td>
            <td>
                <input type="text" class="permissionTax input-mini" name="data[<?= $row->permissionId ?>][permissionTax]"
                       placeholder="TAX"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="permissionMot input-mini" name="data[<?= $row->permissionId ?>][permissionMot]"
                       placeholder="MOT"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="permissionVat input-mini" name="data[<?= $row->permissionId ?>][permissionVat]"
                       placeholder="VAT"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="permissionDeliver input-mini" name="data[<?= $row->permissionId ?>][permissionDeliver]"
                       placeholder="Deliver"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="permissionPrice input-mini text-right"
                       name="data[<?= $row->permissionId ?>][permissionPrice]"
                       placeholder="Total price"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td>
                <input type="text" class="permissionPriceTotal input-mini text-right"
                       name="data[<?= $row->permissionId ?>][permissionPriceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td>
                <input type="text" class="permissionExchangeToUsdPriceTotal input-mini text-right"
                       name="data[<?= $row->permissionId ?>][permissionExchangeToUsdPriceTotal]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="">
            </td>
        </tr>
        <tr id="preInvoiceRefuelId_<?= $row->permissionId ?>" class="info">
            <td><?= date('d-m-Y', $row->permissionDate) ?></td>
            <td><?= $row->permissionQuantityLtr ?></td>
            <td><?= $row->permissionQuantityOtherUnits ?></td>
            <td><?= $row->permissionUnitName ?></td>
            <td class="text-right"><?= number_format($row->permissionPriceUsd, 4, '.', '') ?></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><?= number_format($row->permissionTotalPriceUsd / 100, 2, '.', '') ?></td>
            <td></td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="18">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="permissionCurrency">USD</span> <span class="permissionPriceSubTotal"></span></td>
                            <td>USD <span class="permissionExchangeToUsdPriceSubTotal"></span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>