<form name="permissionIncomeInvoiceStep2" id="permissionIncomeInvoiceStep2" method="post"
      action="/management/permission/income-invoice-step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport Dep</th>
            <th>Date Dep</th>
            <th>Airport Arr</th>
            <th>Date Arr</th>
            <th>Country</th>
            <th>Agent</th>
            <th>Type of permission</th>
            <th>Number of permission</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Total</th>
            <th>Exchange Total, USD</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
            <? \Zend\Debug\Debug::dump($row) ?>
            <tr data-dataRow="<?= $row->preInvoiceId ?>" class="<? if ($row->incomeInvoiceMainId): ?>success<? endif ?>">
                <td>
                    <input type="checkbox" class="rowsSelected" name="rowsSelected[]"
                           data-permissionId="<?= $row->preInvoiceId ?>" value="<?= $row->preInvoiceId ?>">
                </td>
                <td>
                    <a href="<?=
                    $this->url('browse',
                        array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                       target="_blank">
                        <?= $row->flightRefNumberOrder ?>
                    </a>
                </td>
                <td class="noWrap">
                    <? if ($row->incomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/ap-service/income-invoice-show',
                            array('id' => $row->incomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->incomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->flightCustomerShortName ?>
                </td>
                <td>
                    <?= $row->flightAirOperatorShortName ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceFlightNumber): ?>
                        <?= $row->incomeInvoiceFlightNumber ?>
                    <? else: ?>
                        <?= $row->legFlightNumberText ?>
                    <? endif; ?>
                </td>
                <td class="noWrap">
                    <?= $row->flightAircraftTypeName ?> (<?= $row->flightAircraftName ?>)
                </td>
                <td>
                    <?= $row->preInvoiceAirportICAO . ' (' . $row->preInvoiceAirportIATA . ')' ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceMainDateArr): ?>
                        <?= date('d-m-Y', $row->incomeInvoiceMainDateArr) ?>
                    <? else: ?>
                        <?= date('d-m-Y', $row->legArrTime) ?>
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceMainDateDep): ?>
                        <?= date('d-m-Y', $row->incomeInvoiceMainDateDep) ?>
                    <? else: ?>
                        <?= date('d-m-Y', $this->advancedDataWithOutIncomeInvoice[$row->legId]['legDepToNextAirportTime']) ?>
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceMainArrDate): ?>
                        <?= date('d-m-Y', $row->incomeInvoiceMainArrDate) ?>
                    <? else: ?>
                        <?= date('d-m-Y', $row->legDepDate) ?>
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->preInvoiceCountryName ?>
                </td>
                <td class="preInvoiceAgentShortName">
                    <?= $row->preInvoiceAgentShortName ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceTypeOfPermission): ?>
                        <?= $row->incomeInvoiceTypeOfPermission ?>
                    <? else: ?>
                        <?= $row->preInvoiceTypeOfPermission ?>
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceNumberOfPermission): ?>
                        <?= $row->incomeInvoiceNumberOfPermission ?>
                    <? else: ?>
                        <?= $row->preInvoiceNumberOfPermission ?>
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->incomeInvoiceItemPrice): ?>
                        <?= $row->incomeInvoiceItemPrice ?><small>, <?= $row->incomeInvoiceCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceQuantityOtherUnits): ?>
                        <?= $row->incomeInvoiceQuantityOtherUnits ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceUnitName): ?>
                        <?= $row->incomeInvoiceUnitName ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoicePriceTotal): ?>
                        <?= $row->incomeInvoicePriceTotal ?><small>, <?= $row->incomeInvoiceCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->incomeInvoiceExchangeToUsdPriceTotal): ?>
                        <?= $row->incomeInvoiceExchangeToUsdPriceTotal ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="20">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>