<form name="permissionIncomeInvoiceStep2" id="permissionIncomeInvoiceStep2" method="post"
      action="/management/permission/income-invoice-step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport Dep</th>
            <th>Date Dep</th>
            <th>Airport Arr</th>
            <th>Date Arr</th>
            <th>Country</th>
            <th>Agent</th>
            <th>Type of permission</th>
            <th>Number of permission</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Total</th>
            <th>Exchange Total, USD</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
<!--            --><?// \Zend\Debug\Debug::dump($row) ?>
            <tr data-row="<?= $row->preInvoiceId ?>" class="<? if ($row->incomeInvoiceMainId): ?>success<? endif ?>">
                <td>
                    <input type="checkbox" class="rowsSelected" name="rowsSelected[]"
                           data-rowId="<?= $row->preInvoiceId ?>" value="<?= $row->preInvoiceId ?>">
                </td>
                <td>
                    <a href="<?=
                    $this->url('browse',
                        array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                       target="_blank">
                        <?= $row->flightRefNumberOrder ?>
                    </a>
                </td>
                <td class="noWrap">
                    <? if ($row->incomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/permission/income-invoice-show',
                            array('id' => $row->incomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->incomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->flightCustomerShortName ?>
                </td>
                <td>
                    <?= $row->flightAirOperatorShortName ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataFlightNumber): ?>
                        <?= $row->incomeInvoiceDataFlightNumber ?>
                    <? else: ?>
                        <?= $row->legFlightNumberText ?>
                    <? endif; ?>
                </td>
                <td class="noWrap">
                    <? if ($row->incomeInvoiceDataName): ?>
                        <?= $row->incomeInvoiceDataAircraftTypeName ?> (<?= $row->incomeInvoiceDataName ?>)
                    <? else: ?>
                        <?= $row->flightAircraftTypeName ?> (<?= $row->flightAircraftName ?>)
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->preInvoiceAirportDepICAO . ' (' . $row->preInvoiceAirportDepICAO . ')' ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataDateDep): ?>
                        <?= date('d-m-Y', $row->incomeInvoiceDataDateDep) ?>
                    <? else: ?>
                        <?= date('d-m-Y', $row->legDepTime) ?>
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->preInvoiceAirportArrICAO . ' (' . $row->preInvoiceAirportArrICAO . ')' ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataDateArr): ?>
                        <?= date('d-m-Y', $row->incomeInvoiceDataDateArr) ?>
                    <? else: ?>
                        <?= date('d-m-Y', $row->legArrTime) ?>
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->preInvoiceCountryName ?>
                </td>
                <td class="preInvoiceAgentShortName">
                    <?= $row->preInvoiceAgentShortName ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataTypeOfPermission): ?>
                        <?= $row->incomeInvoiceDataTypeOfPermission ?>
                    <? else: ?>
                        <?= $row->preInvoiceTypeOfPermission ?>
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceNumberOfPermission): ?>
                        <?= $row->incomeInvoiceNumberOfPermission ?>
                    <? else: ?>
                        <?= $row->preInvoiceRequestTime ?>
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->incomeInvoiceDataItemPrice): ?>
                        <?= number_format($row->incomeInvoiceDataItemPrice, 2, '.', '') ?><small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataQuantity): ?>
                        <?= $row->incomeInvoiceDataQuantity ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataUnitName): ?>
                        <?= $row->incomeInvoiceDataUnitName ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->incomeInvoiceDataPriceTotal): ?>
                        <?= $row->incomeInvoiceDataPriceTotal ?><small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->incomeInvoiceDataPriceTotalExchangedToUsd): ?>
                        <?= $row->incomeInvoiceDataPriceTotalExchangedToUsd ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="20">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>