<?php
//\Zend\Debug\Debug::dump($this->data);
// Проверяем, одинаков ли agent
//todo
//$fuelSupplierOld = '';
foreach ($this->data as $row) {
    $preInvoiceCustomerId = $row->incomeInvoiceMainAgentId;
    $preInvoiceCustomerShortName = $row->incomeInvoiceMainAgentShortName;
    $preInvoiceCustomerAgreement = $row->incomeInvoiceMainAgentAgreement;
}
//
?>
<form name="permissionOutcomeInvoiceStep3" id="permissionOutcomeInvoiceStep3" method="post"
      action="/management/permission/outcome-invoice-step3">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Customer</th>
        <th>Customer Agreement</th>
        <th>Bank</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="number" name="number" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value="<?= $this->newInvoiceNumber ?>"/>
        </td>
        <td>
            <input type="text" id="date" name="date" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', time()) ?>"/>
        </td>
        <td>
            <input type="hidden" name="customerId" value="<?= $preInvoiceCustomerId ?>">
            <input type="text" class="input-small" name="customerShortName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $preInvoiceCustomerShortName ?>">
        </td>
        <td>
            <input type="text" class="input-small" name="customerAgreement" maxlength="40" required="required"
                   readonly="readonly" value="<?= $preInvoiceCustomerAgreement ?>">
        </td>
        <td>
            <select id="bankId" name="bankId" class="chosen input-large"
                    data-placeholder="Bank"
                    required="required">
                <option value=""></option>
                <? foreach ($this->banks as $key => $value): ?>
                    <? if ($key == '1'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <select id="currency" name="currency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == 'USD'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="exchangeRate" name="exchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" value="1"/>
        </td>
        <td>
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-info" value="Apply">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
<thead>
<tr>
    <th>ORD</th>
    <th>Agent</th>
    <th>Air Operator</th>
    <th>Flight #</th>
    <th>Aircraft</th>
    <th>Airport Dep</th>
    <th>Date Dep</th>
    <th>Airport Arr</th>
    <th>Date Arr</th>
    <th>Country</th>
    <th>Permission number</th>
    <th>Price, <span class="currency">USD</span></th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Total, <span class="currency">USD</span></th>
    <th>Exchange Total, USD</th>
</tr>
</thead>
<tbody>
<? foreach ($this->data as $item => $row): ?>
    <!--                --><? // \Zend\Debug\Debug::dump($row) ?>
    <tr id="invoice_<?= $item ?>">
        <td class="noWrap" rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][incomeInvoiceId]"
                   value="<?= $row->incomeInvoiceDataId ?>"/>
            <input type="text" name="data[<?= $item ?>][flightRefNumberOrder]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly" value="<?= $row->flightRefNumberOrder ?>">
        </td>
        <td rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][agentId]"
                   value="<?= $row->flightAgentId ?>">
            <input type="text" name="data[<?= $item ?>][agentShortName]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly"
                   value="<?= $row->flightCustomerShortName ?>">
        </td>
        <td rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][airOperatorId]"
                   value="<?= $row->flightAirOperatorId ?>">
            <input type="text" name="data[<?= $item ?>][airOperatorShortName]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly"
                   value="<?= $row->flightAirOperatorShortName ?>">
        </td>
        <td>
            <input type="text" name="data[<?= $item ?>][flightNumber]"
                   class="input-small readonly"
                   maxlength="40" required="required"
                   value="">
        </td>
        <td>
            <select id="aircraftId" name="data[<?= $item ?>][aircraftId]"
                    class="chosen input-medium"
                    data-placeholder="Aircraft"
                    required="required">
                <? foreach ($this->aircrafts as $key => $value): ?>
                    <? if ($key == $row->flightAircraftId): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][airportDepId]"
                   value="<?= $row->legAirportDepId ?>">
            <input type="text" name="data[<?= $item ?>][airportDepName]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly"
                   value="<?= $row->legAirportDepICAO . ' (' . $row->legAirportDepIATA . ')' ?>">
        </td>
        <td>
            <input type="text" name="data[<?= $item ?>][dateDep]"
                   class="input-small date"
                   placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', $row->incomeInvoiceDataDateDep) ?>">
        </td>
        <td rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][airportArrId]"
                   value="<?= $row->legAirportArrId ?>">
            <input type="text" name="data[<?= $item ?>][airportArrName]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly"
                   value="<?= $row->legAirportArrICAO . ' (' . $row->legAirportArrIATA . ')' ?>">
        </td>
        <td>
            <input type="text" name="data[<?= $item ?>][dateArr]"
                   class="input-small date"
                   placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', $row->incomeInvoiceDataDateArr) ?>">
        </td>
        <td rowspan="2">
            <input type="hidden" name="data[<?= $item ?>][countryId]"
                   value="<?= $row->preInvoiceCountryId ?>">
            <input type="text" name="data[<?= $item ?>][countryName]"
                   class="input-small readonly"
                   maxlength="40" required="required" readonly="readonly"
                   value="<?= $row->preInvoiceCountryName ?>">
        </td>
        <td>
            <select name="data[<?= $item ?>][typeOfPermission]"
                    class="typeOfPermission chosen input-small"
                    data-placeholder="Type of permission"
                    required="required">
                <? foreach ($this->typesOfPermission as $key => $value): ?>
                    <? if ($row->incomeInvoiceDataTypeOfPermission == $value): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td rowspan="2">
            <input type="text" class="itemPrice input-mini text-right"
                   name="data[<?= $item ?>][itemPrice]"
                   placeholder="Price est"
                   maxlength="40" required="required"
                   value="">
        </td>
        <td rowspan="2">
            <input type="text" class="quantity input-mini"
                   name="data[<?= $item ?>][quantity]"
                   placeholder="Quantity"
                   maxlength="40" required="required"
                   value="">
        </td>
        <td rowspan="2">
            <select name="data[<?= $item ?>][unitId]"
                    class="unitId chosen input-small"
                    data-placeholder="Unit"
                    required="required">
                <option value=""></option>
                <? foreach ($this->units as $key => $value): ?>
                    <? if ($row->permissionUnitName == $value): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td rowspan="2">
            <input type="text" class="priceTotal input-mini text-right"
                   name="data[<?= $item ?>][priceTotal]"
                   placeholder="Total"
                   maxlength="40" required="required"
                   value="">
        </td>
        <td rowspan="2">
            <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                   name="data[<?= $item ?>][priceTotalExchangedToUsd]"
                   placeholder="Exchange Total"
                   maxlength="40" required="required"
                   value="">
        </td>
    </tr>
    <tr id="preInvoice_<?= $row->preInvoiceId ?>" class="info">
        <td>
            <?= $row->incomeInvoiceDataFlightNumber ?>
        </td>
        <td>
            <?= $row->incomeInvoiceDataAircraftTypeName . ' (' . $row->incomeInvoiceDataAircraftName . ')' ?>
        </td>
        <td>
            <?= date('d-m-Y', $row->incomeInvoiceDataDateDep) ?>
        </td>
        <td>
            <?= date('d-m-Y', $row->incomeInvoiceDataDateArr) ?>
        </td>
        <td>
            <?= $row->incomeInvoiceDataTypeOfPermission ?>
        </td>
    </tr>
<? endforeach; ?>
<tr>
    <td colspan="16">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td><span class="currency">USD</span> <span class="priceSubTotal"></span></td>
                        <td>USD <span class="priceSubTotalExchangedToUsd"></span></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>
<tr>
    <td colspan="16">
        <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
    </td>
</tr>
</tbody>
</table>
</form>