<form name="permissionOutcomeInvoiceStep2" id="permissionOutcomeInvoiceStep2" method="post"
      action="/management/permission/outcome-invoice-step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport Dep</th>
            <th>Date Dep</th>
            <th>Airport Arr</th>
            <th>Date Arr</th>
            <th>Country</th>
            <th>Agent</th>
            <th>Type of permission</th>
            <th>Number of permission</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Total</th>
            <th>Exchange Rate</th>
            <th>Exchange Total, USD</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
<!--            --><?// \Zend\Debug\Debug::dump($row) ?>
            <tr data-row="<?= $row->incomeInvoiceDataId ?>"
                class="<? if ($row->outcomeInvoiceMainId): ?>success<? endif ?>">
                <td rowspan="2">
                    <input type="checkbox" class="rowsSelected" name="rowsSelected[]"
                           data-rowId="<?= $row->incomeInvoiceDataId ?>"
                           value="<?= $row->incomeInvoiceDataId ?>">
                </td>
                <td rowspan="2" class="noWrap">
                    <a href="<?=
                    $this->url('browse',
                        array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                       target="_blank">
                        <?= $row->flightRefNumberOrder ?>
                    </a>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/permission/outcome-invoice-show',
                            array('id' => $row->outcomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->outcomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2" class="customer">
                    <?= $row->flightCustomerShortName ?>
                </td>
                <td rowspan="2">
                    <?= $row->flightAirOperatorShortName ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataFlightNumber): ?>
                        <?= $row->outcomeInvoiceDataFlightNumber ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataAircraftName): ?>
                        <?= $row->outcomeInvoiceDataAircraftTypeName ?>
                        <br/>
                        <small>(<?= $row->outcomeInvoiceDataAircraftName ?>)</small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">
                    <?= $row->legAirportDepICAO ?> (<?= $row->legAirportDepIATA ?>)
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataDateDep): ?>
                        <?= date('d-m-Y', $row->outcomeInvoiceDataDateDep) ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">
                    <?= $row->legAirportArrICAO ?> (<?= $row->legAirportArrIATA ?>)
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataDateArr): ?>
                        <?= date('d-m-Y', $row->outcomeInvoiceDataDateArr) ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">
                    <?= $row->preInvoiceCountryName ?>
                </td>
                <td rowspan="2">
                    <?= $row->incomeInvoiceMainAgentShortName ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataTypeOfPermission): ?>
                        <?= $row->outcomeInvoiceDataTypeOfPermission ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">
                    <?= $row->preInvoiceRequestTime ?>
                </td>
                <td class="text-right">
                    <? if ($row->outcomeInvoiceDataItemPrice): ?>
                        <?= $row->outcomeInvoiceDataItemPrice ?>
                        <small>, <?= $row->outcomeInvoiceMainCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataQuantity): ?>
                        <?= $row->outcomeInvoiceDataQuantity ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceDataUnitName): ?>
                        <?= $row->outcomeInvoiceDataUnitName ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->outcomeInvoiceDataPriceTotal): ?>
                        <?= $row->outcomeInvoiceDataPriceTotal ?>
                        <small>, <?= $row->outcomeInvoiceMainCurrency ?> </small>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainExchangeRate): ?>
                        <?= $row->outcomeInvoiceMainExchangeRate ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <? if ($row->outcomeInvoiceDataPriceTotalExchangedToUsd): ?>
                        <?= $row->outcomeInvoiceDataPriceTotalExchangedToUsd ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
            </tr>
            <tr data-incomeInvoiceRefuelRow="<?= $row->incomeInvoiceRefuelId ?>" class="info">
                <td>
                    <? if ($row->incomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/permission/income-invoice-show',
                            array('id' => $row->incomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->incomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataFlightNumber ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataAircraftTypeName ?>
                    <br/>
                    <small>(<?= $row->incomeInvoiceDataAircraftName ?>)</small>
                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceDataDateDep) ?>
                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceDataDateArr) ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataTypeOfPermission ?>
                </td>
                <td class="text-right">
                    <?= $row->incomeInvoiceDataItemPrice ?>
                    <small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataQuantity ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataUnitName ?>
                </td>
                <td class="text-right">
                    <?= $row->incomeInvoiceDataPriceTotal ?>
                    <small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                </td>
                <td>
                    <?= $row->incomeInvoiceMainExchangeRate ?>
                </td>
                <td class="text-right">
                    <?= $row->incomeInvoiceDataPriceTotalExchangedToUsd ?>
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="21">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>