<form name="permissionOutcomeInvoiceStep2" id="permissionOutcomeInvoiceStep2" method="post"
      action="/management/permission/outcome-invoice-step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport Dep</th>
            <th>Date Dep</th>
            <th>Airport Arr</th>
            <th>Date Arr</th>
            <th>Country</th>
            <th>Agent</th>
            <th>Type of permission</th>
            <th>Number of permission</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Total</th>
            <th>Exchange Rate</th>
            <th>Exchange Total, USD</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
            <? \Zend\Debug\Debug::dump($row) ?>
            <tr data-row="<?= $row->incomeInvoiceDataId ?>"
                class="<? if ($row->outcomeInvoiceMainId): ?>success<? endif ?>">
                <td rowspan="2">
                    <input type="checkbox" class="rowSelected" name="rowSelected[]"
                           data-rowId="<?= $row->incomeInvoiceDataId ?>"
                           value="<?= $row->incomeInvoiceDataId ?>">
                </td>
                <td rowspan="2" class="noWrap">
                    <a href="<?=
                    $this->url('browse',
                        array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                       target="_blank">
                        <?= $row->flightRefNumberOrder ?>
                    </a>
                </td>
                <td>
                    <? if ($row->outcomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/permission/outcome-invoice-show',
                            array('id' => $row->outcomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->outcomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td rowspan="2">Customer

                </td>
                <td rowspan="2">Air Operator

                </td>
                <td>Flight #

                </td>
                <td>Aircraft

                </td>
                <td rowspan="2">Airport Dep

                </td>
                <td>Date Dep

                </td>
                <td rowspan="2">Airport Arr

                </td>
                <td>Date Arr

                </td>
                <td rowspan="2">Country

                </td>
                <td rowspan="2">Agent

                </td>
                <td>Type of permission

                </td>
                <td rowspan="2">Number of permission

                </td>
                <td class="text-right">Price

                </td>
                <td>Quantity

                </td>
                <td>Unit

                </td>
                <td class="text-right">Total

                </td>
                <td>Exchange Rate

                </td>
                <td class="text-right">Exchange Total, USD
                    <? if ($row->outcomeInvoicePriceTotalExchangedToUsd): ?>
                        <?= $row->outcomeInvoicePriceTotalExchangedToUsd ?>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
             </tr>
            <tr data-incomeInvoiceRefuelRow="<?= $row->incomeInvoiceRefuelId ?>" class="info">
                <td>
                    <? if ($row->incomeInvoiceMainId): ?>
                        <a href="<?=
                        $this->url('management/permission/income-invoice-show',
                            array('id' => $row->incomeInvoiceMainId));?>"
                           target="_blank">
                            <?= $row->incomeInvoiceMainNumber ?>
                        </a>
                    <? else: ?>
                        &mdash;
                    <? endif; ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataFlightNumber ?>
                </td>
                <td>Aircraft

                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceDataDateDep) ?>
                </td>
                <td>
                    <?= date('d-m-Y', $row->incomeInvoiceDataDateArr) ?>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataTypeOfPermission ?>
                </td>
                <td class="text-right">
                    <?= $row->incomeInvoicePrice ?><small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                </td>
                <td>
                    <?= $row->incomeInvoiceDataQuantity ?>
                </td>
                <td>Unit

                </td>
                <td class="text-right">
                    <?= $row->incomeInvoiceDataPriceTotal ?><small>, <?= $row->incomeInvoiceMainCurrency ?> </small>
                </td>
                <td>
                    <?= $row->incomeInvoiceMainExchangeRate ?>
                </td>
                <td class="text-right">
                    <?= $row->incomeInvoiceDataPriceTotalExchangedToUsd ?>
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="21">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>