<form name="refuelIncomeInvoiceStep4" id="refuelIncomeInvoiceStep4" method="post"
      action="/management/refuel/income-invoice-add">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Fuel supplier</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="invoiceNumber" name="invoiceNumber" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data['invoiceNumber'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceDate" name="invoiceDate" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" readonly="readonly" value="<?= $this->data['invoiceDate'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceCurrency" name="invoiceCurrency" class="input-small"
                   placeholder="Currency" maxlength="40" required="required" readonly="readonly"
                   value="<?= $this->data['invoiceCurrency'] ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceExchangeRate" name="invoiceExchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" readonly="readonly"
                   value="<?= $this->data['invoiceExchangeRate'] ?>"/>
        </td>
        <td>
            <input type="hidden" name="invoiceRefuelSupplierId" value="<?= $this->data['invoiceRefuelSupplierId'] ?>">
            <input type="text" class="input-small" name="invoiceRefuelSupplierName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $this->data['invoiceRefuelSupplierName'] ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date</th>
        <th>Quantity, LTR</th>
        <th>Quantity, Unit</th>
        <th>Unit</th>
        <th>Price, <span class="refuelCurrency"><?= $this->data['invoiceCurrency'] ?></span></th>
        <th>TAX</th>
        <th>MOT</th>
        <th>VAT, %</th>
        <th>Deliver</th>
        <th>Total price, <span class="refuelCurrency"><?= $this->data['invoiceCurrency'] ?></span></th>
        <th>Total, <span class="refuelCurrency"><?= $this->data['invoiceCurrency'] ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data['data'] as $row): ?>
        <? // \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceRefuelId_<?= $row['refuelId'] ?>">
            <td>
                <input type="hidden" name="data[<?= $row['refuelId'] ?>][refuelId]" value="<?= $row['refuelId'] ?>"/>
                <input type="text" name="data[<?= $row['refuelId'] ?>][flightRefNumberOrder]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightRefNumberOrder'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['refuelId'] ?>][flightAgentId]"
                       value="<?= $row['flightAgentId'] ?>">
                <input type="text" name="data[<?= $row['refuelId'] ?>][flightAgentShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightAgentShortName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['refuelId'] ?>][flightAirOperatorId]"
                       value="<?= $row['flightAirOperatorId'] ?>">
                <input type="text" name="data[<?= $row['refuelId'] ?>][flightAirOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightAirOperatorShortName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['refuelId'] ?>][flightAirOperatorNumber]"
                       class="input-small"
                       maxlength="40" required="required"
                       value="<?= $row['flightAirOperatorNumber'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['refuelId'] ?>][flightAircraftId]"
                       value="<?= $row['flightAircraftId'] ?>">
                <input type="text" name="data[<?= $row['refuelId'] ?>][flightAircraftName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['flightAircraftName'] ?>">
            </td>
            <td>
                <input type="hidden" name="data[<?= $row['refuelId'] ?>][refuelAirportId]"
                       value="<?= $row['refuelAirportId'] ?>">
                <input type="text" name="data[<?= $row['refuelId'] ?>][refuelAirportName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row['refuelAirportName'] ?>">
            </td>
            <td>
                <input type="text" name="data[<?= $row['refuelId'] ?>][refuelDate]"
                       class="input-small date"
                       placeholder="Date of refuel"
                       maxlength="40" required="required" value="<?= $row['refuelDate'] ?>">
            </td>
            <td>
                <input type="text" class="refuelQuantityLtr input-mini"
                       name="data[<?= $row['refuelId'] ?>][refuelQuantityLtr]"
                       placeholder="QTY LTR"
                       maxlength="40" required="required" value="<?= $row['refuelQuantityLtr'] ?>">
            </td>
            <td>
                <input type="text" class="refuelQuantityOtherUnits input-mini"
                       name="data[<?= $row['refuelId'] ?>][refuelQuantityOtherUnits]"
                       placeholder="Quantity est"
                       maxlength="40" required="required" value="<?= $row['refuelQuantityOtherUnits'] ?>">
            </td>
            <td>
                <select name="data[<?= $row['refuelId'] ?>][refuelUnitId]"
                        class="refuelUnitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row['refuelUnitId'] == $key): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="refuelItemPrice input-mini text-right"
                       name="data[<?= $row['refuelId'] ?>][refuelItemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="<?= number_format($row['refuelItemPrice'], 4, '.', '') ?>">
            </td>
            <td>
                <input type="text" class="refuelTax input-mini" name="data[<?= $row['refuelId'] ?>][refuelTax]"
                       placeholder="TAX"
                       maxlength="40" required="required" value="<?= $row['refuelTax'] ?>">
            </td>
            <td>
                <input type="text" class="refuelMot input-mini" name="data[<?= $row['refuelId'] ?>][refuelMot]"
                       placeholder="MOT"
                       maxlength="40" required="required" value="<?= $row['refuelMot'] ?>">
            </td>
            <td>
                <input type="text" class="refuelVat input-mini" name="data[<?= $row['refuelId'] ?>][refuelVat]"
                       placeholder="VAT"
                       maxlength="40" required="required" value="<?= $row['refuelVat'] ?>">
            </td>
            <td>
                <input type="text" class="refuelDeliver input-mini" name="data[<?= $row['refuelId'] ?>][refuelDeliver]"
                       placeholder="Deliver"
                       maxlength="40" required="required" value="<?= $row['refuelDeliver'] ?>">
            </td>
            <td>
                <input type="text" class="refuelPrice input-mini text-right"
                       name="data[<?= $row['refuelId'] ?>][refuelPrice]"
                       placeholder="Total price"
                       maxlength="40" required="required"
                       value="<?= $row['refuelPrice'] ?>">
            </td>
            <td>
                <?php
                $refuelPriceSubTotal += $row['refuelPriceTotal'];
                ?>
                <input type="text" class="refuelPriceTotal input-mini text-right"
                       name="data[<?= $row['refuelId'] ?>][refuelPriceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="<?= $row['refuelPriceTotal'] ?>">
            </td>
            <td>
                <?php
                $refuelExchangeToUsdPriceSubTotal += $row['refuelExchangeToUsdPriceTotal'];
                ?>
                <input type="text" class="refuelExchangeToUsdPriceTotal input-mini text-right"
                       name="data[<?= $row['refuelId'] ?>][refuelExchangeToUsdPriceTotal]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="<?= $row['refuelExchangeToUsdPriceTotal'] ?>">
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="18">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="refuelCurrency"><?= $this->data['invoiceCurrency'] ?></span> <span
                                    class="refuelPriceSubTotal"><?= number_format($refuelPriceSubTotal, 2, '.', '') ?></span>
                            </td>
                            <td>USD <span
                                    class="refuelExchangeToUsdPriceSubTotal"><?= number_format($refuelExchangeToUsdPriceSubTotal, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>