<?php
// Проверяем, одинаков ли fuel supplier
//todo
//$fuelSupplierOld = '';
foreach ($this->data as $row) {
    $fuelSupplier = $row->refuelAgentShortName;
}
//
?>
<form name="managementRefuelStep3" id="managementRefuelStep3" method="post" action="/management/refuel/step3">
    <table class="table-bordered table-condensed">
        <thead>
        <tr>
            <th>Number of invoice</th>
            <th>Date</th>
            <th>Currency</th>
            <th>Exchange Rate</th>
            <th>Fuel supplier</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <input type="text" id="invoiceNumber" name="invoiceNumber" class="input-small"
                       placeholder="Number of invoice"
                       maxlength="40" value=""/>
            </td>
            <td>
                <input type="text" id="invoiceDate" name="invoiceDate" class="input-small date" placeholder="Date"
                       maxlength="40" value=""/>
            </td>
            <td>
                <select id="invoiceCurrency" name="invoiceCurrency" class="chosen input-small"
                        data-placeholder="Currency"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->currencies as $key => $value): ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" id="InvoiceExchangeRate" name="InvoiceExchangeRate" class="input-small"
                       placeholder="Exchange Rate" maxlength="40" value=""/>
            </td>
            <td>
                <?= $fuelSupplier ?>
            </td>
        </tr>
        </tbody>
    </table>
    <hr/>
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th>ORD</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Aircraft</th>
            <th>Date</th>
            <th>Airport Dep</th>
            <th>Quantity, LTR</th>
            <th>Quantity, Unit</th>
            <th>Unit</th>
            <th>Price</th>
            <th>TAX</th>
            <th>MOT</th>
            <th>VAT, %</th>
            <th>Deliver</th>
            <th>Total price</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
            <!--            --><? // \Zend\Debug\Debug::dump($row) ?>
            <tr id="preInvoiceRefuelId_<?= $row->refuelId ?>" class="info">
                <td class="noWrap"><?= $row->flightRefNumberOrder ?></td>
                <td><?= $row->flightAgentShortName ?></td>
                <td><?= $row->flightAirOperatorShortName ?></td>
                <td><?= $row->flightAircraftTypeName . ' (' . $row->flightAircraftName . ')' ?></td>
                <td><?= date('d-m-Y', $row->refuelDate) ?></td>
                <td><?= $row->refuelAirportICAO . ' (' . $row->refuelAirportIATA . ')' ?></td>
                <td><?= $row->refuelQuantityLtr ?></td>
                <td><?= $row->refuelQuantityOtherUnits ?></td>
                <td><?= $row->refuelUnitName ?></td>
                <td><?= $row->refuelPriceUsd ?></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><?= $row->refuelTotalPriceUsd ?></td>
            </tr>
            <tr id="invoiceRefuelId_<?= $row->refuelId ?>">
                <td>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][refuelId]" value="<?= $row->refuelId ?>"/>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][flightRefNumberOrder]"
                           value="<?= $row->flightRefNumberOrder ?>"/>

                    <?= $row->flightRefNumberOrder ?>
                </td>
                <td>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][flightAgentId]"
                           value="<?= $row->flightAgentId ?>">
                    <?= $row->flightAgentShortName ?>
                </td>
                <td>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][flightAirOperator]"
                           value="<?= $row->flightAirOperator ?>">
                    <?= $row->flightAirOperatorShortName ?>
                </td>
                <td>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][flightAircraftId]"
                           value="<?= $row->flightAircraftId ?>">
                    <?= $row->flightAircraftTypeName . ' (' . $row->flightAircraftName . ')' ?>
                </td>
                <td>
                    <input type="text" name="data[<?= $row->refuelId ?>][refuelDate]"
                           class="input-small date"
                           placeholder="Date of refuel"
                           maxlength="40" value="<?= date('d-m-Y', $row->refuelDate) ?>">
                </td>
                <td>
                    <input type="hidden" name="data[<?= $row->refuelId ?>][refuelAirportId]"
                           value="<?= $row->refuelAirportId ?>">
                    <?= $row->refuelAirportICAO . ' (' . $row->refuelAirportIATA . ')' ?>
                </td>
                <td>
                    <input type="text" class="refuelQuantityLtr"
                           name="data[<?= $row->refuelId ?>][refuelQuantityLtr]"
                           class="input-small"
                           placeholder="QTY LTR"
                           maxlength="40" value="<?= $row->refuelQuantityLtr ?>">
                </td>
                <td>
                    <input type="text" class="refuelQuantityOtherUnits"
                           name="data[<?= $row->refuelId ?>][refuelQuantityOtherUnits]" class="input-small"
                           placeholder="Quantity est"
                           maxlength="40" value="<?= $row->refuelQuantityOtherUnits ?>">
                </td>
                <td>
                    <select class="refuelUnitName"
                            name="data[<?= $row->refuelId ?>][refuelUnitName]"
                            class="chosen input-small"
                            data-placeholder="Unit"
                            required="required">
                        <option value=""></option>
                        <? foreach ($this->units as $key => $value): ?>
                            <? if ($row->refuelUnitName == $value): ?>
                                <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                            <? else: ?>
                                <option value="<?= $key ?>"><?= $value ?></option>
                            <? endif; ?>
                        <? endforeach; ?>
                    </select>
                </td>
                <td>
                    <input type="text" class="refuelPriceUsd"
                           name="data[<?= $row->refuelId ?>][refuelPriceUsd]"
                           class="input-small"
                           placeholder="Price est"
                           maxlength="40" value="<?= $row->refuelPriceUsd ?>">
                </td>
                <td>
                    <input type="text" class="refuelTax" name="data[<?= $row->refuelId ?>][refuelTax]"
                           class="input-small"
                           placeholder="TAX"
                           maxlength="40" value="">
                </td>
                <td>
                    <input type="text" class="refuelMot" name="data[<?= $row->refuelId ?>][refuelMot]"
                           class="input-small"
                           placeholder="MOT"
                           maxlength="40" value="">
                </td>
                <td>
                    <input type="text" class="refuelVat" name="data[<?= $row->refuelId ?>][refuelVat]"
                           class="input-small" placeholder="VAT"
                           maxlength="40" value="">
                </td>
                <td>
                    <input type="text" class="refuelDeliver" name="data[<?= $row->refuelId ?>][refuelDeliver]"
                           class="input-small" placeholder="Deliver"
                           maxlength="40" value="">
                </td>
                <td>
                    <input type="text" class="refuelPriceTotalUsd"
                           name="data[<?= $row->refuelId ?>][refuelPriceTotalUsd]"
                           class="input-small"
                           placeholder="Total price"
                           maxlength="40"
                           value="">
                </td>
                <td>
                    <input type="text" class="refuelPriceTotal" name="data[<?= $row->refuelId ?>][refuelPriceTotal]"
                           class="input-small"
                           placeholder="Total"
                           maxlength="40"
                           value="">
                </td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="16">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
            </td>
        </tr>
        </tbody>
    </table>
</form>