<form name="managementRefuelStep2" id="managementRefuelStep2" method="post" action="/management/refuel/step2">
    <table
        class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
        <thead>
        <tr>
            <th></th>
            <th>ORD</th>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Aircraft</th>
            <th>Date</th>
            <th>Airport Dep</th>
            <th>Fuel supplier</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->data as $row): ?>
            <tr data-refuelRow="<?= $row->refuelId ?>">
                <td>
                    <input type="checkbox" class="refuelsSelected" name="refuelsSelected[]" data-refuelId="<?= $row->refuelId ?>" value="<?= $row->refuelId ?>">
                </td>
                <td><?= $row->flightRefNumberOrder ?></td>
                <td><?= $row->flightAgentShortName ?></td>
                <td><?= $row->flightAirOperatorShortName ?></td>
                <td><?= $row->flightAircraftTypeName . ' (' . $row->flightAircraftName . ')' ?></td>
                <td><?= date('d-m-Y', $row->refuelDate) ?></td>
                <td><?= $row->refuelAirportICAO . ' (' . $row->refuelAirportIATA . ')' ?></td>
                <td data-refuelAgentShortName="<?= $row->refuelAgentShortName ?>"><?= $row->refuelAgentShortName ?></td>
                <td><?= $row->refuelQuantityOtherUnits ?></td>
                <td><?= $row->refuelUnitName ?></td>
                <td class="text-right"><?= $row->refuelPriceUsd ?></td>
                <td class="text-right"><?= number_format($row->refuelQuantityOtherUnits * $row->refuelPriceUsd, 4, '.', '') ?></td>
            </tr>
        <? endforeach; ?>
        <tr>
            <td colspan="13">
                <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Apply">
            </td>
        </tr>
        </tbody>
    </table>
</form>