<?php
// Проверяем, одинаков ли fuel supplier
//todo
//$fuelSupplierOld = '';
foreach ($this->data as $row) {
    $refuelCustomerId = $row->incomeInvoiceAgentId;
    $refuelCustomerName = $row->incomeInvoiceAgentName;
}
//
?>
<form name="refuelIncomeInvoiceStep3" id="refuelIncomeInvoiceStep3" method="post"
      action="/management/refuel/income-invoice-step3">
<table id="invoiceHeader" class="table-bordered table-condensed">
    <thead>
    <tr>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Rate Apply</th>
        <th>Customer</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <input type="text" id="invoiceNumber" name="invoiceNumber" class="input-small"
                   placeholder="Invoice #"
                   maxlength="40" required="required" value="<?= $this->newInvoiceNumber ?>"/>
        </td>
        <td>
            <input type="text" id="invoiceDate" name="invoiceDate" class="input-small date" placeholder="Date"
                   maxlength="40" required="required" value="<?= date('d-m-Y', time()) ?>"/>
        </td>
        <td>
            <select id="invoiceCurrency" name="invoiceCurrency" class="chosen input-small"
                    data-placeholder="Currency"
                    required="required">
                <option value=""></option>
                <? foreach ($this->currencies as $key => $value): ?>
                    <? if ($value == 'USD'): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" id="invoiceExchangeRate" name="invoiceExchangeRate" class="input-small"
                   placeholder="Exchange Rate" maxlength="40" required="required" value="1"/>
        </td>
        <td>
            <input id="rateApply" name="rateApply" type="submit" class="btn btn-primary" value="Apply">
        </td>
        <td>
            <input type="hidden" name="invoiceCustomerId" value="<?= $refuelCustomerId ?>">
            <input type="text" class="input-small" name="invoiceCustomerName" maxlength="40" required="required"
                   readonly="readonly" value="<?= $refuelCustomerName ?>">
        </td>
    </tr>
    </tbody>
</table>
<hr/>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Fuel supplier</th>
        <th>Air Operator</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date</th>
        <th>Quantity, LTR</th>
        <th>Quantity, Unit</th>
        <th>Unit</th>
        <th>Price</th>
        <th>TAX</th>
        <th>MOT</th>
        <th>VAT, %</th>
        <th>Deliver</th>
        <th>Total price</th>
        <th>Total</th>
        <th>Exchange Rate</th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->data as $row): ?>
<!--        --><?// \Zend\Debug\Debug::dump($row) ?>
        <tr id="outcomeInvoiceRefuelId<?= $row->incomeInvoiceRefuelId ?>">
            <td class="noWrap" rowspan="2">
                <input type="hidden" name="data[<?= $row->incomeInvoiceRefuelId ?>][incomeInvoiceRefuelId]" value="<?= $row->incomeInvoiceRefuelId ?>"/>
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][preInvoiceFlightRefNumberOrder]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->preInvoiceFlightRefNumberOrder ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->incomeInvoiceRefuelId ?>][supplierId]"
                       value="<?= $row->incomeInvoiceAgentId ?>">
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][incomeInvoiceAgentShortName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly" value="<?= $row->incomeInvoiceAgentShortName ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->incomeInvoiceRefuelId ?>][airOperatorId]"
                       value="<?= $row->incomeInvoiceAirOperatorId ?>">
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][incomeInvoiceAirOperatorShortName]"
                       class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->incomeInvoiceAirOperatorShortName ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->incomeInvoiceRefuelId ?>][aircraftId]"
                       value="<?= $row->incomeInvoiceAircraftId ?>">
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][incomeInvoiceAircraftName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->incomeInvoiceAircraftTypeName . ' (' . $row->incomeInvoiceAircraftName . ')' ?>">
            </td>
            <td rowspan="2">
                <input type="hidden" name="data[<?= $row->incomeInvoiceRefuelId ?>][airportDepId]"
                       value="<?= $row->incomeInvoiceAirportId ?>">
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][incomeInvoiceAirportDepName]" class="input-small readonly"
                       maxlength="40" required="required" readonly="readonly"
                       value="<?= $row->incomeInvoiceAirportDepICAO . ' (' . $row->incomeInvoiceAirportDepIATA . ')' ?>">
            </td>
            <td rowspan="2">
                <input type="text" name="data[<?= $row->incomeInvoiceRefuelId ?>][date]"
                       class="input-small date readonly"
                       placeholder="Date of refuel"
                       maxlength="40" required="required" value="<?= date('d-m-Y', $row->incomeInvoiceDate) ?>">
            </td>
            <td rowspan="2">
                <input type="text" class="quantityLtr input-mini readonly"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][quantityLtr]"
                       placeholder="QTY LTR"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="quantityOtherUnits input-mini"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][quantityOtherUnits]"
                       placeholder="Quantity est"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <select name="data[<?= $row->incomeInvoiceUnitId ?>][unitId]"
                        class="unitId chosen input-small"
                        data-placeholder="Unit"
                        required="required">
                    <option value=""></option>
                    <? foreach ($this->units as $key => $value): ?>
                        <? if ($row->incomeInvoiceUnitName == $value): ?>
                            <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                        <? else: ?>
                            <option value="<?= $key ?>"><?= $value ?></option>
                        <? endif; ?>
                    <? endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="itemPrice input-mini text-right"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][itemPrice]"
                       placeholder="Price est"
                       maxlength="40" required="required"
                       value="<?= number_format($row->incomeInvoiceItemPrice, 4, '.', '') ?>">
            </td>
            <td>
                <input type="text" class="tax input-mini" name="data[<?= $row->incomeInvoiceRefuelId ?>][tax]"
                       placeholder="TAX"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="mot input-mini" name="data[<?= $row->incomeInvoiceRefuelId ?>][mot]"
                       placeholder="MOT"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="vat input-mini" name="data[<?= $row->incomeInvoiceRefuelId ?>][vat]"
                       placeholder="VAT"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="deliver input-mini" name="data[<?= $row->incomeInvoiceRefuelId ?>][deliver]"
                       placeholder="Deliver"
                       maxlength="40" required="required" value="">
            </td>
            <td>
                <input type="text" class="price input-mini text-right"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][price]"
                       placeholder="Total price"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td>
                <input type="text" class="priceTotal input-mini text-right"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][priceTotal]"
                       placeholder="Total"
                       maxlength="40" required="required"
                       value="">
            </td>
            <td class="text-right">
                &mdash;
            </td>
            <td>
                <input type="text" class="priceTotalExchangedToUsd input-mini text-right"
                       name="data[<?= $row->incomeInvoiceRefuelId ?>][priceTotalExchangedToUsd]"
                       placeholder="Exchange Total"
                       maxlength="40" required="required"
                       value="">
            </td>
        </tr>
        <tr id="incomeInvoiceRefuelId_<?= $row->incomeInvoiceRefuelId ?>" class="info">
            <td>
                <?= $row->incomeInvoiceQuantityOtherUnits ?>
            </td>
            <td>
                <?= $row->incomeInvoiceUnitName ?>
            </td>
            <td class="text-right">
                <?= number_format($row->incomeInvoiceItemPrice, 4, '.', '') ?>, <small><?= $row->incomeInvoiceMainCurrency ?></small>
            </td>
            <td>
                <?= $row->incomeInvoiceTax ?>
            </td>
            <td>
                <?= $row->incomeInvoiceMot ?>
            </td>
            <td>
                <?= $row->incomeInvoiceVat ?>
            </td>
            <td>
                <?= $row->incomeInvoiceDeliver ?>
            </td>
            <td class="text-right">
                <?= $row->incomeInvoicePrice ?>, <small><?= $row->incomeInvoiceMainCurrency ?></small>
            </td>
            <td class="text-right">
                <?= number_format($row->incomeInvoicePriceTotal, 2, '.', '') ?>, <small><?= $row->incomeInvoiceMainCurrency ?></small>
            </td>
            <td class="text-right">
                <?= $row->incomeInvoiceMainExchangeRate ?>
            </td>
            <td class="text-right">
                <?= $row->incomeInvoicePriceTotalExchangedToUsd ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="18">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td><span class="refuelCurrency">USD</span> <span class="refuelPriceSubTotal"></span></td>
                            <td>USD <span class="refuelExchangeToUsdPriceSubTotal"></span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="18">
            <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
        </td>
    </tr>
    </tbody>
</table>
</form>