<?php
$title = 'Удалить сотрудника';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы уверены что хотите удалить
    <strong>'<?php echo $this->escapeHtml($user->username); ?>'</strong> (<?php echo $this->escapeHtml($user->email); ?>)?
</p>
<?php
$url = $this->url('admin/user', array(
    'action' => 'delete',
    'id'     => $this->user_id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="user_id" value="<?php echo (int) $user->user_id; ?>" />
    <input type="submit" name="del" value="Да" class="btn btn-warning" />
    <input type="submit" name="del" value="Нет" class="btn btn-link" />
</div>
</form>
