<?php
$title = 'Удалить сотрудника';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($album->display_name); ?>' by
    '<?php echo $this->escapeHtml($album->email); ?>'?
</p>
<?php
$url = $this->url('admin/user', array(
    'action' => 'delete',
    'id'     => $this->id_user,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $album->id_user; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
