<?php
$title = 'Удалить сотрудника';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы уверены что хотите удалить
    <strong>'<?php echo $this->escapeHtml($user->display_name); ?>'</strong> (<?php echo $this->escapeHtml($user->email); ?>)?
</p>
<?php
$url = $this->url('admin/user', array(
    'action' => 'delete',
    'id'     => $this->id_user,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id_user" value="<?php echo (int) $user->id_user; ?>" />
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>
