<?php
$title = 'Список сотрудников';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('zfcadmin/user', array('action' => 'add'));?>" class="btn btn-primary">Добавить сотрудника</a>
</p>

<table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Фамилия Имя</th>
        <th>Отображаемое имя</th>
        <th>Email</th>
        <th>Статус</th>
        <th>Операции</th>
    </tr>
    <?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->user_id);?></td>
        <td><?php echo $this->escapeHtml($user->username);?></td>
        <td><?php echo $this->escapeHtml($user->display_name);?></td>
        <td><?php echo $this->escapeHtml($user->email);?></td>
        <td>
            <?php if ($user->state == 1) {
                echo 'Активен';
            } else {
                echo 'Блокирован';
            };?>
        <td>
            <a href="<?php echo $this->url('zfcadmin/user',
                array('action' => 'edit', 'id' => $user->user_id));?>" class="btn btn-success">Редактировать</a>
            <a href="<?php echo $this->url('zfcadmin/user',
                array('action' => 'delete', 'id' => $user->user_id));?>" class="btn btn-warning">Удалить</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
