<?php
$title = 'Список сотрудников';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/users', array('action' => 'add'));?>">Добавить сотрудника</a>
</p>

<table class="table">
<tr>
    <th>Имя</th>
    <th>Email</th>
    <th>Статус</th>
    <th>Операции</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->display_name);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $this->escapeHtml($user->state);?></td>
    <td>
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'edit', 'id' => $user->user_id));?>">Edit</a>
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'delete', 'id' => $user->user_id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
