<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?= $this->url('zfcadmin/libraries', array('action' => 'index')); ?>">Libraries</a> <span
            class="divider">/</span></li>
    <li>Advanced search</li>
</ul>
<?php
$title = 'Advanced search';
$this->headTitle($title);
?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 leftPanes">
            <?php echo $this->partial('fc-libraries-search/widgets/form/search/default.phtml', array('form' => $form)); ?>
        </div>
        <div class="span10 rightPanes">
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

            <? if (count($result) > 0): ?>
                    <legend>Search Result</legend>
                    <?php
                    switch ($library) {
                        case 'library_aircraft':
                            $widgetName = 'aircraftTable';
                            break;

                        case 'library_aircraft_type':
                            $widgetName = 'aircraftTypeTable';
                            break;

                        case 'library_air_operator':
                            $widgetName = 'airOperatorTable';
                            break;

                        case 'library_airport':
                            $widgetName = 'airportTable';
                            break;

                        case 'library_base_of_permit':
                            $widgetName = 'baseOfPermitTable';
                            break;

                        case 'library_city':
                            $widgetName = 'cityTable';
                            break;

                        case 'library_country':
                            $widgetName = 'countryTable';
                            break;

                        case 'library_currency':
                            $widgetName = 'currencyTable';
                            break;

                        case 'library_kontragent':
                            $widgetName = 'kontragentTable';
                            break;

                        case 'library_region':
                            $widgetName = 'regionTable';
                            break;

                        case 'library_unit':
                            $widgetName = 'unitTable';
                            break;

                        default:
                            // skip it
                            break;
                    }
                    ?>

                    <?php echo $this->partial('fc-libraries-search/widgets/' . $widgetName . '.phtml', array('result' => $result)); ?>

            <? endif; ?>

        </div>
    </div>
</div>
