<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?= $this->url('zfcadmin/libraries', array('action' => 'index')); ?>">Libraries</a> <span
            class="divider">/</span></li>
    <li>Advanced search</li>
</ul>
<?php
$title = 'Advanced search';
$this->headTitle($title);
?>

<?php
$displayOptions = array(
    'elements' => array(
        'text' => array(
            'class' => 'span3',
            'required' => true,
        ),
    ),
);

//Form object
$form = $this->form;
$formType = $this->formType;
$validData = $this->validData;
$form->prepare();

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/aircraft', array('action' => 'add')));
$form->prepare();
if ($form->getMessages()):
    ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        The form fields are not filled out correctly. (The search form does not support field errors.
        Use $form->getMessages() to inform user about data errors.)
    </div>
    <?php
    \Zend\Debug\Debug::dump($form->getMessages(), '$form->getMessages():');
endif;

//Default form display (the 'one-liner')
//Good for quick form preview or when there are no special presentation requirements
//If you need more control over the form view, use the 'controlled' approach below
echo $this->formTwb($form, $formType, $displayOptions);
