<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?= $this->url('zfcadmin/libraries', array('action' => 'index')); ?>">Libraries</a> <span
            class="divider">/</span></li>
    <li>Advanced search</li>
</ul>
<?php
$title = 'Advanced search';
$this->headTitle($title);
?>

<?php
$displayOptions = array(
    'elements' => array(
        'text' => array(
            'class' => 'span3',
            'required' => true,
        ),
    ),
);

//Form object
$form = $this->form;
//$formType = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_SEARCH;
$validData = $this->validData;
$form->prepare();

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/advanced_search', array('action' => 'advancedSearch')));
$form->prepare();
if ($form->getMessages()):
    ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        The form field are not filled out correctly.
    </div>
<?php
endif;

//Default form display (the 'one-liner')
//Good for quick form preview or when there are no special presentation requirements
//If you need more control over the form view, use the 'controlled' approach below
echo $this->formTwb($form, $formType, $displayOptions);
