<?php
$title = 'Add AP Service';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Type of service: AP Service</li>
</ul>
<div class="alert alert-info">
    <strong>Warning!</strong> Page in development.
</div>

<?=
$this->partial('widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
    )
)
?>

<h1><?= $title ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'airportId' => array(
            'required' => true,
        ),
        'agentId' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$form->setAttribute('action', $this->url('apService', array('action' => 'add', 'id' => $this->header->id)));
$form->prepare();
?>

<?=
$this->partial('widgets/tables/ap-service.phtml',
    array(
        'apServices' => $this->apServices,
        'status' => $this->header->status,
        'fixedHeader' => true,
    )
)
?>


<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>
