<?php
$title = 'Edit AP Service';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Type of service: AP Service</li>
</ul>

<?=
$this->partial('fc-flight/_widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
    )
)
?>

<h1><?= $title ?></h1>

<?php if ($this->form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<div id="apService">
    <?=
    $this->partial('fc-flight/_widgets/tables/ap-service.phtml',
        array(
            'currentId' => $this->id,
            'apServices' => $this->apServices,
            'apServicesTotal' => $this->apServicesTotal,
            'status' => $this->header->status,
            'fixedHeader' => true,
        )
    )
    ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('apService', array('action' => 'edit', 'id' => $this->id)));
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>

    <table class="table ">
        <thead>
        <tr>
            <th>Airport</th>
            <th>Type of AP Service</th>
            <th>Agent</th>
            <th>Price</th>
            <th>Currency</th>
            <th>Exchange Rate</th>
            <th>Price USD</th>
            <th>Status</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                $field = $form->get('airportId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('typeOfApServiceId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('agentId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('price');
                echo $this->formInput($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('currency');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('exchangeRate');
                echo $this->formInput($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('priceUSD');
                echo $this->formInput($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('status');
                echo $this->formCheckbox($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
