<?php
$displayOptions = array(
    'elements' => array(
        'dateOrderFrom' => array(
            'required' => false,
        ),
        'dateOrderTo' => array(
            'required' => false,
        ),
        'status' => array(
            'required' => false,
        ),
        'customer' => array(
            'required' => false,
        ),
        'airOperator' => array(
            'required' => false,
        ),
        'aircraft' => array(
            'required' => false,
        ),
    ),
);
$formType = 'vertical';
$form = $this->form;
$form->prepare();

echo $this->formTwb()->openTag($form, $formType);

echo'<legend>Search</legend>';
echo $this->formRowTwb($form->get('dateOrderFrom'), $formType, $displayOptions['elements']['dateOrderFrom']);
echo $this->formRowTwb($form->get('dateOrderTo'), $formType, $displayOptions['elements']['dateOrderTo']);
echo $this->formRowTwb($form->get('status'), $formType, $displayOptions['elements']['status']);
echo $this->formRowTwb($form->get('customer'), $formType, $displayOptions['elements']['customer']);
echo $this->formRowTwb($form->get('airOperator'), $formType, $displayOptions['elements']['airOperator']);
echo $this->formRowTwb($form->get('aircraft'), $formType, $displayOptions['elements']['aircraft']);

echo $this->formRowTwb($form->get('csrf'));

echo $this->formActionsTwb(array($form->get('submitBtn'), $formType));

echo $this->formTwb()->closeTag();

?>
