<?php
//$this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <?php echo $this->translate('Password changed successfully.'); ?>
</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <?php echo $this->translate('Unable to update your password. Please try again.'); ?>
</div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$formType = $this->formType;
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
//не удалять
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'credential' => array(
            'required' => true,
        ),
        'newCredential' => array(
            'required' => true,
        ),
        'newCredentialVerify' => array(
            'required' => true,
        ),
    ),
);
foreach ($form as $element) {
    $label = $element->getLabel();
    if ($label != '') {
        $element->setLabel($this->translate($label));
    }
}
$form->prepare();
?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>
