<?php
    $this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.'); ?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());
echo $this->form()->openTag($form);
?>
<?php echo $this->formElementErrors($form->get('identity')); ?>
<?php echo $this->formInput($form->get('identity')); ?>
<label>
    <span for="credential"><?php echo $this->translate('Current Password'); ?></span>
    <?php
    echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
    ?>
</label>
<label>
    <span for="newCredential"><?php echo $this->translate('New Password'); ?></span>
    <?php
    echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
    ?>
</label>
<label>
    <span for="newCredentialVerify"><?php echo $this->translate('Verify New Password'); ?></span>
    <?php
    echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
    ?>
</label>

<input name="submit" type="submit" value="<?php echo $this->translate('Submit'); ?>" class="btn btn-primary">

<?php echo $this->form()->closeTag(); ?>
