<h3>Изменить пароль для <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Пароль успешно изменен.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Не удается обновить пароль. Пожалуйста, попробуйте еще раз.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<?php echo $this->formElementErrors($form->get('identity')); ?>
<?php echo $this->formInput($form->get('identity')); ?>
<label>
    <span for="credential">Текущий пароль</span>
    <?php
    echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
    ?>
</label>
<label>
    <span for="newCredential">Новый пароль</span>
    <?php
    echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
    ?>
</label>
<label>
    <span for="newCredentialVerify">Повторите новый пароль</span>
    <?php
    echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
    ?>
</label>

<input name="submit" type="submit" value="Отправить" class="btn btn-primary">

<?php echo $this->form()->closeTag(); ?>
