<h3>Изменить Email для <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Адрес электронной почты успешно изменен.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Не удалось обновить ваш электронный адрес. Пожалуйста, попробуйте еще раз.</div>
<?php endif; ?>
<?php

$form = $this->changeEmailForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');

?>

<?php echo $this->form()->openTag($form) ?>
    <?php foreach ($form as $element): ?>
        <label>
        <?php if ($element->getLabel() != null): ?>
                <?php
                switch ($element->getLabel()) {
                    case 'New Email':
                        echo '<span>Новый Email</span>';
                        break;
                    case 'Verify New Email':
                        echo '<span>Подтвердите новый Email</span>';
                        break;
                    case 'Password':
                        echo '<span>Пароль</span>';
                        break;
                }
                ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formButton($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else: ?>
            <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
        <?php endif ?>
    </label>
    <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
    <input type="submit" value="Отправить" class="btn btn-primary" />
<?php echo $this->form()->closeTag() ?>
