<?php
$this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<h3><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <?php echo $this->translate('Email address changed successfully.'); ?>
</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <?php echo $this->translate('Unable to update your email address. Please try again.'); ?>
</div>
<?php endif; ?>
<?php
$form = $this->changeEmailForm;
$formType = $this->formType;
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');
$displayOptions = array(
    'class' => 'form-horizontal',
);
if ($this->redirect){
    $form->add(array(
        'name' => 'redirect',
        'type' => 'Zend\Form\Element\Hidden',
        'attributes' => array(
            'value' => $this->redirect,
        ),
    ));
}
$form->add(array(
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => array(
        'value' => 'Отправить',
    ),
));
foreach ($form as $element) {
    $label = $element->getLabel();
    if ($label != '') {
        $element->setLabel($this->translate($label));
    }
}
$form->prepare();
?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>

