<?php
    $this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/changeemail') ?>" class="btn btn-info">Изменить Email</a>
<a href="<?php echo $this->url('zfcuser/changepassword') ?>" class="btn btn-info">Изменить пароль</a>
<a href="<?php echo $this->url('zfcuser/logout') ?>" class="btn btn-warning"><?php echo $this->translate('Sign Out'); ?></a>
<div style="clear:both;"></div>
