<?php
//    $this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<div style="padding-bottom: 1em;">
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#" class="disabled">Overview</a></li>
        <li><a href="<?php echo $this->url('zfcuser/changeemail'); ?>">Change Email</a></li>
        <li><a href="<?php echo $this->url('zfcuser/changepassword'); ?>">Change Password</a></li>
        <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><?php echo $this->translate('Sign Out'); ?></a></li>
    </ul>
</div>
<div style="clear:both;"></div>
<div class="alert alert-info">
    <strong>TODO!</strong> Здесь будут логи последних действий этого пользователя.
</div>
