<?php
    $this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formElementErrors($form->get('identity')) ?>
<label>
    <span><?php echo $this->translate('Email'); ?></span>
    <?php echo $this->formInput($form->get('identity')) ?>
</label>
<label>
    <span><?php echo $this->translate('Password'); ?></span>
    <?php echo $this->formInput($form->get('credential')) ?>
</label>
<?php if ($this->redirect): ?>
<input type="hidden" name="redirect" value="<?php echo $this->redirect ?>"/>
<?php endif ?>
<button type="submit" name="submit" value="" class="btn btn-success">Войти</button>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a
        href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
