<?php
$this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
?>

<h1><?php echo $this->translate('Sign In'); ?></h1>
<?php
$form = $this->loginForm;
$formType = $this->formType;
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$displayOptions = array(
    'class' => 'form-horizontal',
);
if ($this->redirect) {
    $form->add(array(
        'name' => 'redirect',
        'type' => 'Zend\Form\Element\Hidden',
        'attributes' => array(
            'value' => $this->escapeHtml($this->redirect),
        ),
    ));
}
foreach ($form as $element) {
    if ($element instanceof Zend\Form\Element\Button) {
        $element->setValue($this->translate('Sign In'));
    }
    $label = $element->getLabel();
    if ($label != '') {
        $element->setLabel($this->translate($label));
    }
}
$form->prepare();
?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a
        href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
