<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">LEG form</li>
</ul>
<?php
$title = 'Remove LEG';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure you want to delete?</p>
<?php
$url = $this->url('leg', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$leg->id; ?>"/>
        <input type="hidden" name="referer" value="<?php echo $this->referer; ?>"/>
        <input type="submit" name="del" value="Yes" class="btn btn-warning"/>
        <input type="submit" name="del" value="No" class="btn btn-link" onclick="history.go(-1);"/>
    </div>
</form>
