<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->refNumberOrder)); ?>"><?= $this->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">LEG form</li>
</ul>
<?php
$title = 'Edit LEG';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'elements' => array(
        'dateOfFlight' => array(
            'required' => true,
            'class' => 'span2',
        ),
    ),
    'fieldsets' => array(
        'flightNumber' => array(
            'display_legend' => true,
            'elements' => array(
                'flightNumberAirportId' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
                'flightNumberText' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
            ),
        ),
        'apDep' => array(
            'display_legend' => true,
            'elements' => array(
                'apDepCountries' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
                'apDepAirports' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
                'apDepTime' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
            ),
        ),
        'apArr' => array(
            'display_legend' => true,
            'elements' => array(
                'apArrCountries' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
                'apArrAirports' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
                'apArrTime' => array(
                    'required' => true,
                    'class' => 'span8',
                ),
            ),
        ),
    ),
);
//$formType = 'inline';
$form = $this->form;
$form->setAttribute('action', $this->url('leg', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>

<?php echo $this->partial('widgets/tables/leg.phtml', array('legs' => $legs, 'status' => $headerStatus)); ?>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php
$flightNumber = $form->get('flightNumber');
$apDep = $form->get('apDep');
$apArr = $form->get('apArr');

echo $this->formTwb()->openTag($form, $formType);
echo $this->formRowTwb($form->get('dateOfFlight'), $formType, $displayOptions['elements']['dateOfFlight']);

?>

<div class="row-fluid">
    <div class="span4">
        <?php
        echo $this->formFieldsetTwb()->openTag($flightNumber, $formType, $displayOptions['fieldsets']['flightNumber'], true, true, true);
        echo $this->formRowTwb($flightNumber->get('flightNumberAirportId'), $formType, $displayOptions['fieldsets']['flightNumber']['elements']['flightNumberAirportId']);
        echo $this->formRowTwb($flightNumber->get('flightNumberText'), $formType, $displayOptions['fieldsets']['flightNumber']['elements']['flightNumberText']);
        echo $this->formFieldsetTwb()->closeTag();
        ?>
    </div>
    <div class="span4">
        <?php
        echo $this->formFieldsetTwb()->openTag($apDep, $formType, $displayOptions['fieldsets']['apDep']);
        echo $this->formRowTwb($apDep->get('apDepCountries'), $formType, $displayOptions['fieldsets']['apDep']['elements']['apDepCountries']);
        echo $this->formRowTwb($apDep->get('apDepAirports'), $formType, $displayOptions['fieldsets']['apDep']['elements']['apDepAirports']);
        echo $this->formRowTwb($apDep->get('apDepTime'), $formType, $displayOptions['fieldsets']['apDep']['elements']['apDepTime']);
        echo $this->formFieldsetTwb()->closeTag();
        ?>
    </div>
    <div class="span4">
        <?php
        echo $this->formFieldsetTwb()->openTag($apArr, $formType, $displayOptions['fieldsets']['apArr']);
        echo $this->formRowTwb($apArr->get('apArrCountries'), $formType, $displayOptions['fieldsets']['apArr']['elements']['apArrCountries']);
        echo $this->formRowTwb($apArr->get('apArrAirports'), $formType, $displayOptions['fieldsets']['apArr']['elements']['apArrAirports']);
        echo $this->formRowTwb($apArr->get('apArrTime'), $formType, $displayOptions['fieldsets']['apArr']['elements']['apArrTime']);
        echo $this->formFieldsetTwb()->closeTag();
        ?>
    </div>
</div>

<?php

echo $this->formRowTwb($form->get('csrf'));
$actions = array(
    $form->get('submitBtn'),
);
?>
<div class="form-actions">
    <?= $this->formActionsTwb($actions, $formType); ?>
</div>

<?php
echo $this->formRowTwb($form->get('id'));
echo $this->formRowTwb($form->get('headerId'));
echo $this->formRowTwb($form->get('previousDate'));
echo $this->formRowTwb($form->get('preSelectedApDepCountryId'));
echo $this->formRowTwb($form->get('preSelectedApDepAirportId'));
echo $this->formRowTwb($form->get('apDepAirportId'));
echo $this->formRowTwb($form->get('apArrAirportId'));
echo $this->formTwb()->closeTag();
