<?php
$title = 'Edit LEG';
$this->headTitle($title);
//\Zend\Debug\Debug::dump($this->header);
?>
    <ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">LEG form</li>
</ul>

<?=
$this->partial('fc-flight/_widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
        'currentId' => $this->id,
    )
)
?>

    <h1><?= $title ?></h1>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>
<div id="leg">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('leg', array('action' => 'edit', 'id' => $this->id)));
    $form->prepare();
    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('previousDate')) . PHP_EOL;
    echo $this->formHidden($form->get('preSelectedAirOperatorId')) . PHP_EOL;
    echo $this->formHidden($form->get('preSelectedApDepCountryId')) . PHP_EOL;
    echo $this->formHidden($form->get('preSelectedApDepAirportId')) . PHP_EOL;
    echo $this->formHidden($form->get('apDepAirportId')) . PHP_EOL;
    echo $this->formHidden($form->get('apArrAirportId')) . PHP_EOL;
    ?>

    <table class="table">
        <thead>
        <tr>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Dep Date</th>
            <th>Country Dep</th>
            <th>Airport Dep</th>
            <th>Arr Date</th>
            <th>Country Arr</th>
            <th>Airport Arr</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                $field = $form->get('airOperatorId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('flightNumber');
                echo $this->formInput($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td class="apDepTime">
                <?php
                $field = $form->get('apDepTime');
                echo $this->formInput($field);
                echo '<p class="help-block">' . $field->getOption('description') . '</p>';
                echo '<p class="help-block">' . $field->getOption('hint') . '</p>';
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('apDepCountryId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('apDepAirports');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td class="apArrTime">
                <?php
                $field = $form->get('apArrTime');
                echo $this->formInput($field);
                echo '<p class="help-block">' . $field->getOption('description') . '</p>';
                echo '<p class="help-block">' . $field->getOption('hint') . '</p>';
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('apArrCountryId');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('apArrAirports');
                echo $this->formSelect($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
