<?php
$title = 'Add Refuel';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Type of service: Refuel</li>
</ul>

<?=
$this->partial('widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
    )
)
?>

<h1><?= $title ?></h1>

<?php if ($this->form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?= $this->flashMessenger()->render('success', array('alert', 'alert-success')) ?>
<?php endif ?>
<div class="alert alert-info">
    <strong>Warning!</strong> Page in development.
</div>
<div id="refuel">
    <?=
    $this->partial('widgets/tables/refuel.phtml',
        array(
            'refuels' => $this->refuels,
            'status' => $this->header->status,
            'fixedHeader' => true,
        )) ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('refuel', array('action' => 'add', 'id' => $this->header->id)));
    $form->prepare();
    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('previousDate')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>

    <table class="table ">
        <tr>
            <td>
                <?php
                $field = $form->get('agentId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('legId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('quantity');
                echo $this->formInput($field);
                echo '<p class="help-block" id="help-dateOrder">Под этим полем будет пересчитанное значение!<br />Или добавить поле ввода readonly? Пересчитываем оба поля!</p>';
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('unitId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('price');
                echo $this->formInput($field);
                echo '<p class="help-block" id="help-dateOrder">Под этим полем будет Total (quantity*price)!<br />Или добавить поле ввода readonly?</p>';
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('date');
                echo $field->getOption('label');
                echo $this->formInput($field);
                echo '<p class="help-block" id="help-dateOrder">' . $field->getOption('description'). '<br />Говорили да забылось.<br />Это выпадающий список?<br />Можешь показать конкретный пример значений на любом полете? К примеру: http://fcontrol.rapvokzal.com/refuel/add/43. Подставить из лега, но с возможностью редактировать!</p>';
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
