<?php
$title = 'Remove Refuel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure you want to delete?</p>
<?php
$url = $this->url('refuel', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$data->id; ?>"/>
        <input type="submit" name="del" value="Yes" class="btn btn-warning"/>
        <input type="submit" name="del" value="No" class="btn btn-link" onclick="history.go(-1);"/>
    </div>
</form>
