<?php
$title = 'Edit Refuel';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?= $this->url('browse', array('action' => 'show', 'refNumberOrder' => $this->header->refNumberOrder)); ?>"><?= $this->header->refNumberOrder ?></a>
        <span class="divider">/</span>
    </li>
    <li class="active">Type of service: Refuel</li>
</ul>

<?=
$this->partial('fc-flight/_widgets/components/flight.phtml',
    array(
        'header' => $this->header,
        'legs' => $this->legs,
    )
)
?>

<h1><?= $title ?></h1>

<?php if ($this->form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<div id="refuel">
    <?=
    $this->partial('fc-flight/_widgets/tables/refuel.phtml', array(
        'currentId' => $this->id,
        'refuels' => $this->refuels,
        'refuelsTotal' => $this->refuelsTotal,
        'status' => $this->header->status,
        'fixedHeader' => true,
    )) ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('refuel', array('action' => 'edit', 'id' => $this->id)));
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
    echo $this->formHidden($form->get('id')) . PHP_EOL;
    echo $this->formHidden($form->get('headerId')) . PHP_EOL;
    echo $this->formHidden($form->get('csrf')) . PHP_EOL;
    ?>

    <table class="table ">
        <thead>
        <tr>
            <th>Airport</th>
            <th>Date</th>
            <th>Agent</th>
            <th>Quantity, LTR</th>
            <th>Quantity in Selected Units</th>
            <th>Unit</th>
            <th>Price, USD</th>
            <th>Total, USD</th>
            <th>Status</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                $field = $form->get('airportId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('date');
                echo $field->getOption('label');
                echo $this->formInput($field);
                echo '<p class="help-block" id="help-dateOrder">' . $field->getOption('description') . '</p>';
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('agentId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('quantityLtr');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('quantityOtherUnits');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('unitId');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('priceUsd');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('totalPriceUsd');
                echo $this->formInput($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('status');
                echo $this->formCheckbox($field);
                ?>
                <ul class="errors"><?= $this->formElementErrors($field) ?></ul>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
