<table class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead class="header">
    <tr>
        <th>
            Ref Number
        </th>
        <th>
            Date Order
        </th>
        <th>
            Customer
        </th>
        <th>
            Air Operator
        </th>
        <th>
            Aircraft
        </th>
        <th>Refuel</th>
        <th>Permit</th>
        <th>AP Service</th>
        <th class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data as $row) : ?>
        <?php
        //\Zend\Debug\Debug::dump($row);
        $class = '';
        switch ($row['status']) {
            case -1:
                $class = 'warning statusDraft';
                break;
            case 0:
                $class = 'success statusDone';
                break;
            case 1:
                $class = 'info statusActive';
                break;
            default:
                $class = '';
                break;
        }
        ?>
        <tr class="<?= $class ?>">
            <td>
                <a href="<?php
                echo $this->url('browse',
                    array('refNumberOrder' => urlencode($row['refNumberOrder'])));?>">
                    <strong><?php echo $this->escapeHtml($row['refNumberOrder']); ?></strong>
                </a>
            </td>
            <td><strong><?php echo date('d-m-Y', $row['dateOrder']); ?></strong></td>
            <td><?php echo $this->escapeHtml($row['kontragentShortName']); ?></td>
            <td><?php echo $this->escapeHtml($row['airOperatorShortName']); ?></td>
            <td>
                <?php
                $aircraft = $this->escapeHtml($row['aircraftTypeName'])
                    . ' (' . $this->escapeHtml($row['aircraftName']) . ')';
                if ($row['alternativeAircraftTypeName1']
                    && $row['alternativeAircraftName1']) {
                    $aircraft .= '<br /><small>'
                        . $this->escapeHtml($row['alternativeAircraftTypeName1'])
                        . ' (' . $this->escapeHtml($row['alternativeAircraftName1']) . ')</small>';
                }
                if ($row['alternativeAircraftTypeName2']
                    && $row['alternativeAircraftName2']) {
                    $aircraft .= '<br /><small>'
                        . $this->escapeHtml($row['alternativeAircraftTypeName2'])
                        . ' (' . $this->escapeHtml($row['alternativeAircraftName2']) . ')</small>';
                }
                ?>
                <?= $aircraft ?>
            </td>
            <td>
                <?php
                $class = '';
                switch ($row['refuelStatus']) {
                    case 'YES':
                        $class = 'statusYes';
                        break;
                    case 'NO':
                        $class = 'statusNo';
                        break;
                    case 'CNFMD':
                        $class = 'statusCNFMD';
                        break;
                    default:
                        $class = 'statusDone';
                        break;
                }
                ?>
                <span class="<?= $class; ?>"><?= $row['refuelStatus']; ?></span>
            </td>
            <td>
                <?php
                $class = '';
                switch ($row['permitStatus']) {
                    case 'YES':
                        $class = 'statusYes';
                        break;
                    case 'NO':
                        $class = 'statusNo';
                        break;
                    case 'CNFMD':
                        $class = 'statusCNFMD';
                        break;
                    default:
                        $class = 'statusDone';
                        break;
                }
                ?>
                <span class="<?= $class; ?>"><?= $row['permitStatus']; ?></span>
            </td>
            <td>
                <?php
                $class = '';
                switch ($row['apServiceStatus']) {
                    case 'YES':
                        $class = 'statusYes';
                        break;
                    case 'NO':
                        $class = 'statusNo';
                        break;
                    case 'CNFMD':
                        $class = 'statusCNFMD';
                        break;
                    default:
                        $class = 'statusDone';
                        break;
                }
                ?>
                <span class="<?= $class; ?>"><?= $row['apServiceStatus']; ?></span>
            </td>

            <td class="actions">
                <a title="Edit" href="<?php echo $this->url('flight',
                    array('action' => 'edit-header', 'id' => $row['id']));?>"><i class="icon-edit"></i></a>
                <a title="Remove" href="<?php echo $this->url('flight',
                    array('action' => 'delete-header', 'id' => $row['id']));?>"><i class="icon-remove"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>