<h3>Изменение пароля для <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Пароль успешно изменен.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Не удается обновить пароль. Пожалуйста, попробуйте еще раз.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><label for="credential">Текущий пароль</label></dt>
<dd><?php
echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
?></dd>

<dt><label for="newCredential">Новый пароль</label></dt>
<dd><?php
echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
?></dd>

<dt><label for="newCredentialVerify">Повторите новый пароль</label></dt>
<dd><?php
echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
?></dd>

<dd><input name="submit" type="submit" value="Отправить"></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>
