<h1>Вход</h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formElementErrors($form->get('identity')) ?>
<label>
    <span>Email</span>
    <?php echo $this->formInput($form->get('identity')) ?>
</label>
<label>
    <span>Пароль</span>
    <?php echo $this->formInput($form->get('credential')) ?>
</label>
<?php if ($this->redirect): ?>
<input type="hidden" name="redirect" value="<?php echo $this->redirect ?>"/>
<?php endif ?>
<input type="submit" value="Добавить" class="btn btn-success" id="submitbutton" name="submit">

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
Не зарегистрированы? <a
        href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>">Регистрация!</a>
<?php endif; ?>
