<?php
$title = 'Show Permission income invoice';
$this->headTitle($title);
?>
    <ul class="breadcrumb">
        <li><a href="/">Home</a> <span class="divider">/</span></li>
        <li>Management <span class="divider">/</span></li>
        <li>Permission income invoice<span class="divider">/</span></li>
        <li><?= $this->header->incomeInvoiceMainNumber ?></li>
    </ul>

    <h1><?= $title ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-error')); ?>
<? \Zend\Debug\Debug::dump($this->header) ?>
    <table id="invoiceHeader" class="table-bordered table-condensed">
        <thead>
        <tr>
            <th>Invoice #</th>
            <th>Date</th>
            <th>Currency</th>
            <th>Exchange Rate</th>
            <th>Agent</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?= $this->header->incomeInvoiceMainNumber ?>
            </td>
            <td>
                <?= date('d-m-Y', $this->header->incomeInvoiceMainDate) ?>
            </td>
            <td>
                <?= $this->header->incomeInvoiceMainCurrency ?>
            </td>
            <td>
                <?= $this->header->incomeInvoiceMainExchangeRate ?>
            </td>
            <td>
                <?= $this->header->invoiceAgentShortName ?>
            </td>
        </tr>
        </tbody>
    </table>
    <br/>
<?=
$this->partial('fc-flight-management/_widgets/tables/permission-income-invoice.phtml',
    array(
        'header' => $this->header,
    )
)
?>