<?php
$title = 'Show Permission outcome invoice';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>Management <span class="divider">/</span></li>
    <li>Permission outcome invoice<span class="divider">/</span></li>
    <li><?= $this->header->outcomeInvoiceMainNumber ?></li>
</ul>

<h1><?= $title ?></h1>

<table id="invoiceMain" class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ORD #</th>
        <th>Invoice #</th>
        <th>Date</th>
        <th>Currency</th>
        <th>Exchange Rate</th>
        <th>Agent</th>
        <th colspan="2">Type of service</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td>
            test
        </td>
        <td>
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td colspan="2">
            test
        </td>
    </tr>
    </tbody>
    <thead>
    <tr>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Arr</th>
        <th>Airport Dep</th>
        <th>Date Arr</th>
        <th>Date Dep</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td rowspan="2">
            test
        </td>
        <td>
            test
        </td>
        <td>
            test
        </td>
    </tr>
    </tbody>
</table>
<br/>
