<style>
    th, td {
        /*border: 1px solid #000000;*/
    }

    th {
        font-weight: bold;
    }
    .table-bordered {
        border: 1px solid #dddddd;
        border-collapse: separate;
        border-left: 0;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
    }
    .table {
        width: 100%;
        margin-bottom: 15px;
    }
    table {
        max-width: 100%;
        background-color: transparent;
        border-collapse: collapse;
        border-spacing: 0;
    }
    body {
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 12px;
        line-height: 15px;
        color: #333333;
    }
    thead {
        background-color: #eaeaea;
    }

</style>

<div class="header">
    <strong>Invoice #:</strong> <?= $this->header->outcomeInvoiceMainNumber ?>
    <br/>
    <strong>Date:</strong> <?= $this->header->outcomeInvoiceMainDate ?>
    <br/>
    <strong>Due Date:</strong> <?= $this->header->dueDate ?>
    <br/>
    <strong>Customer:</strong> <?= $this->header->outcomeInvoiceMainCustomerName ?>
    <br/>
    <strong>Agreement:</strong> ???
    <br/>
    <strong>Type of service:</strong> Permission service
    <br/>
    <strong>Currency:</strong> <?= $this->header->outcomeInvoiceMainCurrency ?>
    <br/>
</div>
<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th>
            #
        </th>
        <th>
            Description
        </th>
        <th>
            Quantity
        </th>
        <th>
            Price per unit
        </th>
        <th>
            Total amount
        </th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->header->data as $item => $row): ?>
        <tr>
            <td>
                <?= $item + 1 ?>
            </td>
            <td>
                <strong>Country</strong> <?= $row->preInvoiceCountryName ?>
                <strong>Type perm</strong> <?= $row->preInvoiceTypeOfPermission ?>
                <strong>Airport Dep</strong> <?= $row->legAirportDepICAO ?> <?= $row->legAirportDepIATA ?>
                <strong>Airport Arr</strong> <?= $row->legAirportArrICAO ?> <?= $row->legAirportArrIATA ?>
                <strong>Date Dep</strong> <?= date('d-m-Y', $row->outcomeInvoiceDataDateDep) ?>
                <strong>Date Arr</strong> <?= date('d-m-Y', $row->outcomeInvoiceDataDateArr) ?>
                <br/>
                <strong>Flight #:</strong> <?= $row->outcomeInvoiceDataFlightNumber ?>
                <br/>
                <strong>Aircraft:</strong> <?= $row->outcomeInvoiceDataAircraftTypeName ?>
                (<?= $row->outcomeInvoiceDataAircraftName ?>)
            </td>
            <td>
                <?= $row->outcomeInvoiceDataQuantity ?>
            </td>
            <td>
                <?= number_format($row->outcomeInvoiceDataItemPrice, 2, '.', '') ?>
            </td>
            <td>
                <?= number_format($row->incomeInvoiceDataPriceTotal, 2, '.', '') ?>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
