<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                                       => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'                   => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Navigation\Service\fControlNavigationFactory' => __DIR__ . '/src/Application/Navigation/Service/fControlNavigationFactory.php',
    'Application\Service\ErrorHandling'                        => __DIR__ . '/src/Application/Service/ErrorHandling.php',
    'ApplicationTest\Controller\IndexControllerTest'           => __DIR__ . '/test/ApplicationTest/Controller/IndexControllerTest.php',
    'ApplicationTest\Bootstrap'                                => __DIR__ . '/test/Bootstrap.php',
);
