<?php
$title = 'Active Flights (In Process)';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>

<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Active Flights</li>
</ul>

<div class="row">
    <div class="span2 leftPanes">
        <?php echo $this->partial('widgets/search/default.phtml', array('form' => $searchForm)); ?>
    </div>
    <div class="span10 rightPanes">
        <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
        <div class="row">
            <div class="span2">
                <p>
                    <a href="<?php echo $this->url('flight', array('action' => 'add-header')); ?>"
                       class="btn btn-primary">Add Flight</a>
                </p>
            </div>

            <div class="span8">
                <h4>Active Flights (In Process)</h4>
            </div>
        </div>

        <?= $this->partial('widgets/tables/header.phtml', array(
            'data' => $data,
            'url_order' => $url_order,
            'order_by' => $order_by,
            'route' => $route,
            'fixedHeader' => true,
        )) ?>
    </div>
</div>

