<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Active Flights</li>
</ul>

<?php
$title = 'Active Flights (In Process)';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

<p>
    <a href="<?php echo $this->url('flight', array('action' => 'add-header')); ?>"
       class="btn btn-primary">Add Flight</a>
</p>

<?php echo $this->partial('widgets/tables/header.phtml', array(
    'data' => $data,
    'url_order' => $url_order,
    'order_by' => $order_by,
    'route' => $route,
)); ?>


