<?php
$title = 'Add Flight';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'elements' => array(
//        'dateOrder' => array(
//            'class' => 'input-small',
//        ),
//        'kontragent' => array(
//            'class' => 'input-small',
//            'required' => true,
//        ),
//        'airOperator' => array(
//            'class' => 'input-small',
//        ),
//        'aircraft' => array(
//            'class' => 'input-small',
//        ),
    ),
);
//$formType = 'inline';
$form = $this->form;
$form->setAttribute('action', $this->url('flight', array('action' => 'add-header')));
$form->prepare();
?>

<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Invalid input!</strong>
    Form fields are not filled in correctly.
</div>
<?php else: ?>
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>
