<?php
$title = 'Add Flight';
$this->headTitle($title);
?>
    <ul class="breadcrumb">
        <li><a href="/">Home</a> <span class="divider">/</span></li>
        <li class="active">Flight form</li>
    </ul>

    <h1><?= $title ?></h1>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('flight', array('action' => 'add-header')));
$form->prepare();
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('csrf')) . PHP_EOL;
?>

    <table class="table ">
        <thead>
        <tr>
            <td>Date Order</td>
            <td>Customer</td>
            <td>Air Operator</td>
            <td>Aircraft Type</td>
            <td>Status</td>
            <td colspan="2"></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                $field = $form->get('dateOrder');
                echo $this->formInput($field);
                echo '<p class="help-block" id="help-dateOrder">' . $field->getOption('description') . '</p>';
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('kontragent');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('airOperator');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('aircraft');
                echo $this->formSelect($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('status');
                echo $this->formCheckbox($field);
                echo $this->formElementErrors($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('submitBtn');
                echo $this->formElement($field);
                ?>
            </td>
            <td>
                <?php
                $field = $form->get('cancel');
                echo $this->formElement($field);
                ?>
            </td>
        </tr>
        </tbody>
    </table>
<?= $this->form()->closeTag() ?>
