<?php
$title = 'Add Data';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'fieldsets' => array(
        'flightNumber' => array(
            'display_legend' => true,
            'elements' => array(
                'flightNumberIcaoAndIata' => array(
                    'required' => true,
                ),
                'flightNumberText' => array(
                    'required' => true,
                ),
            ),
        ),
        'apDep' => array(
            'display_legend' => true,
            'elements' => array(
                'apDepIcaoAndIata' => array(
                    'required' => true,
                ),
                'apDepTime' => array(
                    'required' => true,
                ),
            ),
        ),
        'apArr' => array(
            'display_legend' => true,
            'elements' => array(
                'apArrIcaoAndIata' => array(
                    'required' => true,
                ),
                'apArrTime' => array(
                    'required' => true,
                ),
            ),
        ),
    ),
    'elements' => array(
        'dateOfFlight' => array(
            'required' => true,
        ),
        'submitBtn' => array(
            'class' => 'btn-large',
        ),
    ),
);
//$formType = 'inline';
$form = $this->form;
$form->setAttribute('action', $this->url('flight', array('action' => 'add-data', 'id' => $this->headerId)));
$form->prepare();
?>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>