<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Archived Flights</li>
</ul>

<?php
/**
 * @var $this FcFlight\Controller\FlightController
 */

$title = 'Archived Flights (Done)';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>

<div class="row">
    <div class="span2 leftPanes">
        <?php echo $this->partial('fc-flight/_widgets/search/default.phtml', array('form' => $searchForm)); ?>
    </div>
    <div class="span10 rightPanes">
        <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
        <div class="row">
            <div class="span2">
                <p>
                    <a href="<?php echo $this->url('flight', array('action' => 'add-header')); ?>"
                       class="btn btn-primary">Add Flight</a>
                </p>
            </div>

            <div class="span8">
                <h4>Active Flights (Done)</h4>
            </div>
        </div>

        <?= $this->partial('fc-flight/_widgets/tables/header.phtml', array(
            'data' => $data,
            'url_order' => $url_order,
            'order_by' => $order_by,
            'route' => $route,
            'fixedHeader' => true,
        )) ?>

        <?= $this->paginationControl(
            $pagination, 'Sliding', 'libraries-pagination-slide', array(
                'order_by' => $order_by,
                'order' => $order,
                'route' => $route,
            )
        )
        ?>
    </div>
</div>





