<?php
$title = 'Form: Flights';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

<p>
    <a href="<?php echo $this->url('flight', array('action' => 'add'));?>"
       class="btn btn-primary">Add Flight</a>
</p>

<table class="table table-bordered table-hover">
    <tr>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'refNumberOrder', 'order' => $url_order)); ?>">
                REF NUMBER ORDER
                <?php if ($order_by == 'refNumberOrder'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'dateOrder', 'order' => $url_order)); ?>">
                DATE ORDER
                <?php if ($order_by == 'dateOrder'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'kontragentShortName', 'order' => $url_order)); ?>">
                CUSTOMER
                <?php if ($order_by == 'kontragentShortName'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'airOperatorShortName', 'order' => $url_order)); ?>">
                AIR OPERATOR
                <?php if ($order_by == 'airOperatorShortName'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url($route, array('order_by' => 'aircraftType', 'order' => $url_order)); ?>">
                AIRCRAFT
                <?php if ($order_by == 'aircraftType'): ?>
                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                <?php endif; ?>
            </a>
        </th>
        <th>Actions</th>
    </tr>
    <?php foreach ($pagination as $row) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($row->refNumberOrder);?></td>
        <td><?php echo $this->escapeHtml($row->dateOrder);?></td>
        <td><?php echo $this->escapeHtml($row->kontragentShortName);?></td>
        <td><?php echo $this->escapeHtml($row->airOperatorShortName);?></td>
        <td>
            <?php echo $this->escapeHtml($row->aircraftType);?>
            <br />
            <small><?php echo $this->escapeHtml($row->aircraft);?></small>
        </td>
        <td>
            <a href="<?php echo $this->url('flight',
                array('action' => 'edit', 'id' => $row->id));?>" class="btn btn-success">Edit</a>
            <a href="<?php echo $this->url('flight',
                array('action' => 'delete', 'id' => $row->id));?>" class="btn btn-warning">Remove</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
    $pagination, 'Sliding', 'libraries-pagination-slide', array(
        'order_by' => $order_by,
        'order' => $order,
        'route' => $route,
    )
);
?>
