<?php
$title = 'Browse: Flight';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
    <ul class="nav nav-pills">
        <li>
            <a href="<?php echo $this->url('flight', array('action' => 'add-data', 'id' => $header->id)); ?>">Add Form 1</a>
        </li>
        <li class="disabled"><a href="#">Add Form 2</a></li>
        <li class="disabled"><a href="#">Add Form 3</a></li>
    </ul>
</div>
<table id="flightBrowse">
    <tr>
        <td>
            <table class="cHeader">
                <tr>
                    <th>Reg Number Order</th>
                    <td class="cRefNumberOrder"><?php echo $this->escapeHtml($header->refNumberOrder); ?></td>
                </tr>
                <tr>
                    <th>Date Order</th>
                    <td><?php echo date('Y-m-d', $header->dateOrder); ?></td>
                </tr>
                <tr>
                    <th>Customer</th>
                    <td><?php echo $this->escapeHtml($header->kontragentShortName); ?></td>
                </tr>
            </table>
        </td>
        <td>
            <table class="cHeader">
                <tr>
                    <th>Air Operator</th>
                    <td><?php echo $this->escapeHtml($header->airOperatorShortName); ?></td>
                </tr>
                <tr>
                    <th>Aircraft</th>
                    <td><?php echo $this->escapeHtml($header->aircraftType); ?>
                        (<?php echo $this->escapeHtml($header->aircraft); ?>)
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
