<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active"><?= $header->refNumberOrder ?></li>
</ul>
<?php
$title = 'Browse: Flight';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
    <ul class="nav nav-pills">
        <li class="disabled"><a href="#">Add service:</a></li>
        <li>
            <a href="<?php echo $this->url('flight', array('action' => 'add-data', 'id' => $header->id)); ?>">Data</a>
        </li>
        <li class="disabled"><a href="#">Refuel</a></li>
        <li class="disabled"><a href="#">Permission</a></li>
        <li class="disabled"><a href="#">Hotel</a></li>
        <li class="disabled"><a href="#">FPL/PPL/SLOT</a></li>
        <li class="disabled"><a href="#">Charter</a></li>
    </ul>
</div>
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<table id="flightBrowse">
    <tr>
        <td>
            <table class="cHeader">
                <tr>
                    <th>Reg Number Order</th>
                    <td class="cRefNumberOrder"><?php echo $this->escapeHtml($header->refNumberOrder); ?></td>
                </tr>
                <tr>
                    <th>Date Order</th>
                    <td><?php echo date('Y-m-d', $header->dateOrder); ?></td>
                </tr>
                <tr>
                    <th>Customer</th>
                    <td><?php echo $this->escapeHtml($header->kontragentShortName); ?></td>
                </tr>
            </table>
        </td>
        <td>
            <table class="cHeader">
                <tr>
                    <th>Air Operator</th>
                    <td><?php echo $this->escapeHtml($header->airOperatorShortName); ?></td>
                </tr>
                <tr>
                    <th>Aircraft</th>
                    <td><?php echo $this->escapeHtml($header->aircraftTypeName); ?>
                        (<?php echo $this->escapeHtml($header->aircraft); ?>)
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table class="table table-bordered table-hover">
    <tr>
        <th rowspan="2">
            Date of Flight
        </th>
        <th colspan="3">
            Flight Number
        </th>
        <th colspan="3">
            App Dep
        </th>
        <th colspan="3">
            Ap Arr
        </th>
        <th rowspan="2">Actions</th>
    </tr>
    <tr>

        <th>
            ICAO
        </th>
        <th>
            IATA
        </th>
        <th></th>
        <th>
            ICAO
        </th>
        <th>
            IATA
        </th>
        <th>
            Time, UTC
        </th>
        <th>
            ICAO
        </th>
        <th>
            IATA
        </th>
        <th>
            Time, UTC
        </th>
    </tr>
    <?php foreach ($data as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row['dateOfFlight']); ?></td>
            <td><?php echo $this->escapeHtml($row['flightNumberIcao']); ?></td>
            <td><?php echo $this->escapeHtml($row['flightNumberIata']); ?></td>
            <td><?php echo $this->escapeHtml($row['flightNumberText']); ?></td>
            <td><?php echo $this->escapeHtml($row['apDepIcao']); ?></td>
            <td><?php echo $this->escapeHtml($row['apDepIata']); ?></td>
            <td><?php echo $this->escapeHtml($row['apDepTime']); ?></td>
            <td><?php echo $this->escapeHtml($row['apArrIcao']); ?></td>
            <td><?php echo $this->escapeHtml($row['apArrIata']); ?></td>
            <td><?php echo $this->escapeHtml($row['apArrTime']); ?></td>
            <td>
                <!--<a href="<?php echo $this->url('flight',
                    array('action' => 'edit-data', 'id' => $row['id']));?>" class="btn">Edit</a>-->
                <a href="<?php echo $this->url('flight',
                    array('action' => 'delete-data', 'id' => $row['id']));?>" class="btn btn-warning">Remove</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>