<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'ZFTool',
        'ZendDeveloperTools',
        //'DluTwBootstrapDemo',
        'Application',
        'ZfcBase',
        'ZfcAdmin',
        'ZfcUser',
        'BjyAuthorize',
        //'RoleUserBridge',
        'BjyProfiler',
        'Album',
        'FcAdmin',
        //'ZfcUserAdmin',
        //'ZfcTwitterBootstrap',
        'FcLibraries',
        'DluTwBootstrap',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
    ),
    'translator' => array('locale' => 'ru_RU')
);
