<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?=$this->url('zfcadmin/users', array('action' => 'index'));?>">Users</a>
        <span class="divider">/</span>
    </li>
    <li class="active">Add form</li>
</ul>
<?php
$title = 'Add new employee';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'username' => array(
            'class' => 'username',
            'required' => true,
        ),
        'email' => array(
            'required' => true,
        ),
        'password' => array(
            'required' => true,
        ),
        'passwordVerify' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$formType = $this->formType;
$validData = $this->validData;
$form->setAttribute('action', $this->url('zfcadmin/user', array('action' => 'add')));
$form->prepare();
?>



<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Invalid input!</strong>
    Form fields are not filled in correctly.
</div>
<?php endif; ?>

<div class="row">
    <div class="span6">
        <?php echo $this->formTwb($form, $formType, $displayOptions); ?>
    </div>
    <div class="span6">
        <div class="alert alert-info">
            <h4>About user roles!</h4>
            <ul>
                <li><strong>User</strong> - has access only to the home page.</li>
                <li><strong>Manager</strong> - can add the main form of flights, as well as any sub forms.
                    Has access to the logs. Does not have access to the management of libraries and users.</li>
                <li><strong>Admin</strong> - has full access.</li>
            </ul>
        </div>
    </div>
</div>
