<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>
        <a href="<?=$this->url('zfcadmin/users', array('action' => 'index'));?>">Users</a>
        <span class="divider">/</span>
    </li>
    <li class="active">Edit form</li>
</ul>
<?php
$title = 'Editing staff member';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'username' => array(
            'class' => 'username',
            'required' => true,
        ),
        'email' => array(
            'required' => true,
        ),
        'password' => array(
            'required' => true,
        ),
        'passwordVerify' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$formType = $this->formType;
$validData = $this->validData;
$form->setAttribute('action', $this->url(
    'zfcadmin/user',
    array(
        'action' => 'edit',
        'id'     => $this->user_id,
    )
));
$form->prepare();
?>

<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Invalid input!</strong>
    Form fields are not filled in correctly.
</div>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>

