<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FcLibrariesSearch\Module' => __DIR__ . '/Module.php',
    'FcLibrariesSearch\Controller\SearchController' => __DIR__ . '/src/FcLibrariesSearch/Controller/SearchController.php',
    'FcLibrariesSearch\Filter\AdvancedSearchFilter' => __DIR__ . '/src/FcLibrariesSearch/Filter/AdvancedSearchFilter.php',
    'FcLibrariesSearch\Form\AdvancedSearchForm' => __DIR__ . '/src/FcLibrariesSearch/Form/AdvancedSearchForm.php',
    'FcLibrariesSearch\Model\SearchModel' => __DIR__ . '/src/FcLibrariesSearch/Model/SearchModel.php',
);
