<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FcLibrariesSearch\Controller\SearchController' => __DIR__ . '/src/FcLibrariesSearch/Controller/SearchController.php',
  'FcLibrariesSearch\Filter\AdvancedSearchFilter' => __DIR__ . '/src/FcLibrariesSearch/Filter/AdvancedSearchFilter.php',
  'FcLibrariesSearch\Filter\SearchFilter'         => __DIR__ . '/src/FcLibrariesSearch/Filter/SearchFilter.php',
  'FcLibrariesSearch\Form\AdvancedSearchForm'     => __DIR__ . '/src/FcLibrariesSearch/Form/AdvancedSearchForm.php',
  'FcLibrariesSearch\Form\SearchForm'             => __DIR__ . '/src/FcLibrariesSearch/Form/SearchForm.php',
  'FcLibrariesSearch\Model\SearchModel'           => __DIR__ . '/src/FcLibrariesSearch/Model/SearchModel.php',
  'FcLibrariesSearch\Module'                      => __DIR__ . '/Module.php',
);
