<table class="table table-bordered table-hover table-condensed">
    <tr>
        <th>
            Ref Number
        </th>
        <th>
            Date Order
        </th>
        <th>
            Customer
        </th>
        <th>
            Air Operator
        </th>
        <th>
            Aircraft
        </th>
        <th>Actions</th>
    </tr>
    <?php foreach ($data as $row) : ?>
        <tr class="<?= ($row->status) ? 'warning' : 'success'; ?>">
            <td>
                <a href="<?php
                echo $this->url('browse',
                    array('refNumberOrder' => urlencode($row->refNumberOrder)));?>">
                    <?php echo $this->escapeHtml($row->refNumberOrder); ?>
                </a>
            </td>
            <td><?php echo date('Y-m-d', $row->dateOrder); ?></td>
            <td><?php echo $this->escapeHtml($row->kontragentShortName); ?></td>
            <td><?php echo $this->escapeHtml($row->airOperatorShortName); ?></td>
            <td>
                <?php echo $this->escapeHtml($row->aircraftTypeName); ?>
                <br/>
                <small><?php echo $this->escapeHtml($row->aircraft); ?></small>
            </td>
            <td>
                <a title="Edit" href="<?php echo $this->url('flight',
                    array('action' => 'edit-header', 'id' => $row->id));?>"><i class="icon-edit"></i></a>
                <a title="Remove" href="<?php echo $this->url('flight',
                    array('action' => 'delete-header', 'id' => $row->id));?>"><i class="icon-remove"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>