<?php
$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
//$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.css');
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css', 'all');

//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css', 'all');
//Twitter Bootstrap responsive styles
//$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css', 'all');

$this->headLink()->appendStylesheet($basePath . '/lib/chosen/chosen.min.css', 'all');
$this->headLink()->appendStylesheet($basePath . '/lib/table-fixed-header/table-fixed-header.css', 'all');

//fControl style
$this->headLink()->appendStylesheet($basePath . '/css/style.css', 'all');
$this->headLink()->appendStylesheet($basePath . '/css/print.css', 'print');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.10.2.min.js');
//$this->inlineScript()->appendFile($basePath . '/js/bootstrap.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');
$this->inlineScript()->appendFile($basePath . '/lib/chosen/chosen.jquery.min.js');
$this->inlineScript()->appendFile($basePath . '/lib/table-fixed-header/table-fixed-header.js');
$this->inlineScript()->appendFile($basePath . '/js/jquery.maskedinput.min.js');
$this->inlineScript()->appendFile($basePath . '/js/fControlGlobal.js');
$this->inlineScript()->appendFile($basePath . '/js/fControlNav.js');
$this->inlineScript()->appendFile($basePath . '/js/fControlForms.js');
$this->inlineScript()->appendFile($basePath . '/js/fControlLibrariesForms.js');
$this->inlineScript()->appendFile($basePath . '/js/fControlFlightForm.js');

echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('fControl') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
</head>

<body style="padding-top: 60px; padding-bottom: 40px;">
<!-- NavBar -->
<?php
//Set up the brand link
$brandLink = new \Zend\Navigation\Page\Mvc();
$brandLink->setRoute('home');
$brandLink->setLabel('fControl (alfa)');
echo $this->navigation()->twbNavbar()->renderNavbar($this->navBar,
    null, null, $brandLink, null, true, false, true, true, true);
?>
<!-- /NavBar -->
<!-- UserBar -->
<div class="user_nav">
    <ul class="nav pull-right">
        <?php if ($this->zfcUserIdentity() !== false) { ?>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                <?php echo $this->ZfcUserDisplayName(); ?>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/user/change-password">Change Password</a></li>
                <li><a href="/user/change-email">Change Email</a></li>
                <li><a href="/user/logout">Sign Out</a></li>
            </ul>
        </li>

        <?php } else { ?>
        <li><a class="btn btn-link" href="/user/login">Sign in</a></li>
        <?php } ?>
    </ul>
</div>

<!-- /UserBar -->
<div class="container">


    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; C Air Chartering 2012-<?php echo date('Y');?>. <?php echo 'All rights reserved.' ?></p>

        <p>
            <small>Все ошибки просьба копировать,
                по возможности дублировать скриншотами - отправлять на
                <a href="mailto:ruslan.piskarev@gmail.com">ruslan.piskarev@gmail.com</a>.
            </small>
        </p>

        <table style='width:708px;height:60px;display:none;border:0;margin:0;padding:0;'>
            <tr><td valign='top'>
                    <center><script type='text/javascript'>
                            var _ubn=_ubn||{sid:Math.round((Math.random()*10000000)),data:[]};
                            (function(){var n=document.getElementsByTagName('script');
                                _ubn.data.push({user: 14611, format_id: 4, page: 1,
                                    pid: Math.round((Math.random()*10000000)),placeholder: n[n.length-1]});
                                if(!_ubn.code)(function() {var script = document.createElement('script');
                                    script.type = 'text/javascript'; _ubn.code= script.async = script.defer = true;
                                    script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'banner.kiev.ua/j/banner.js?'+_ubn.sid;
                                    n[0].parentNode.insertBefore(script,n[0]);})();})();
                        </script><br>
                </td>
                <td valign='top'>
                    <center><script type='text/javascript'>
                            var _ubn=_ubn||{sid:Math.round((Math.random()*10000000)),data:[]};
                            (function(){var n=document.getElementsByTagName('script');
                                _ubn.data.push({user: 14611, format_id: 1, page: 1,
                                    pid: Math.round((Math.random()*10000000)),placeholder: n[n.length-1]});
                                if(!_ubn.code)(function() {var script = document.createElement('script');
                                    script.type = 'text/javascript'; _ubn.code= script.async = script.defer = true;
                                    script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'banner.kiev.ua/j/banner.js?'+_ubn.sid;
                                    n[0].parentNode.insertBefore(script,n[0]);})();})();
                        </script><br>
                </td>
                <td valign='top'>
                    <center><script type='text/javascript'>
                            var _ubn=_ubn||{sid:Math.round((Math.random()*10000000)),data:[]};
                            (function(){var n=document.getElementsByTagName('script');
                                _ubn.data.push({user: 14611, format_id: 4, page: 1,
                                    pid: Math.round((Math.random()*10000000)),placeholder: n[n.length-1]});
                                if(!_ubn.code)(function() {var script = document.createElement('script');
                                    script.type = 'text/javascript'; _ubn.code= script.async = script.defer = true;
                                    script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'banner.kiev.ua/j/banner.js?'+_ubn.sid;
                                    n[0].parentNode.insertBefore(script,n[0]);})();})();
                        </script><br>
                </td></tr>
        </table>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript(); ?>

</body>
</html>
