<?php
$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css');
//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css');
//Twitter Bootstrap responsive styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');
//fControl style
$this->headLink()->appendStylesheet($basePath . '/css/style.css');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.9.1.min.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');
$this->inlineScript()->appendFile($basePath . '/js/fcontrol.js');

echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('fControl') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
</head>

<body style="padding-top: 60px; padding-bottom: 40px;">
<!-- NavBar -->
<?php
//Set up the brand link
$brandLink = new \Zend\Navigation\Page\Mvc();
$brandLink->setRoute('home');
$brandLink->setLabel('fControl (alfa)');
echo $this->navigation()->twbNavbar()->renderNavbar($this->navBar,
    null, null, $brandLink, null, true, false, true, true, true);
?>
<!-- /NavBar -->
<!-- UserBar -->
<div class="user_nav">
    <ul class="nav pull-right">
        <?php if ($this->zfcUserIdentity() !== false) { ?>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                <?php echo $this->ZfcUserDisplayName(); ?>
                (Admin)
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/user/change-password">Change Password</a></li>
                <li><a href="/user/change-email">Change Email</a></li>
                <li><a href="/user/logout">Sign Out</a></li>
            </ul>
        </li>

        <?php } else { ?>
    <li><a class="btn" href="/user/login">Sign in</a></li>
        <?php } ?>
    </ul>
</div>

<!-- /UserBar -->
<div class="container">


    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; C Air Chartering 2012-<?php echo date('Y');?>. <?php echo 'All rights reserved.' ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript(); ?>
</body>
</html>
