<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">fControl</a> (alfa)

        <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="active"><a href="/">Главная</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/album">Album</a></li>
                <li class=""><a href="<?php echo $this->url('admin/users') ?>">Управление пользователями</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="nav-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <div class="pull-right">
                <?php if ($this->zfcUserIdentity() !== false) { ?>
                <?php if ($this->isAllowed('admin') === true) { ?>
                    <ul class="nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/admin">Настройки</a></li>
                                <li><a href="/user/change-email">Больше..</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php } else { ?>
                    <ul class="nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Настройки <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/user/change-password">Изменить пароль</a></li>
                                <li><a href="/user/change-email">Изменить Email</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php } ?>

                <a class="btn" href="/user/logout">Выйти</a>
                <?php } else { ?>
                <a class="btn" href="/user/login">Войти</a>
                <!-- <a class="btn" href="/user/register">Register</a> -->
                <?php } ?>
            </div>

        </div>
        <!--/.nav-collapse -->
    </div>
</div>
