<?php
$title = 'Show AP Service outcome invoice';
$this->headTitle($title);
?>
    <ul class="breadcrumb">
        <li><a href="/">Home</a> <span class="divider">/</span></li>
        <li>Management <span class="divider">/</span></li>
        <li>AP Service outcome invoice<span class="divider">/</span></li>
        <li><?= $this->header->outcomeInvoiceMainNumber ?></li>
    </ul>

    <h1><?= $title ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-error')); ?>

    <table id="invoiceMain" class="table table-bordered table-hover table-condensed">
        <thead>
        <tr>
            <th>ORD #</th>
            <th>Invoice #</th>
            <th>Date</th>
            <th>Currency</th>
            <th>Exchange Rate</th>
            <th>Agent</th>
            <th>Type of service</th>
            <th>Bank</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <a href="<?=
                $this->url('browse',
                    array('refNumberOrder' => $this->header->flightRefNumberOrder));?>"
                   target="_blank">
                    <?= $this->header->flightRefNumberOrder ?>
                </a>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainNumber ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainDate ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainCurrency ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainExchangeRate ?>
            </td>
            <td>
                <?= $this->header->preInvoiceAgentShortName ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainTypeOfServiceName ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainBankName ?>
            </td>
        </tr>
        </tbody>
        <thead>
        <tr>
            <th>Customer</th>
            <th>Air Operator</th>
            <th>Flight #</th>
            <th>Aircraft</th>
            <th>Airport Arr</th>
            <th>Airport Dep</th>
            <th>Date Arr</th>
            <th>Date Dep</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?= $this->header->flightCustomerShortName ?>
            </td>
            <td>
                <?= $this->header->flightAirOperatorShortName ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceFlightNumber ?>
            </td>
            <td>
                <?= $this->header->flightAircraftTypeName ?> (<?= $this->header->flightAircraftName ?>)
            </td>
            <td>
                <?= $this->header->preInvoiceAirportICAO ?> (<?= $this->header->preInvoiceAirportIATA ?>)
            </td>
            <td>
                <?= $this->header->legDepToNextAirportICAO ?> (<?= $this->header->legDepToNextAirportIATA ?>)
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainDateArr ?>
            </td>
            <td>
                <?= $this->header->outcomeInvoiceMainDateDep ?>
            </td>
        </tr>
        </tbody>
    </table>
    <br/>
<?=
$this->partial('fc-flight-management/_widgets/tables/ap-service-outcome-invoice.phtml',
    array(
        'header' => $this->header,
    )
)
?>
<div>
    <a class="btn"
       href="/management/ap-service/outcome-invoice-print/<?= $this->header->outcomeInvoiceMainId ?>">Download INVOICE</a>
</div>
