<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                             => __DIR__ . '/Module.php',
    'Album\Controller\AlbumController'         => __DIR__ . '/src/Album/Controller/AlbumController.php',
    'Album\Entity\Album'                       => __DIR__ . '/src/Album/Entity/Album.php',
    'Album\Form\AlbumForm'                     => __DIR__ . '/src/Album/Form/AlbumForm.php',
    'Album\Model\Album'                        => __DIR__ . '/src/Album/Model/Album.php',
    'Album\Model\AlbumTable'                   => __DIR__ . '/src/Album/Model/AlbumTable.php',
    'AlbumTest\Controller\AlbumControllerTest' => __DIR__ . '/test/AlbumTest/Controller/AlbumControllerTest.php',
    'Album\Model\AlbumTableTest'               => __DIR__ . '/test/AlbumTest/Model/AlbumTableTest.php',
    'AlbumTest\Model\AlbumTest'                => __DIR__ . '/test/AlbumTest/Model/AlbumTest.php',
    'AlbumTest\Bootstrap'                      => __DIR__ . '/test/Bootstrap.php',
);
