<?php
//$this->plugin('translate')->setTranslatorTextDomain(__NAMESPACE__);
$title = 'Add region';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
);
$form = $this->form;
$formType = $this->formType;
$validData = $this->validData;
$form->setAttribute('action', $this->url('zfcadmin/region', array('action' => 'add')));
$form->prepare();
?>

<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Invalid input!</strong>
    Form fields are not filled in correctly.
</div>
<?php elseif ($validData):?>
<div class="alert alert-success">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Form data is valid!</strong>
    The following data has been received from the form.
</div>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>
