<?php
$title = 'Удалить регион';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы уверены что хотите удалить
    <strong>'<?php echo $this->escapeHtml($data->name); ?>'</strong>?
</p>
<?php
$url = $this->url('zfcadmin/region', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int)$data->id; ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" />
    <input type="submit" name="del" value="No" class="btn btn-link" />
</div>
</form>
