<?// \Zend\Debug\Debug::dump($this->header) ?>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>Description</th>
        <th>Price, <?= $this->header->outcomeInvoiceMainCurrency ?></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <?= $this->header->outcomeInvoiceMainCurrency ?></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->header->data as $i => $row): ?>
        <tr class="dataRow" data-rowid="<?= $i ?>">
            <td>
                <?= $row->outcomeInvoiceDataTypeOfServiceName ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataItemPrice ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataQuantity ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataUnitId ?>
            </td>
            <td>
                <?php
                $priceSubTotal += $row->outcomeInvoiceDataPriceTotal;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotal ?>
            </td>
            <td>
                <?php
                $priceSubTotalExchangedToUsd += $row->outcomeInvoiceDataPriceTotalExchangedToUsd;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotalExchangedToUsd ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="6">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->header->outcomeInvoiceMainCurrency ?></span>
                                <span class="priceSubTotal"><?= number_format($priceSubTotal, 4, '.', '') ?></span>
                            </td>
                            <td>
                                USD <span
                                    class="priceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
            <strong>Disbursement</strong><br/>
            <?= $this->header->disbursement ?> %
        </td>
        <td>
        </td>
        <td>
        </td>
        <td>
            <?= $this->header->disbursementTotal ?>
        </td>
        <td>
            <?= $this->header->disbursementTotalExchangedToUsd ?>
        </td>
    </tr>
    <? foreach ($this->header->subData as $i => $row): ?>
        <tr class="subDataRow" data-subrowid="<?= $i ?>">
            <td>
                <?= $row->outcomeInvoiceDataTypeOfServiceName ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataItemPrice ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataQuantity ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataUnitId ?>
            </td>
            <td>
                <?php
                $priceSubTotal += $row->outcomeInvoiceDataPriceTotal;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotal ?>
            </td>
            <td>
                <?php
                $priceSubTotalExchangedToUsd += $row->outcomeInvoiceDataPriceTotalExchangedToUsd;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotalExchangedToUsd ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="6">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->header->outcomeInvoiceMainCurrency ?></span>
                                <span class="subPriceSubTotal"><?=
                                number_format($priceSubTotal
                                    + $this->header->disbursementTotal, 4, '.', '') ?></span>
                            </td>
                            <td>
                                USD <span class="subPriceSubTotalExchangedToUsd"><?=
                                    number_format($priceSubTotalExchangedToUsd
                                        + $this->header->disbursementTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>
