<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
<thead>
<tr>
    <th>Description</th>
    <th>Price, <?= $this->data->currency ?></th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Total, <?= $this->data->currency ?></th>
    <th>Exchange Total, USD</th>
</tr>
</thead>
<tbody>
<? foreach ($this->data->data as $i => $row): ?>
    <tr class="dataRow" data-rowid="<?= $i ?>">
        <td>
            <select name="data[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <? if ($row['typeOfServiceId'] == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small itemPrice" name="data[<?= $i ?>][itemPrice]" maxlength="40"
                   required="required"
                   value="<?= $row['itemPrice'] ?>">
        </td>
        <td>
            <input type="text" class="input-small quantity" name="data[<?= $i ?>][quantity]" maxlength="40"
                   required="required"
                   value="<?= $row['quantity'] ?>">
        </td>
        <td>
            <select name="data[<?= $i ?>][unitId]" class="chosen input-large unitId"
                    data-placeholder="Unit"
                    required="required">
                <option value=""></option>
                <? foreach ($this->units as $key => $value): ?>
                    <? if ($row['unitId'] == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <?php
            $priceSubTotal += $row['priceTotal'];
            ?>
            <input type="text" class="input-small priceTotal" name="data[<?= $i ?>][priceTotal]" maxlength="40"
                   required="required"
                   value="<?= $row['priceTotal'] ?>">
        </td>
        <td>
            <?php
            $priceSubTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
            ?>
            <input type="text" class="input-small priceTotalExchangedToUsd"
                   name="data[<?= $i ?>][priceTotalExchangedToUsd]"
                   maxlength="40"
                   required="required"
                   value="<?= $row['priceTotalExchangedToUsd'] ?>">
        </td>
    </tr>
<? endforeach; ?>
<tr>
    <td colspan="6">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td>
                            <span class="currency"><?= $this->data->currency ?></span>
                            <span class="priceSubTotal"><?= number_format($priceSubTotal, 4, '.', '') ?></span>
                        </td>
                        <td>
                            USD <span class="priceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd, 2, '.', '') ?></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>
<tr>
    <td>
    </td>
    <td>
        <strong>Disbursement</strong><br/>
        <input type="text" class="input-small disbursement" name="disbursement" maxlength="40"
               required="required"
               value="<?= $this->data->disbursement ?>"> %
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
        <input type="text" class="input-small disbursementTotal" name="disbursementTotal" maxlength="40"
               required="required"
               value="<?= $this->data->disbursementTotal ?>">
    </td>
    <td>
        <input type="text" class="input-small disbursementTotalExchangedToUsd"
               name="disbursementTotalExchangedToUsd"
               maxlength="40"
               required="required"
               value="<?= $this->data->disbursementTotalExchangedToUsd ?>">
    </td>
</tr>
<? foreach ($this->data->subData as $i => $row): ?>
    <tr class="subDataRow" data-subrowid="<?= $i ?>">
        <td>
            <select name="subData[<?= $i ?>][typeOfServiceId]" class="chosen input-large typeOfServiceId"
                    data-placeholder="Type of Service"
                    required="required">
                <option value=""></option>
                <? foreach ($this->typeOfServices as $key => $value): ?>
                    <? if ($row['typeOfServiceId'] == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <input type="text" class="input-small itemPrice" name="subData[<?= $i ?>][itemPrice]" maxlength="40"
                   required="required"
                   value="<?= $row['itemPrice'] ?>">
        </td>
        <td>
            <input type="text" class="input-small quantity" name="subData[<?= $i ?>][quantity]" maxlength="40"
                   required="required"
                   value="<?= $row['quantity'] ?>">
        </td>
        <td>
            <select name="subData[<?= $i ?>][unitId]" class="chosen input-large unitId"
                    data-placeholder="Unit"
                    required="required">
                <option value=""></option>
                <? foreach ($this->units as $key => $value): ?>
                    <? if ($row['unitId'] == $key): ?>
                        <option value="<?= $key ?>" selected="selected"><?= $value ?></option>
                    <? else: ?>
                        <option value="<?= $key ?>"><?= $value ?></option>
                    <? endif; ?>
                <? endforeach; ?>
            </select>
        </td>
        <td>
            <?php
            $priceSubTotal += $row['priceTotal'];
            ?>
            <input type="text" class="input-small priceTotal" name="subData[<?= $i ?>][priceTotal]" maxlength="40"
                   required="required"
                   value="<?= $row['priceTotal'] ?>">
        </td>
        <td>
            <?php
            $priceSubTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
            ?>
            <input type="text" class="input-small priceTotalExchangedToUsd"
                   name="subData[<?= $i ?>][priceTotalExchangedToUsd]"
                   maxlength="40"
                   required="required"
                   value="<?= $row['priceTotalExchangedToUsd'] ?>">
        </td>
    </tr>
<? endforeach; ?>
<tr>
    <td colspan="6">
        <div class="row-fluid">
            <div class="span6">
            </div>
            <div class="span6">
                <table style="width: 300px; float: right" class="table table-bordered pull-right">
                    <tbody>
                    <tr>
                        <td>
                            Subtotal
                        </td>
                        <td>
                            <span class="currency"><?= $this->data->currency ?></span>
                            <span class="subPriceSubTotal"><?= number_format($priceSubTotal
                                    + $this->data->disbursementTotal, 4, '.', '') ?></span>
                        </td>
                        <td>
                            USD <span class="subPriceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd
                                    + $this->data->disbursementTotalExchangedToUsd, 2, '.', '') ?></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </td>
</tr>


<tr>
    <td colspan="18">
        <input name="submitBtn" type="submit" class="btn btn-primary pull-right" value="Save">
    </td>
</tr>
</tbody>
</table>
