<? // \Zend\Debug\Debug::dump($this->header) ?>
<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Income invoice #</th>
        <th>Agent</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency"><?= $this->header->outcomeInvoiceMainCurrency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->header->outcomeInvoiceMainCurrency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->header->data as $row): ?>
        <!--    --><? // \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row['outcomeInvoiceDataId'] ?>">
            <td class="noWrap">
                <a href="<?=
                $this->url('browse',
                    array('refNumberOrder' => $row->flightRefNumberOrder));?>"
                   target="_blank">
                    <?= $row->flightRefNumberOrder ?>
                </a>
            </td>
            <td>
                <a href="<?=
                $this->url('management/permission/income-invoice-show',
                    array('id' => $row->incomeInvoiceMainId));?>"
                   target="_blank">
                    <?= $row->incomeInvoiceMainNumber ?>
                </a>
            </td>
            <td>
                <?= $row->flightAgentShortName ?>
            </td>
            <td>
                <?= $row->flightAirOperatorShortName ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataFlightNumber ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataAircraftTypeName ?>
                <br>
                <small>(<?= $row->outcomeInvoiceDataAircraftName ?>)</small>
            </td>
            <td>
                <?= $row->legAirportDepICAO ?> (<?= $row->legAirportDepIATA ?>)
            </td>
            <td>
                <?= date('d-m-Y', $row->outcomeInvoiceDataDateDep) ?>
            </td>
            <td>
                <?= $row->legAirportArrICAO ?> (<?= $row->legAirportArrIATA ?>)
            </td>
            <td>
                <?= date('d-m-Y', $row->outcomeInvoiceDataDateArr) ?>
            </td>
            <td>
                <?= $row->preInvoiceCountryName ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataTypeOfPermission ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataItemPrice ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataQuantity ?>
            </td>
            <td>
                <?= $row->outcomeInvoiceDataUnitName ?>
            </td>
            <td>
                <?php
                $priceSubTotal += $row->outcomeInvoiceDataPriceTotal;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotal ?>
            </td>
            <td>
                <?php
                $priceSubTotalExchangedToUsd += $row->outcomeInvoiceDataPriceTotalExchangedToUsd;
                ?>
                <?= $row->outcomeInvoiceDataPriceTotalExchangedToUsd ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="17">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->header->outcomeInvoiceMainCurrency ?></span>
                                <span class="priceSubTotal"><?= number_format($priceSubTotal, 2, '.', '') ?></span>
                            </td>
                            <td>USD
                            <span
                                class="priceSubTotalExchangedToUsd"><?= number_format($priceSubTotalExchangedToUsd, 2, '.', '') ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>
