<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->header->data as $row): ?>
<!--        --><?// \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row['incomeInvoiceDataId'] ?>">
            <td class="noWrap">
                <a href="<?=
                $this->url('browse',
                    array('refNumberOrder' => $row['flightRefNumberOrder']));?>"
                   target="_blank">
                    <?= $row['flightRefNumberOrder'] ?>
                </a>
            </td>
            <td>
                <?= $row['flightCustomerShortName'] ?>
            </td>
            <td>
                <?= $row['flightAirOperatorICAO'] ?> (<?= $row['flightAirOperatorIATA'] ?>)
            </td>
            <td>
                <?= $row['incomeInvoiceDataFlightNumber'] ?>
            </td>
            <td>
                <?= $row['incomeInvoiceDataAircraftTypeName'] ?> (<?= $row['incomeInvoiceDataAircraftName'] ?>)
            </td>
            <td>
                <?= $row['legAirportDepICAO'] ?> (<?= $row['legAirportDepIATA'] ?>)
            </td>
            <td>
                <?= date('d-m-Y', $row['incomeInvoiceDataDateDep']) ?>
            </td>
            <td>
                <?= $row['legAirportArrICAO'] ?> (<?= $row['legAirportArrIATA'] ?>)
            </td>
            <td>
                <?= date('d-m-Y', $row['incomeInvoiceDataDateArr']) ?>
            </td>
            <td>
                <?= $row['preInvoiceCountryName'] ?>
            </td>
            <td>
                <?= $row['incomeInvoiceDataTypeOfPermission'] ?>
            </td>
            <td>
                <?= number_format($row['incomeInvoiceDataItemPrice'], 2, '.', '') ?>
            </td>
            <td>
                <?= $row['incomeInvoiceDataQuantity'] ?>
            </td>
            <td>
                <?= $row['incomeInvoiceDataUnitName'] ?>
            </td>
            <td>
                <?php
                $priceTotal += $row['incomeInvoiceDataPriceTotal'];
                ?>
                <?= number_format($row['incomeInvoiceDataPriceTotal'], 2, '.', '') ?>
            </td>
            <td>
                <?php
                $priceTotalExchangedToUsd += $row['incomeInvoiceDataPriceTotalExchangedToUsd'];
                ?>
                <?= number_format($row['incomeInvoiceDataPriceTotalExchangedToUsd'], 2, '.', '') ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="16">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span>
                                <span class="priceSubTotal">
                                    <?= number_format($priceTotal, 2, '.', '') ?>
                                </span>
                            </td>
                            <td>
                                USD <span class="priceSubTotalExchangedToUsd">
                                    <?= number_format($priceTotalExchangedToUsd, 2, '.', '') ?>
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>