<table id="invoiceData"
       class="table table-bordered table-hover table-condensed <? if ($this->fixedHeader): ?> table-fixed-header<? endif ?>">
    <thead>
    <tr>
        <th>ORD</th>
        <th>Customer</th>
        <th>Air Operator</th>
        <th>Flight #</th>
        <th>Aircraft</th>
        <th>Airport Dep</th>
        <th>Date Dep</th>
        <th>Airport Arr</th>
        <th>Date Arr</th>
        <th>Country</th>
        <th>Permission number</th>
        <th>Price, <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span></th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Total, <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span></th>
        <th>Exchange Total, USD</th>
    </tr>
    </thead>
    <tbody>
    <? foreach ($this->header->data as $row): ?>
<!--        --><?// \Zend\Debug\Debug::dump($row) ?>
        <tr id="invoiceId_<?= $row['incomeInvoiceDataId'] ?>">
            <td class="noWrap">
                <?= $row['flightRefNumberOrder'] ?>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
                <?php
                $priceTotal += $row['priceTotal'];
                ?>
            </td>
            <td>
                <?php
                $priceTotalExchangedToUsd += $row['priceTotalExchangedToUsd'];
                ?>
            </td>
        </tr>
    <? endforeach; ?>
    <tr>
        <td colspan="16">
            <div class="row-fluid">
                <div class="span6">
                </div>
                <div class="span6">
                    <table style="width: 300px; float: right" class="table table-bordered pull-right">
                        <tbody>
                        <tr>
                            <td>
                                Subtotal
                            </td>
                            <td>
                                <span class="currency"><?= $this->header->incomeInvoiceMainCurrency ?></span>
                                <span class="priceSubTotal"><?= $priceTotal ?></span>
                            </td>
                            <td>
                                USD <span class="priceSubTotalExchangedToUsd"><?= $priceTotalExchangedToUsd ?></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>