<?php
$legsCount = count($this->legs);
$canBeChangedStatus = false;
$canBeCloned = false;
$canBeEdited = false;
$canBeEdited = false;
$canAddLeg = false;
$canAddServices = false;

if (($this->header->status == '-1' && $legsCount > 0) || $this->header->status == 1) {
    $canBeChangedStatus = true;
}

if ($this->header->status != '-1') {
    $canBeCloned = true;
}

if ($this->header->status == '-1') {
    $canBeEdited = true;
}

if ($this->header->status == '-1') {
    $canAddLeg = true;
}

if ($this->header->status == '-1' && $legsCount > 0) {
    $canAddServices = true;
}

?>
<?// \Zend\Debug\Debug::dump($this->header) ?>
<div id="header">
    <div class="flightAuthor">
        <span class="label label-inverse">Author: <?= $this->header->authorName ?></span>
    </div>
    <table id="flightBrowse">
        <tr>
            <td>
                <table class="cHeader table">
                    <tr>
                        <th>Reg Number Order</th>
                        <td class="cRefNumberOrder">
                            <?= $this->header->refNumberOrder ?>
                            <? if ($this->header->parentRefNumberOrder): ?>
                                <?=
                                ' <small>(<a href="' .
                                $this->url('browse',
                                    array('action' => 'show', 'refNumberOrder' => $this->header->parentRefNumberOrder))
                                . '">' . $this->header->parentRefNumberOrder . '</a>)</small>' ?>
                            <? endif ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Air Operator</th>
                        <td><?= $this->escapeHtml($this->header->airOperatorShortName) ?></td>
                    </tr>
                </table>
            </td>
            <td>
                <table class="cHeader table">
                    <tr>
                        <th>Date Order</th>
                        <td><?= $this->header->dateOrder ?></td>
                    </tr>
                    <tr>
                        <th>Aircraft</th>
                        <td>
                            <?php
                            $aircraft = $this->escapeHtml($this->header->aircraftTypeName)
                                . ' (' . $this->escapeHtml($this->header->aircraftName) . ')';
                            if ($this->header->alternativeAircraftTypeName1
                                && $this->header->alternativeAircraftName1
                            ) {
                                $aircraft .= '<br /><small>'
                                    . $this->escapeHtml($this->header->alternativeAircraftTypeName1)
                                    . ' (' . $this->escapeHtml($this->header->alternativeAircraftName1) . ')</small>';
                            }
                            if ($this->header->alternativeAircraftTypeName2
                                && $this->header->alternativeAircraftName2
                            ) {
                                $aircraft .= '<br /><small>'
                                    . $this->escapeHtml($this->header->alternativeAircraftTypeName2)
                                    . ' (' . $this->escapeHtml($this->header->alternativeAircraftName2) . ')</small>';
                            }
                            ?>
                            <?= $aircraft ?>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <table class="cHeader table">
                    <tr>
                        <th>Customer</th>
                        <td><?= $this->escapeHtml($this->header->kontragentShortName) ?></td>
                    </tr>
                    <tr>
                        <?php
                        $class = $status = $nextStatus = '';
                        switch ($this->header->status) {
                            case -1:
                                $class = 'warning statusDraft';
                                $status = 'Draft';
                                $nextStatus = 'In Process';
                                break;
                            case 1:
                                $class = 'info statusActive ';
                                $status = 'In Process';
                                $nextStatus = 'Done';
                                break;
                            case 0:
                                $class = 'success statusDone ';
                                $status = 'Done';
                                break;
                            default:
                                $class = '';
                                break;
                        }
                        ?>

                    <tr class="<?= $class ?>">
                        <th>Status</th>
                        <td><?= $status ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <div id="switchStatus" class="modal hide fade" tabindex="-1" role="dialog"
         aria-labelledby="switchStatusLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="switchStatusLabel">Change status warring</h3>
        </div>
        <div class="modal-body">
            <p>
                ARE YOU COMPLETELY SURE TO CHANGE STATUS
                <? if ($nextStatus): print 'to "<strong>' . $nextStatus . '</strong>"'; endif; ?>
                FOR FLIGHT<br/><b><?= $this->header->refNumberOrder ?></b>?
            </p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <a class="btn btn-<?= $class ?>"
               href="<?= $this->url('flight', array('action' => 'status-header', 'id' => $this->header->id)) ?>">
                Change status</a>
        </div>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            <div style="float: left; color: #999; font-size:12px; font-weight:bold; margin: 5px 10px 5px 0;">
                OPERATIONS
            </div>
            <a class="btn btn-<?= $class ?> <?= ($canBeChangedStatus) ? '' : 'disabled' ?>" href="#switchStatus" data-toggle="modal" role="button">
                <i class="icon-refresh"></i> Change status</a>
            <a class="btn btn-primary <?= ($canBeCloned) ? '' : 'disabled' ?>"
               href="<?= $this->url('flight', array('action' => 'clone-header', 'id' => $this->header->id)) ?>">
                <i class="icon-share"></i> Clone</a>
            <a class="btn btn-primary <?= ($canBeEdited) ? '' : 'disabled' ?>"
               href="<?= $this->url('flight', array('action' => 'edit-header', 'id' => $this->header->id)) ?>">
                <i class="icon-edit"></i> Edit</a>
        </div>
        <div class="btn-group">
            <div style="float: left; color: #999; font-size:12px; font-weight:bold; margin: 5px 10px 5px 0;">
                ADD SERVICE
            </div>
            <a class="btn <?= ($canAddLeg) ? '' : 'disabled' ?>"
               href="<?= $this->url('leg', array('action' => 'add', 'id' => $this->header->id)) ?>">
                <i class="icon-plane"></i> LEG</a>
            <a class="btn <?= ($canAddServices) ? '' : 'disabled' ?>"
               href="<?= $this->url('refuel', array('action' => 'add', 'id' => $this->header->id)) ?>">
                <i class="icon-plane"></i> Refuel</a>
            <a class="btn <?= ($canAddServices) ? '' : 'disabled' ?>"
               href="<?= $this->url('permission', array('action' => 'add', 'id' => $this->header->id)) ?>">
                <i class="icon-plane"></i> Permission</a>
            <a class="btn <?= ($canAddServices) ? '' : 'disabled' ?>"
               href="<?= $this->url('apService', array('action' => 'add', 'id' => $this->header->id)) ?>">
                <i class="icon-plane"></i> AP Service</a>
        </div>
    </div>

    <? if ($legsCount > 0): ?>
        <legend>LEGs</legend>
        <?=
        $this->partial('fc-flight/_widgets/tables/leg.phtml',
            array('legs' => $this->legs, 'header' => $this->header, 'currentId' => $this->currentId))
        ?>
    <? endif; ?>
</div>
