<?php
$title = 'Search refuels (step 1)';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
</ul>

<h1><?= $title ?></h1>

<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        Form fields are not filled in correctly.
    </div>
<?php else: ?>
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php endif; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('management/refuel', array('action' => 'step1')));
$form->prepare();
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('csrf')) . PHP_EOL;
?>

<table class="table ">
    <thead>
    <tr>
        <th colspan=1"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            $field = $form->get('submitBtn');
            echo $this->formElement($field);
            ?>
        </td>
    </tr>
    </tbody>
</table>
<?= $this->form()->closeTag() ?>
