<?php
$title = 'Show income refuel invoice';
$this->headTitle($title);
?>
    <ul class="breadcrumb">
        <li><a href="/">Home</a> <span class="divider">/</span></li>
        <li>Management <span class="divider">/</span></li>
        <li>Refuel income invoice<span class="divider">/</span></li>
        <li><?= $this->header->invoiceNumber ?></li>
    </ul>

    <h1><?= $title ?></h1>

<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-error')); ?>

    <table id="invoiceHeader" class="table-bordered table-condensed">
        <thead>
        <tr>
            <th>Number of invoice</th>
            <th>Date</th>
            <th>Currency</th>
            <th>Exchange Rate</th>
            <th>Fuel supplier</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?= $this->header->invoiceNumber ?>
            </td>
            <td>
                <?= $this->header->invoiceDate ?>
            </td>
            <td>
                <?= $this->header->invoiceCurrency ?>
            </td>
            <td>
                <?= $this->header->invoiceExchangeRate ?>
            </td>
            <td>
                <?= $this->header->invoiceRefuelSupplierName ?>
            </td>
        </tr>
        </tbody>
    </table>
    <br/>
<?=
$this->partial('fc-flight-management/_widgets/tables/feruel-income-invoice.phtml',
    array(
        'header' => $this->header,
    )
)
?>