<?php
$title = 'Make refuel invoice';
$this->headTitle($title);
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li>Management <span class="divider">/</span></li>
    <li>Refuel</li>
</ul>

<h1><?= $title ?></h1>

<? if($this->result): ?>
    <?=
    $this->partial('fc-flight-management/_widgets/forms/refuel-step2.phtml',
        array(
            'data' => $this->result,
            'units' => $this->units,
            'currencies' => $this->currencies,
            'fixedHeader' => true,
        ))
    ?>
<? endif; ?>
