<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Logs</li>
</ul>
<?php
$title = 'Logs';
$this->headTitle($title);
$url_order = 'ASC';
if ($order) {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 leftPanes">
                        <?php echo $this->partial('fc-log-events/widgets/form/search/default.phtml', array('form' => $searchForm)); ?>
        </div>
        <div class="span10 rightPanes">
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>

            <table class="table table-bordered table-hover table-condensed">
                <tr>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'username', 'order' => $url_order)); ?>">
                            User
                            <?php if ($order_by == 'username'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'ipaddress', 'order' => $url_order)); ?>">
                            IP
                            <?php if ($order_by == 'ipaddress'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'priority', 'order' => $url_order)); ?>">
                            Priority
                            <?php if ($order_by == 'priority'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        <a href="<?php echo $this->url($route, array('order_by' => 'timestamp', 'order' => $url_order)); ?>">
                            Time
                            <?php if ($order_by == 'timestamp'): ?>
                                <i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
                            <?php endif; ?>
                        </a>
                    </th>
                    <th>
                        Message
                    </th>
                </tr>
                <?php foreach ($pagination as $row) : ?>
                    <?php
                    switch ($row->priority) {
                        case 4:
                            $trClass = 'error';
                            break;
                        case 5:
                            $trClass = 'warning';
                            break;
                        case 6:
                            $trClass = 'info';
                            break;
                        default:
                            $trClass = 'default';
                    }
                    $row->timestamp = \DateTime::createFromFormat('Y-m-d H:i:s', $row->timestamp)->getTimestamp();
                    $row->timestamp = date('d-m-Y H:i:s', $row->timestamp);
                    ?>
                    <tr class="<?= $trClass; ?>">
                        <td><?php echo $this->escapeHtml($row->username); ?></td>
                        <td><?php echo $this->escapeHtml($row->ipaddress); ?></td>
                        <td><?php echo $this->escapeHtml($row->priorityName); ?></td>
                        <td><?php echo $this->escapeHtml($row->timestamp); ?></td>
                        <td><?php echo $this->escapeHtml($row->message); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?php
            echo $this->paginationControl(
                $pagination, 'Sliding', 'libraries-pagination-slide', array(
                'order_by' => $order_by,
                'order' => $order,
                'route' => $route,
            ));
            ?>

        </div>
    </div>
</div>
