<?php
$title = 'Edit City';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$displayOptions = array(
    'class' => 'form-horizontal',
    'elements' => array(
        'name' => array(
            'required' => true,
        ),
        'country_id' => array(
            'required' => true,
        ),
    ),
);
$form = $this->form;
$form->setAttribute('action', $this->url(
    'zfcadmin/city',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
?>

<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong>Invalid input!</strong>
    Form fields are not filled in correctly.
</div>
<?php endif; ?>

<?php echo $this->formTwb($form, $formType, $displayOptions); ?>
