<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FcFlight\Controller\FlightController' => __DIR__ . '/src/FcFlight/Controller/FlightController.php',
  'FcFlight\Controller\LegController'    => __DIR__ . '/src/FcFlight/Controller/LegController.php',
  'FcFlight\Controller\RefuelController' => __DIR__ . '/src/FcFlight/Controller/RefuelController.php',
  'FcFlight\Controller\SearchController' => __DIR__ . '/src/FcFlight/Controller/SearchController.php',
  'FcFlight\Filter\FlightHeaderFilter'   => __DIR__ . '/src/FcFlight/Filter/FlightHeaderFilter.php',
  'FcFlight\Filter\LegFilter'            => __DIR__ . '/src/FcFlight/Filter/LegFilter.php',
  'FcFlight\Filter\RefuelFilter'         => __DIR__ . '/src/FcFlight/Filter/RefuelFilter.php',
  'FcFlight\Filter\SearchFilter'         => __DIR__ . '/src/FcFlight/Filter/SearchFilter.php',
  'FcFlight\Form\BaseForm'               => __DIR__ . '/src/FcFlight/Form/BaseForm.php',
  'FcFlight\Form\FlightHeaderForm'       => __DIR__ . '/src/FcFlight/Form/FlightHeaderForm.php',
  'FcFlight\Form\LegForm'                => __DIR__ . '/src/FcFlight/Form/LegForm.php',
  'FcFlight\Form\RefuelForm'             => __DIR__ . '/src/FcFlight/Form/RefuelForm.php',
  'FcFlight\Form\SearchForm'             => __DIR__ . '/src/FcFlight/Form/SearchForm.php',
  'FcFlight\Model\FlightHeaderModel'     => __DIR__ . '/src/FcFlight/Model/FlightHeaderModel.php',
  'FcFlight\Model\LegModel'              => __DIR__ . '/src/FcFlight/Model/LegModel.php',
  'FcFlight\Model\RefuelModel'           => __DIR__ . '/src/FcFlight/Model/RefuelModel.php',
  'FcFlight\Model\SearchModel'           => __DIR__ . '/src/FcFlight/Model/SearchModel.php',
  'FcFlight\Module'                      => __DIR__ . '/Module.php',
  'FcFlight\Validator\FlightDateChecker' => __DIR__ . '/src/FcFlight/Validator/FlightDateChecker.php',
  'FcFlight\Validator\FlightYearChecker' => __DIR__ . '/src/FcFlight/Validator/FlightYearChecker.php',
);
