<?php
$title = 'Редактирование сотрудника';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'zfcadmin/user',
    array(
        'action' => 'edit',
        'id'     => $this->user_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
